// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRefClient creates a new instance of MockRefClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRefClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRefClient {
	mock := &MockRefClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRefClient is an autogenerated mock type for the RefClient type
type MockRefClient struct {
	mock.Mock
}

type MockRefClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRefClient) EXPECT() *MockRefClient_Expecter {
	return &MockRefClient_Expecter{mock: &_m.Mock}
}

// GetSecretFromRef provides a mock function for the type MockRefClient
func (_mock *MockRefClient) GetSecretFromRef(ctx context.Context, refVal string, secretNamespace string) (string, error) {
	ret := _mock.Called(ctx, refVal, secretNamespace)

	if len(ret) == 0 {
		panic("no return value specified for GetSecretFromRef")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return returnFunc(ctx, refVal, secretNamespace)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = returnFunc(ctx, refVal, secretNamespace)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, refVal, secretNamespace)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRefClient_GetSecretFromRef_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSecretFromRef'
type MockRefClient_GetSecretFromRef_Call struct {
	*mock.Call
}

// GetSecretFromRef is a helper method to define mock.On call
//   - ctx context.Context
//   - refVal string
//   - secretNamespace string
func (_e *MockRefClient_Expecter) GetSecretFromRef(ctx interface{}, refVal interface{}, secretNamespace interface{}) *MockRefClient_GetSecretFromRef_Call {
	return &MockRefClient_GetSecretFromRef_Call{Call: _e.mock.On("GetSecretFromRef", ctx, refVal, secretNamespace)}
}

func (_c *MockRefClient_GetSecretFromRef_Call) Run(run func(ctx context.Context, refVal string, secretNamespace string)) *MockRefClient_GetSecretFromRef_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRefClient_GetSecretFromRef_Call) Return(s string, err error) *MockRefClient_GetSecretFromRef_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockRefClient_GetSecretFromRef_Call) RunAndReturn(run func(ctx context.Context, refVal string, secretNamespace string) (string, error)) *MockRefClient_GetSecretFromRef_Call {
	_c.Call.Return(run)
	return _c
}

// MapComponentConfigSecretsRefs provides a mock function for the type MockRefClient
func (_mock *MockRefClient) MapComponentConfigSecretsRefs(ctx context.Context, config map[string][]string, namespace string) error {
	ret := _mock.Called(ctx, config, namespace)

	if len(ret) == 0 {
		panic("no return value specified for MapComponentConfigSecretsRefs")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string][]string, string) error); ok {
		r0 = returnFunc(ctx, config, namespace)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRefClient_MapComponentConfigSecretsRefs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MapComponentConfigSecretsRefs'
type MockRefClient_MapComponentConfigSecretsRefs_Call struct {
	*mock.Call
}

// MapComponentConfigSecretsRefs is a helper method to define mock.On call
//   - ctx context.Context
//   - config map[string][]string
//   - namespace string
func (_e *MockRefClient_Expecter) MapComponentConfigSecretsRefs(ctx interface{}, config interface{}, namespace interface{}) *MockRefClient_MapComponentConfigSecretsRefs_Call {
	return &MockRefClient_MapComponentConfigSecretsRefs_Call{Call: _e.mock.On("MapComponentConfigSecretsRefs", ctx, config, namespace)}
}

func (_c *MockRefClient_MapComponentConfigSecretsRefs_Call) Run(run func(ctx context.Context, config map[string][]string, namespace string)) *MockRefClient_MapComponentConfigSecretsRefs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 map[string][]string
		if args[1] != nil {
			arg1 = args[1].(map[string][]string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRefClient_MapComponentConfigSecretsRefs_Call) Return(err error) *MockRefClient_MapComponentConfigSecretsRefs_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRefClient_MapComponentConfigSecretsRefs_Call) RunAndReturn(run func(ctx context.Context, config map[string][]string, namespace string) error) *MockRefClient_MapComponentConfigSecretsRefs_Call {
	_c.Call.Return(run)
	return _c
}

// MapConfigSecretsRefs provides a mock function for the type MockRefClient
func (_mock *MockRefClient) MapConfigSecretsRefs(ctx context.Context, config map[string]string, namespace string) error {
	ret := _mock.Called(ctx, config, namespace)

	if len(ret) == 0 {
		panic("no return value specified for MapConfigSecretsRefs")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string]string, string) error); ok {
		r0 = returnFunc(ctx, config, namespace)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRefClient_MapConfigSecretsRefs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MapConfigSecretsRefs'
type MockRefClient_MapConfigSecretsRefs_Call struct {
	*mock.Call
}

// MapConfigSecretsRefs is a helper method to define mock.On call
//   - ctx context.Context
//   - config map[string]string
//   - namespace string
func (_e *MockRefClient_Expecter) MapConfigSecretsRefs(ctx interface{}, config interface{}, namespace interface{}) *MockRefClient_MapConfigSecretsRefs_Call {
	return &MockRefClient_MapConfigSecretsRefs_Call{Call: _e.mock.On("MapConfigSecretsRefs", ctx, config, namespace)}
}

func (_c *MockRefClient_MapConfigSecretsRefs_Call) Run(run func(ctx context.Context, config map[string]string, namespace string)) *MockRefClient_MapConfigSecretsRefs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 map[string]string
		if args[1] != nil {
			arg1 = args[1].(map[string]string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRefClient_MapConfigSecretsRefs_Call) Return(err error) *MockRefClient_MapConfigSecretsRefs_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRefClient_MapConfigSecretsRefs_Call) RunAndReturn(run func(ctx context.Context, config map[string]string, namespace string) error) *MockRefClient_MapConfigSecretsRefs_Call {
	_c.Call.Return(run)
	return _c
}
