dir: '{{.InterfaceDir}}/mocks'
structname: Mock{{.InterfaceName}}
pkgname: mocks
template: testify
filename: "{{ .InterfaceName | snakecase }}_generated.mock.go"
template-data:
  unroll-variadic: true
packages:
  github.com/epam/edp-keycloak-operator/pkg/client/keycloak:
    interfaces:
      Client: {}
  github.com/epam/edp-keycloak-operator/pkg/client/keycloak/adapter:
    interfaces:
      GoCloak: {}
