ignore:
  - "**/*_test.go"
  - "**/config/**"
  - "**/deploy-templates/**"
  - "**/factory.go"
  - "**/*_generated.*go"
  - "**/*_mock.go"
  - "**/mock_*.go"
  - "**/.github/**"
  - "**/api/**"
  - "**/tests/**"
  - "**/hack/**"
  - "**/bundle/**"
  - "**/main.go"
  - "**/testutils/**"
