apiVersion: v1.edp.epam.com/v1alpha1
kind: KeycloakClientScope
metadata:
  name: groups
spec:
  name: groups
  realm: main
  description: "Group Membership"
  protocol: openid-connect
  protocolMappers:
    - name: groups
      protocol: openid-connect
      protocolMapper: "oidc-group-membership-mapper"
      config:
        "access.token.claim": "true"
        "claim.name": "groups"
        "full.path": "false"
        "id.token.claim": "true"
        "userinfo.token.claim": "true"
