apiVersion: v1.edp.epam.com/v1
kind: KeycloakClientScope
metadata:
  name: test-role-list
spec:
  name: role_list
  realm: d1-id-k8s-realm-name
  description: "test role list"
  protocol: saml
  protocolMappers:
    - name: "role list"
      protocol: saml
      protocolMapper: "saml-role-list-mapper"
      config:
        "friendly.name": "za123"
        "attribute.name": "Role"
        "attribute.nameformat": "Basic"
        "single": "false"

