apiVersion: v1.edp.epam.com/v1alpha1
kind: ClusterKeycloakRealm
metadata:
  name: clusterkeycloakrealm-sample
spec:
  clusterKeycloakRef: clusterkeycloak-sample
  realmName: realm-sample1234
  authenticationFlows:
    browserFlow: browserFlow-sample
  login:
    userRegistration: true
    forgotPassword: true
    rememberMe: true
    emailAsUsername: false
    loginWithEmail: true
    duplicateEmails: false
    verifyEmail: true
    editUsername: false
