apiVersion: v1.edp.epam.com/v1
kind: KeycloakClient
metadata:
  name: keycloakclient-sample
spec:
  targetRealm: realm-sample
  advancedProtocolMappers: true
  clientId: agocd
  directAccess: true
  public: false
  secret: ''
  webUrl: https://argocd.example.com
  defaultClientScopes:
    - groups
