apiVersion: v1.edp.epam.com/v1
kind: KeycloakRealm
metadata:
  name: keycloakrealm-sample
spec:
  id: bfebeff6-ac63-4b46-a1f3-37df5099a9c4
  realmName: realm-sample
  keycloakRef:
    name: keycloak-sample
    kind: Keycloak
  ssoRealmName: master
  ssoRealmEnabled: false
  ssoAutoRedirectEnabled: false
  passwordPolicy:
    - type: "forceExpiredPasswordChange"
      value: "365"
    - type: "length"
      value: "8"
  realmEventConfig:
    adminEventsDetailsEnabled: false
    adminEventsEnabled: true
    enabledEventTypes:
      - UPDATE_CONSENT_ERROR
      - CLIENT_LOGIN
    eventsEnabled: true
    eventsExpiration: 15000
    eventsListeners:
      - jboss-logging
