apiVersion: v1.edp.epam.com/v1
kind: KeycloakRealmIdentityProvider
metadata:
  name: keycloakrealmidentityprovider-sample
spec:
  realmRef:
    kind: KeycloakRealm
    name: keycloakrealm-sample
  alias: github
  authenticateByDefault: false
  enabled: true
  firstBrokerLoginFlowAlias: "first broker login"
  postBrokerLoginFlowAlias: "browser"
  providerId: "github"
  config:
    clientId: "foo"
    clientSecret: "$test-idp-secret:secret"
    syncMode: "IMPORT"
    useJwksUrl: "true"
  mappers:
    - name: "test-33221"
      identityProviderMapper: "hardcoded-attribute-idp-mapper"
      identityProviderAlias: "github"
      config:
        attribute: "foo"
        "attribute.value": "bar"
        syncMode: "IMPORT"

---
  
apiVersion: v1
kind: Secret
metadata:
  name: test-idp-secret
type: Opaque
data:
  secret: "c2VjcmV0"  # base64 encoded value of "secret"