apiVersion: v1.edp.epam.com/v1
kind: KeycloakRealmUser
metadata:
  name: d1-user-test1
spec:
  realm: d1-id-k8s-realm-name
  username: "john.snow13"
  firstName: "John"
  lastName: "Snow"
  email: "john.snow13@gmail.com"
  enabled: true
  emailVerified: true
  password: "12345678"
  keepResource: true
  requiredUserActions:
    - UPDATE_PASSWORD
  attributes:
    foo: "bar"
    baz: "jazz"
