apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: keycloakrealmidentityproviders.v1.edp.epam.com
spec:
  group: v1.edp.epam.com
  names:
    kind: KeycloakRealmIdentityProvider
    listKind: KeycloakRealmIdentityProviderList
    plural: keycloakrealmidentityproviders
    singular: keycloakrealmidentityprovider
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation
                  of an object. Servers should convert recognized schemas to the latest
                  internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this
                  object represents. Servers may infer this from the endpoint the client
                  submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              properties:
                realm:
                  description: 'keycloak realm name'
                  type: string
                providerId:
                  type: string
                config:
                  nullable: true
                  type: object
                  additionalProperties: true
                addReadTokenRoleOnCreate:
                  type: boolean
                alias:
                  type: string
                authenticateByDefault:
                  type: boolean
                displayName:
                  type: string
                enabled:
                  type: boolean
                firstBrokerLoginFlowAlias:
                  type: string
                linkOnly:
                  type: boolean
                storeToken:
                  type: boolean
                trustEmail:
                  type: boolean
                mappers:
                  nullable: true
                  type: array
                  items:
                    type: object
                    properties:
                      identityProviderAlias:
                        type: string
                      identityProviderMapper:
                        type: string
                      name:
                        type: string
                      config:
                        nullable: true
                        type: object
                        additionalProperties: true
              required:
                - realm
                - providerId
                - alias
                - enabled
                - config
              type: object
            status:
              type: object
              additionalProperties: true
      subresources:
        status: {}