apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: keycloakrealmgroups.v1.edp.epam.com
spec:
  group: v1.edp.epam.com
  names:
    kind: KeycloakRealmGroup
    listKind: KeycloakRealmGroupList
    plural: keycloakrealmgroups
    singular: keycloakrealmgroup
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation
                  of an object. Servers should convert recognized schemas to the latest
                  internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this
                  object represents. Servers may infer this from the endpoint the client
                  submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              properties:
                name:
                  type: string
                  description: 'group name'
                realm:
                  description: 'keycloak realm name'
                  type: string
                path:
                  type: string
                attributes:
                  nullable: true
                  type: object
                  additionalProperties: true
                access:
                  nullable: true
                  type: object
                  additionalProperties: true
                realmRoles:
                  type: array
                  items:
                    type: string
                clientRoles:
                  type: array
                  items:
                    type: object
                    additionalProperties: true
                subGroups:
                  type: array
                  items:
                    type: string
              required:
                - realm
                - name
              type: object
            status:
              type: object
              additionalProperties: true
      subresources:
        status: {}