apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: keycloakauthflows.v1.edp.epam.com
spec:
  group: v1.edp.epam.com
  names:
    kind: KeycloakAuthFlow
    listKind: KeycloakAuthFlowList
    plural: keycloakauthflows
    singular: keycloakauthflow
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
                  of an object. Servers should convert recognized schemas to the latest
                  internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
                  object represents. Servers may infer this from the endpoint the client
                  submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              realm:
                description: 'keycloak realm name'
                type: string
              alias:
                type: string
              description:
                type: string
              providerId:
                type: string
                description: "providerId for root auth flow and provider for child auth flows"
              topLevel:
                type: boolean
              builtIn:
                type: boolean
              parentName:
                type: string
              childType:
                type: string
                description: "type for auth flow if it has a parent, available options: basic-flow, form-flow"
              authenticationExecutions:
                nullable: true
                type: array
                items:
                  type: object
                  properties:
                    authenticator:
                      type: string
                    authenticatorConfig:
                      nullable: true
                      type: object
                      properties:
                        alias:
                          type: string
                        config:
                          type: object
                          nullable: true
                          additionalProperties: true
                    priority:
                      type: integer
                    requirement:
                      type: string
                    authenticatorFlow:
                      type: boolean
                    alias:
                      type: string
            required:
              - realm
              - alias
              - providerId
              - topLevel
              - builtIn
            type: object
          status:
            type: object
            additionalProperties: true
    subresources:
      status: {}