apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: keycloakrealmusers.v1.edp.epam.com
spec:
  group: v1.edp.epam.com
  names:
    kind: KeycloakRealmUser
    listKind: KeycloakRealmUserList
    plural: keycloakrealmusers
    singular: keycloakrealmuser
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation
                  of an object. Servers should convert recognized schemas to the latest
                  internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this
                  object represents. Servers may infer this from the endpoint the client
                  submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              properties:
                realm:
                  description: 'keycloak realm name'
                  type: string
                username:
                  type: string
                  description: "user name"
                email:
                  type: string
                  description: "user email"
                firstName:
                  type: string
                  description: "user first name"
                lastName:
                  type: string
                  description: "user last name"
                enabled:
                  type: boolean
                  description: "user is enabled"
                emailVerified:
                  type: boolean
                  description: "is user email verified"
                requiredUserActions:
                  description: "required user actions, require action when user log in, example: CONFIGURE_TOTP, UPDATE_PASSWORD, UPDATE_PROFILE, VERIFY_EMAIL, update_user_locale"
                  type: array
                  nullable: true
                  items:
                    type: string
                roles:
                  description: "user realm roles"
                  type: array
                  nullable: true
                  items:
                    type: string
                groups:
                  description: "user realm groups"
                  type: array
                  nullable: true
                  items:
                    type: string
                attributes:
                  description: "user attributes"
                  type: object
                  additionalProperties: true
              required:
                - realm
                - username
              type: object
            status:
              type: object
              additionalProperties: true
      subresources:
        status: { }