# permissions for end users to edit clusterkeycloakrealms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: clusterkeycloakrealm-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: edp-keycloak-operator
    app.kubernetes.io/part-of: edp-keycloak-operator
    app.kubernetes.io/managed-by: kustomize
  name: clusterkeycloakrealm-editor-role
rules:
- apiGroups:
  - v1.edp.epam.com
  resources:
  - clusterkeycloakrealms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - v1.edp.epam.com
  resources:
  - clusterkeycloakrealms/status
  verbs:
  - get
