# permissions for end users to edit keycloakrealmrolebatches.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keycloakrealmrolebatch-editor-role
rules:
- apiGroups:
  - v1.edp.epam.com
  resources:
  - keycloakrealmrolebatches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - v1.edp.epam.com
  resources:
  - keycloakrealmrolebatches/status
  verbs:
  - get
