# permissions for end users to edit keycloakrealmgroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keycloakrealmgroup-editor-role
rules:
- apiGroups:
  - v1.edp.epam.com
  resources:
  - keycloakrealmgroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - v1.edp.epam.com
  resources:
  - keycloakrealmgroups/status
  verbs:
  - get
