# permissions for end users to edit keycloakrealmroles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keycloakrealmrole-editor-role
rules:
- apiGroups:
  - v1.edp.epam.com
  resources:
  - keycloakrealmroles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - v1.edp.epam.com
  resources:
  - keycloakrealmroles/status
  verbs:
  - get
