# permissions for end users to edit keycloaks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: keycloak-operator
    app.kubernetes.io/managed-by: kustomize
  name: keycloak-editor-role
rules:
- apiGroups:
  - v1.edp.epam.com
  resources:
  - keycloaks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - v1.edp.epam.com
  resources:
  - keycloaks/status
  verbs:
  - get
