# permissions for end users to view keycloakauthflows.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: keycloak-operator
    app.kubernetes.io/managed-by: kustomize
  name: keycloakauthflow-viewer-role
rules:
- apiGroups:
  - v1.edp.epam.com
  resources:
  - keycloakauthflows
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - v1.edp.epam.com
  resources:
  - keycloakauthflows/status
  verbs:
  - get
