# permissions for end users to view keycloakrealms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keycloakrealm-viewer-role
rules:
- apiGroups:
  - v1.edp.epam.com
  resources:
  - keycloakrealms
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - v1.edp.epam.com
  resources:
  - keycloakrealms/status
  verbs:
  - get
