# permissions for end users to view keycloakrealmidentityproviders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keycloakrealmidentityprovider-viewer-role
rules:
- apiGroups:
  - v1.edp.epam.com
  resources:
  - keycloakrealmidentityproviders
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - v1.edp.epam.com
  resources:
  - keycloakrealmidentityproviders/status
  verbs:
  - get
