# permissions for end users to view keycloakrealmgroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keycloakrealmgroup-viewer-role
rules:
- apiGroups:
  - v1.edp.epam.com
  resources:
  - keycloakrealmgroups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - v1.edp.epam.com
  resources:
  - keycloakrealmgroups/status
  verbs:
  - get
