# permissions for end users to edit keycloakrealmcomponents.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keycloakrealmcomponent-editor-role
rules:
- apiGroups:
  - v1.edp.epam.com
  resources:
  - keycloakrealmcomponents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - v1.edp.epam.com
  resources:
  - keycloakrealmcomponents/status
  verbs:
  - get
