# permissions for end users to view keycloakrealmroles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keycloakrealmrole-viewer-role
rules:
- apiGroups:
  - v1.edp.epam.com
  resources:
  - keycloakrealmroles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - v1.edp.epam.com
  resources:
  - keycloakrealmroles/status
  verbs:
  - get
