# permissions for end users to edit keycloakrealmusers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keycloakrealmuser-editor-role
rules:
- apiGroups:
  - v1.edp.epam.com
  resources:
  - keycloakrealmusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - v1.edp.epam.com
  resources:
  - keycloakrealmusers/status
  verbs:
  - get
