// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/epam/edp-keycloak-operator/pkg/client/keycloakapi"
	mock "github.com/stretchr/testify/mock"
)

// NewMockEventsClient creates a new instance of MockEventsClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventsClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventsClient {
	mock := &MockEventsClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEventsClient is an autogenerated mock type for the EventsClient type
type MockEventsClient struct {
	mock.Mock
}

type MockEventsClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventsClient) EXPECT() *MockEventsClient_Expecter {
	return &MockEventsClient_Expecter{mock: &_m.Mock}
}

// ClearAllBruteForce provides a mock function for the type MockEventsClient
func (_mock *MockEventsClient) ClearAllBruteForce(ctx context.Context, realm string) (*keycloakapi.Response, error) {
	ret := _mock.Called(ctx, realm)

	if len(ret) == 0 {
		panic("no return value specified for ClearAllBruteForce")
	}

	var r0 *keycloakapi.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*keycloakapi.Response, error)); ok {
		return returnFunc(ctx, realm)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *keycloakapi.Response); ok {
		r0 = returnFunc(ctx, realm)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*keycloakapi.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, realm)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEventsClient_ClearAllBruteForce_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearAllBruteForce'
type MockEventsClient_ClearAllBruteForce_Call struct {
	*mock.Call
}

// ClearAllBruteForce is a helper method to define mock.On call
//   - ctx context.Context
//   - realm string
func (_e *MockEventsClient_Expecter) ClearAllBruteForce(ctx interface{}, realm interface{}) *MockEventsClient_ClearAllBruteForce_Call {
	return &MockEventsClient_ClearAllBruteForce_Call{Call: _e.mock.On("ClearAllBruteForce", ctx, realm)}
}

func (_c *MockEventsClient_ClearAllBruteForce_Call) Run(run func(ctx context.Context, realm string)) *MockEventsClient_ClearAllBruteForce_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventsClient_ClearAllBruteForce_Call) Return(response *keycloakapi.Response, err error) *MockEventsClient_ClearAllBruteForce_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockEventsClient_ClearAllBruteForce_Call) RunAndReturn(run func(ctx context.Context, realm string) (*keycloakapi.Response, error)) *MockEventsClient_ClearAllBruteForce_Call {
	_c.Call.Return(run)
	return _c
}

// ClearBruteForceForUser provides a mock function for the type MockEventsClient
func (_mock *MockEventsClient) ClearBruteForceForUser(ctx context.Context, realm string, userID string) (*keycloakapi.Response, error) {
	ret := _mock.Called(ctx, realm, userID)

	if len(ret) == 0 {
		panic("no return value specified for ClearBruteForceForUser")
	}

	var r0 *keycloakapi.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*keycloakapi.Response, error)); ok {
		return returnFunc(ctx, realm, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *keycloakapi.Response); ok {
		r0 = returnFunc(ctx, realm, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*keycloakapi.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, realm, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEventsClient_ClearBruteForceForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearBruteForceForUser'
type MockEventsClient_ClearBruteForceForUser_Call struct {
	*mock.Call
}

// ClearBruteForceForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - realm string
//   - userID string
func (_e *MockEventsClient_Expecter) ClearBruteForceForUser(ctx interface{}, realm interface{}, userID interface{}) *MockEventsClient_ClearBruteForceForUser_Call {
	return &MockEventsClient_ClearBruteForceForUser_Call{Call: _e.mock.On("ClearBruteForceForUser", ctx, realm, userID)}
}

func (_c *MockEventsClient_ClearBruteForceForUser_Call) Run(run func(ctx context.Context, realm string, userID string)) *MockEventsClient_ClearBruteForceForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEventsClient_ClearBruteForceForUser_Call) Return(response *keycloakapi.Response, err error) *MockEventsClient_ClearBruteForceForUser_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockEventsClient_ClearBruteForceForUser_Call) RunAndReturn(run func(ctx context.Context, realm string, userID string) (*keycloakapi.Response, error)) *MockEventsClient_ClearBruteForceForUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAdminEvents provides a mock function for the type MockEventsClient
func (_mock *MockEventsClient) DeleteAdminEvents(ctx context.Context, realm string) (*keycloakapi.Response, error) {
	ret := _mock.Called(ctx, realm)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAdminEvents")
	}

	var r0 *keycloakapi.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*keycloakapi.Response, error)); ok {
		return returnFunc(ctx, realm)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *keycloakapi.Response); ok {
		r0 = returnFunc(ctx, realm)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*keycloakapi.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, realm)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEventsClient_DeleteAdminEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAdminEvents'
type MockEventsClient_DeleteAdminEvents_Call struct {
	*mock.Call
}

// DeleteAdminEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - realm string
func (_e *MockEventsClient_Expecter) DeleteAdminEvents(ctx interface{}, realm interface{}) *MockEventsClient_DeleteAdminEvents_Call {
	return &MockEventsClient_DeleteAdminEvents_Call{Call: _e.mock.On("DeleteAdminEvents", ctx, realm)}
}

func (_c *MockEventsClient_DeleteAdminEvents_Call) Run(run func(ctx context.Context, realm string)) *MockEventsClient_DeleteAdminEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventsClient_DeleteAdminEvents_Call) Return(response *keycloakapi.Response, err error) *MockEventsClient_DeleteAdminEvents_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockEventsClient_DeleteAdminEvents_Call) RunAndReturn(run func(ctx context.Context, realm string) (*keycloakapi.Response, error)) *MockEventsClient_DeleteAdminEvents_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteEvents provides a mock function for the type MockEventsClient
func (_mock *MockEventsClient) DeleteEvents(ctx context.Context, realm string) (*keycloakapi.Response, error) {
	ret := _mock.Called(ctx, realm)

	if len(ret) == 0 {
		panic("no return value specified for DeleteEvents")
	}

	var r0 *keycloakapi.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*keycloakapi.Response, error)); ok {
		return returnFunc(ctx, realm)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *keycloakapi.Response); ok {
		r0 = returnFunc(ctx, realm)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*keycloakapi.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, realm)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEventsClient_DeleteEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteEvents'
type MockEventsClient_DeleteEvents_Call struct {
	*mock.Call
}

// DeleteEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - realm string
func (_e *MockEventsClient_Expecter) DeleteEvents(ctx interface{}, realm interface{}) *MockEventsClient_DeleteEvents_Call {
	return &MockEventsClient_DeleteEvents_Call{Call: _e.mock.On("DeleteEvents", ctx, realm)}
}

func (_c *MockEventsClient_DeleteEvents_Call) Run(run func(ctx context.Context, realm string)) *MockEventsClient_DeleteEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventsClient_DeleteEvents_Call) Return(response *keycloakapi.Response, err error) *MockEventsClient_DeleteEvents_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockEventsClient_DeleteEvents_Call) RunAndReturn(run func(ctx context.Context, realm string) (*keycloakapi.Response, error)) *MockEventsClient_DeleteEvents_Call {
	_c.Call.Return(run)
	return _c
}

// GetAdminEvents provides a mock function for the type MockEventsClient
func (_mock *MockEventsClient) GetAdminEvents(ctx context.Context, realm string, params *keycloakapi.GetAdminEventsParams) ([]keycloakapi.AdminEventRepresentation, *keycloakapi.Response, error) {
	ret := _mock.Called(ctx, realm, params)

	if len(ret) == 0 {
		panic("no return value specified for GetAdminEvents")
	}

	var r0 []keycloakapi.AdminEventRepresentation
	var r1 *keycloakapi.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *keycloakapi.GetAdminEventsParams) ([]keycloakapi.AdminEventRepresentation, *keycloakapi.Response, error)); ok {
		return returnFunc(ctx, realm, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *keycloakapi.GetAdminEventsParams) []keycloakapi.AdminEventRepresentation); ok {
		r0 = returnFunc(ctx, realm, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]keycloakapi.AdminEventRepresentation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *keycloakapi.GetAdminEventsParams) *keycloakapi.Response); ok {
		r1 = returnFunc(ctx, realm, params)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*keycloakapi.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, *keycloakapi.GetAdminEventsParams) error); ok {
		r2 = returnFunc(ctx, realm, params)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockEventsClient_GetAdminEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAdminEvents'
type MockEventsClient_GetAdminEvents_Call struct {
	*mock.Call
}

// GetAdminEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - realm string
//   - params *keycloakapi.GetAdminEventsParams
func (_e *MockEventsClient_Expecter) GetAdminEvents(ctx interface{}, realm interface{}, params interface{}) *MockEventsClient_GetAdminEvents_Call {
	return &MockEventsClient_GetAdminEvents_Call{Call: _e.mock.On("GetAdminEvents", ctx, realm, params)}
}

func (_c *MockEventsClient_GetAdminEvents_Call) Run(run func(ctx context.Context, realm string, params *keycloakapi.GetAdminEventsParams)) *MockEventsClient_GetAdminEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *keycloakapi.GetAdminEventsParams
		if args[2] != nil {
			arg2 = args[2].(*keycloakapi.GetAdminEventsParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEventsClient_GetAdminEvents_Call) Return(vs []keycloakapi.AdminEventRepresentation, response *keycloakapi.Response, err error) *MockEventsClient_GetAdminEvents_Call {
	_c.Call.Return(vs, response, err)
	return _c
}

func (_c *MockEventsClient_GetAdminEvents_Call) RunAndReturn(run func(ctx context.Context, realm string, params *keycloakapi.GetAdminEventsParams) ([]keycloakapi.AdminEventRepresentation, *keycloakapi.Response, error)) *MockEventsClient_GetAdminEvents_Call {
	_c.Call.Return(run)
	return _c
}

// GetBruteForceStatus provides a mock function for the type MockEventsClient
func (_mock *MockEventsClient) GetBruteForceStatus(ctx context.Context, realm string, userID string) (map[string]any, *keycloakapi.Response, error) {
	ret := _mock.Called(ctx, realm, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetBruteForceStatus")
	}

	var r0 map[string]any
	var r1 *keycloakapi.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (map[string]any, *keycloakapi.Response, error)); ok {
		return returnFunc(ctx, realm, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) map[string]any); ok {
		r0 = returnFunc(ctx, realm, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) *keycloakapi.Response); ok {
		r1 = returnFunc(ctx, realm, userID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*keycloakapi.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = returnFunc(ctx, realm, userID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockEventsClient_GetBruteForceStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBruteForceStatus'
type MockEventsClient_GetBruteForceStatus_Call struct {
	*mock.Call
}

// GetBruteForceStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - realm string
//   - userID string
func (_e *MockEventsClient_Expecter) GetBruteForceStatus(ctx interface{}, realm interface{}, userID interface{}) *MockEventsClient_GetBruteForceStatus_Call {
	return &MockEventsClient_GetBruteForceStatus_Call{Call: _e.mock.On("GetBruteForceStatus", ctx, realm, userID)}
}

func (_c *MockEventsClient_GetBruteForceStatus_Call) Run(run func(ctx context.Context, realm string, userID string)) *MockEventsClient_GetBruteForceStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEventsClient_GetBruteForceStatus_Call) Return(stringToV map[string]any, response *keycloakapi.Response, err error) *MockEventsClient_GetBruteForceStatus_Call {
	_c.Call.Return(stringToV, response, err)
	return _c
}

func (_c *MockEventsClient_GetBruteForceStatus_Call) RunAndReturn(run func(ctx context.Context, realm string, userID string) (map[string]any, *keycloakapi.Response, error)) *MockEventsClient_GetBruteForceStatus_Call {
	_c.Call.Return(run)
	return _c
}

// GetEvents provides a mock function for the type MockEventsClient
func (_mock *MockEventsClient) GetEvents(ctx context.Context, realm string, params *keycloakapi.GetEventsParams) ([]keycloakapi.EventRepresentation, *keycloakapi.Response, error) {
	ret := _mock.Called(ctx, realm, params)

	if len(ret) == 0 {
		panic("no return value specified for GetEvents")
	}

	var r0 []keycloakapi.EventRepresentation
	var r1 *keycloakapi.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *keycloakapi.GetEventsParams) ([]keycloakapi.EventRepresentation, *keycloakapi.Response, error)); ok {
		return returnFunc(ctx, realm, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *keycloakapi.GetEventsParams) []keycloakapi.EventRepresentation); ok {
		r0 = returnFunc(ctx, realm, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]keycloakapi.EventRepresentation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *keycloakapi.GetEventsParams) *keycloakapi.Response); ok {
		r1 = returnFunc(ctx, realm, params)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*keycloakapi.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, *keycloakapi.GetEventsParams) error); ok {
		r2 = returnFunc(ctx, realm, params)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockEventsClient_GetEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEvents'
type MockEventsClient_GetEvents_Call struct {
	*mock.Call
}

// GetEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - realm string
//   - params *keycloakapi.GetEventsParams
func (_e *MockEventsClient_Expecter) GetEvents(ctx interface{}, realm interface{}, params interface{}) *MockEventsClient_GetEvents_Call {
	return &MockEventsClient_GetEvents_Call{Call: _e.mock.On("GetEvents", ctx, realm, params)}
}

func (_c *MockEventsClient_GetEvents_Call) Run(run func(ctx context.Context, realm string, params *keycloakapi.GetEventsParams)) *MockEventsClient_GetEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *keycloakapi.GetEventsParams
		if args[2] != nil {
			arg2 = args[2].(*keycloakapi.GetEventsParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEventsClient_GetEvents_Call) Return(vs []keycloakapi.EventRepresentation, response *keycloakapi.Response, err error) *MockEventsClient_GetEvents_Call {
	_c.Call.Return(vs, response, err)
	return _c
}

func (_c *MockEventsClient_GetEvents_Call) RunAndReturn(run func(ctx context.Context, realm string, params *keycloakapi.GetEventsParams) ([]keycloakapi.EventRepresentation, *keycloakapi.Response, error)) *MockEventsClient_GetEvents_Call {
	_c.Call.Return(run)
	return _c
}

// GetEventsConfig provides a mock function for the type MockEventsClient
func (_mock *MockEventsClient) GetEventsConfig(ctx context.Context, realm string) (*keycloakapi.RealmEventsConfigRepresentation, *keycloakapi.Response, error) {
	ret := _mock.Called(ctx, realm)

	if len(ret) == 0 {
		panic("no return value specified for GetEventsConfig")
	}

	var r0 *keycloakapi.RealmEventsConfigRepresentation
	var r1 *keycloakapi.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*keycloakapi.RealmEventsConfigRepresentation, *keycloakapi.Response, error)); ok {
		return returnFunc(ctx, realm)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *keycloakapi.RealmEventsConfigRepresentation); ok {
		r0 = returnFunc(ctx, realm)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*keycloakapi.RealmEventsConfigRepresentation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) *keycloakapi.Response); ok {
		r1 = returnFunc(ctx, realm)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*keycloakapi.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, realm)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockEventsClient_GetEventsConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEventsConfig'
type MockEventsClient_GetEventsConfig_Call struct {
	*mock.Call
}

// GetEventsConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - realm string
func (_e *MockEventsClient_Expecter) GetEventsConfig(ctx interface{}, realm interface{}) *MockEventsClient_GetEventsConfig_Call {
	return &MockEventsClient_GetEventsConfig_Call{Call: _e.mock.On("GetEventsConfig", ctx, realm)}
}

func (_c *MockEventsClient_GetEventsConfig_Call) Run(run func(ctx context.Context, realm string)) *MockEventsClient_GetEventsConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventsClient_GetEventsConfig_Call) Return(v *keycloakapi.RealmEventsConfigRepresentation, response *keycloakapi.Response, err error) *MockEventsClient_GetEventsConfig_Call {
	_c.Call.Return(v, response, err)
	return _c
}

func (_c *MockEventsClient_GetEventsConfig_Call) RunAndReturn(run func(ctx context.Context, realm string) (*keycloakapi.RealmEventsConfigRepresentation, *keycloakapi.Response, error)) *MockEventsClient_GetEventsConfig_Call {
	_c.Call.Return(run)
	return _c
}

// SetEventsConfig provides a mock function for the type MockEventsClient
func (_mock *MockEventsClient) SetEventsConfig(ctx context.Context, realm string, cfg keycloakapi.RealmEventsConfigRepresentation) (*keycloakapi.Response, error) {
	ret := _mock.Called(ctx, realm, cfg)

	if len(ret) == 0 {
		panic("no return value specified for SetEventsConfig")
	}

	var r0 *keycloakapi.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, keycloakapi.RealmEventsConfigRepresentation) (*keycloakapi.Response, error)); ok {
		return returnFunc(ctx, realm, cfg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, keycloakapi.RealmEventsConfigRepresentation) *keycloakapi.Response); ok {
		r0 = returnFunc(ctx, realm, cfg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*keycloakapi.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, keycloakapi.RealmEventsConfigRepresentation) error); ok {
		r1 = returnFunc(ctx, realm, cfg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEventsClient_SetEventsConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetEventsConfig'
type MockEventsClient_SetEventsConfig_Call struct {
	*mock.Call
}

// SetEventsConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - realm string
//   - cfg keycloakapi.RealmEventsConfigRepresentation
func (_e *MockEventsClient_Expecter) SetEventsConfig(ctx interface{}, realm interface{}, cfg interface{}) *MockEventsClient_SetEventsConfig_Call {
	return &MockEventsClient_SetEventsConfig_Call{Call: _e.mock.On("SetEventsConfig", ctx, realm, cfg)}
}

func (_c *MockEventsClient_SetEventsConfig_Call) Run(run func(ctx context.Context, realm string, cfg keycloakapi.RealmEventsConfigRepresentation)) *MockEventsClient_SetEventsConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 keycloakapi.RealmEventsConfigRepresentation
		if args[2] != nil {
			arg2 = args[2].(keycloakapi.RealmEventsConfigRepresentation)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEventsClient_SetEventsConfig_Call) Return(response *keycloakapi.Response, err error) *MockEventsClient_SetEventsConfig_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockEventsClient_SetEventsConfig_Call) RunAndReturn(run func(ctx context.Context, realm string, cfg keycloakapi.RealmEventsConfigRepresentation) (*keycloakapi.Response, error)) *MockEventsClient_SetEventsConfig_Call {
	_c.Call.Return(run)
	return _c
}
