// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/epam/edp-keycloak-operator/pkg/client/keycloakapi"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRealmClient creates a new instance of MockRealmClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRealmClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRealmClient {
	mock := &MockRealmClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRealmClient is an autogenerated mock type for the RealmClient type
type MockRealmClient struct {
	mock.Mock
}

type MockRealmClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRealmClient) EXPECT() *MockRealmClient_Expecter {
	return &MockRealmClient_Expecter{mock: &_m.Mock}
}

// CreateRealm provides a mock function for the type MockRealmClient
func (_mock *MockRealmClient) CreateRealm(ctx context.Context, realmRep keycloakapi.RealmRepresentation) (*keycloakapi.Response, error) {
	ret := _mock.Called(ctx, realmRep)

	if len(ret) == 0 {
		panic("no return value specified for CreateRealm")
	}

	var r0 *keycloakapi.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, keycloakapi.RealmRepresentation) (*keycloakapi.Response, error)); ok {
		return returnFunc(ctx, realmRep)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, keycloakapi.RealmRepresentation) *keycloakapi.Response); ok {
		r0 = returnFunc(ctx, realmRep)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*keycloakapi.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, keycloakapi.RealmRepresentation) error); ok {
		r1 = returnFunc(ctx, realmRep)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRealmClient_CreateRealm_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRealm'
type MockRealmClient_CreateRealm_Call struct {
	*mock.Call
}

// CreateRealm is a helper method to define mock.On call
//   - ctx context.Context
//   - realmRep keycloakapi.RealmRepresentation
func (_e *MockRealmClient_Expecter) CreateRealm(ctx interface{}, realmRep interface{}) *MockRealmClient_CreateRealm_Call {
	return &MockRealmClient_CreateRealm_Call{Call: _e.mock.On("CreateRealm", ctx, realmRep)}
}

func (_c *MockRealmClient_CreateRealm_Call) Run(run func(ctx context.Context, realmRep keycloakapi.RealmRepresentation)) *MockRealmClient_CreateRealm_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 keycloakapi.RealmRepresentation
		if args[1] != nil {
			arg1 = args[1].(keycloakapi.RealmRepresentation)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRealmClient_CreateRealm_Call) Return(response *keycloakapi.Response, err error) *MockRealmClient_CreateRealm_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockRealmClient_CreateRealm_Call) RunAndReturn(run func(ctx context.Context, realmRep keycloakapi.RealmRepresentation) (*keycloakapi.Response, error)) *MockRealmClient_CreateRealm_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRealm provides a mock function for the type MockRealmClient
func (_mock *MockRealmClient) DeleteRealm(ctx context.Context, realm string) (*keycloakapi.Response, error) {
	ret := _mock.Called(ctx, realm)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRealm")
	}

	var r0 *keycloakapi.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*keycloakapi.Response, error)); ok {
		return returnFunc(ctx, realm)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *keycloakapi.Response); ok {
		r0 = returnFunc(ctx, realm)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*keycloakapi.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, realm)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRealmClient_DeleteRealm_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRealm'
type MockRealmClient_DeleteRealm_Call struct {
	*mock.Call
}

// DeleteRealm is a helper method to define mock.On call
//   - ctx context.Context
//   - realm string
func (_e *MockRealmClient_Expecter) DeleteRealm(ctx interface{}, realm interface{}) *MockRealmClient_DeleteRealm_Call {
	return &MockRealmClient_DeleteRealm_Call{Call: _e.mock.On("DeleteRealm", ctx, realm)}
}

func (_c *MockRealmClient_DeleteRealm_Call) Run(run func(ctx context.Context, realm string)) *MockRealmClient_DeleteRealm_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRealmClient_DeleteRealm_Call) Return(response *keycloakapi.Response, err error) *MockRealmClient_DeleteRealm_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockRealmClient_DeleteRealm_Call) RunAndReturn(run func(ctx context.Context, realm string) (*keycloakapi.Response, error)) *MockRealmClient_DeleteRealm_Call {
	_c.Call.Return(run)
	return _c
}

// GetAuthenticationFlows provides a mock function for the type MockRealmClient
func (_mock *MockRealmClient) GetAuthenticationFlows(ctx context.Context, realm string) ([]keycloakapi.AuthenticationFlowRepresentation, *keycloakapi.Response, error) {
	ret := _mock.Called(ctx, realm)

	if len(ret) == 0 {
		panic("no return value specified for GetAuthenticationFlows")
	}

	var r0 []keycloakapi.AuthenticationFlowRepresentation
	var r1 *keycloakapi.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]keycloakapi.AuthenticationFlowRepresentation, *keycloakapi.Response, error)); ok {
		return returnFunc(ctx, realm)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []keycloakapi.AuthenticationFlowRepresentation); ok {
		r0 = returnFunc(ctx, realm)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]keycloakapi.AuthenticationFlowRepresentation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) *keycloakapi.Response); ok {
		r1 = returnFunc(ctx, realm)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*keycloakapi.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, realm)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockRealmClient_GetAuthenticationFlows_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAuthenticationFlows'
type MockRealmClient_GetAuthenticationFlows_Call struct {
	*mock.Call
}

// GetAuthenticationFlows is a helper method to define mock.On call
//   - ctx context.Context
//   - realm string
func (_e *MockRealmClient_Expecter) GetAuthenticationFlows(ctx interface{}, realm interface{}) *MockRealmClient_GetAuthenticationFlows_Call {
	return &MockRealmClient_GetAuthenticationFlows_Call{Call: _e.mock.On("GetAuthenticationFlows", ctx, realm)}
}

func (_c *MockRealmClient_GetAuthenticationFlows_Call) Run(run func(ctx context.Context, realm string)) *MockRealmClient_GetAuthenticationFlows_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRealmClient_GetAuthenticationFlows_Call) Return(vs []keycloakapi.AuthenticationFlowRepresentation, response *keycloakapi.Response, err error) *MockRealmClient_GetAuthenticationFlows_Call {
	_c.Call.Return(vs, response, err)
	return _c
}

func (_c *MockRealmClient_GetAuthenticationFlows_Call) RunAndReturn(run func(ctx context.Context, realm string) ([]keycloakapi.AuthenticationFlowRepresentation, *keycloakapi.Response, error)) *MockRealmClient_GetAuthenticationFlows_Call {
	_c.Call.Return(run)
	return _c
}

// GetRealm provides a mock function for the type MockRealmClient
func (_mock *MockRealmClient) GetRealm(ctx context.Context, realm string) (*keycloakapi.RealmRepresentation, *keycloakapi.Response, error) {
	ret := _mock.Called(ctx, realm)

	if len(ret) == 0 {
		panic("no return value specified for GetRealm")
	}

	var r0 *keycloakapi.RealmRepresentation
	var r1 *keycloakapi.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*keycloakapi.RealmRepresentation, *keycloakapi.Response, error)); ok {
		return returnFunc(ctx, realm)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *keycloakapi.RealmRepresentation); ok {
		r0 = returnFunc(ctx, realm)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*keycloakapi.RealmRepresentation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) *keycloakapi.Response); ok {
		r1 = returnFunc(ctx, realm)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*keycloakapi.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, realm)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockRealmClient_GetRealm_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRealm'
type MockRealmClient_GetRealm_Call struct {
	*mock.Call
}

// GetRealm is a helper method to define mock.On call
//   - ctx context.Context
//   - realm string
func (_e *MockRealmClient_Expecter) GetRealm(ctx interface{}, realm interface{}) *MockRealmClient_GetRealm_Call {
	return &MockRealmClient_GetRealm_Call{Call: _e.mock.On("GetRealm", ctx, realm)}
}

func (_c *MockRealmClient_GetRealm_Call) Run(run func(ctx context.Context, realm string)) *MockRealmClient_GetRealm_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRealmClient_GetRealm_Call) Return(v *keycloakapi.RealmRepresentation, response *keycloakapi.Response, err error) *MockRealmClient_GetRealm_Call {
	_c.Call.Return(v, response, err)
	return _c
}

func (_c *MockRealmClient_GetRealm_Call) RunAndReturn(run func(ctx context.Context, realm string) (*keycloakapi.RealmRepresentation, *keycloakapi.Response, error)) *MockRealmClient_GetRealm_Call {
	_c.Call.Return(run)
	return _c
}

// GetRealmKeys provides a mock function for the type MockRealmClient
func (_mock *MockRealmClient) GetRealmKeys(ctx context.Context, realm string) (*keycloakapi.KeysMetadataRepresentation, *keycloakapi.Response, error) {
	ret := _mock.Called(ctx, realm)

	if len(ret) == 0 {
		panic("no return value specified for GetRealmKeys")
	}

	var r0 *keycloakapi.KeysMetadataRepresentation
	var r1 *keycloakapi.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*keycloakapi.KeysMetadataRepresentation, *keycloakapi.Response, error)); ok {
		return returnFunc(ctx, realm)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *keycloakapi.KeysMetadataRepresentation); ok {
		r0 = returnFunc(ctx, realm)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*keycloakapi.KeysMetadataRepresentation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) *keycloakapi.Response); ok {
		r1 = returnFunc(ctx, realm)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*keycloakapi.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, realm)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockRealmClient_GetRealmKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRealmKeys'
type MockRealmClient_GetRealmKeys_Call struct {
	*mock.Call
}

// GetRealmKeys is a helper method to define mock.On call
//   - ctx context.Context
//   - realm string
func (_e *MockRealmClient_Expecter) GetRealmKeys(ctx interface{}, realm interface{}) *MockRealmClient_GetRealmKeys_Call {
	return &MockRealmClient_GetRealmKeys_Call{Call: _e.mock.On("GetRealmKeys", ctx, realm)}
}

func (_c *MockRealmClient_GetRealmKeys_Call) Run(run func(ctx context.Context, realm string)) *MockRealmClient_GetRealmKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRealmClient_GetRealmKeys_Call) Return(v *keycloakapi.KeysMetadataRepresentation, response *keycloakapi.Response, err error) *MockRealmClient_GetRealmKeys_Call {
	_c.Call.Return(v, response, err)
	return _c
}

func (_c *MockRealmClient_GetRealmKeys_Call) RunAndReturn(run func(ctx context.Context, realm string) (*keycloakapi.KeysMetadataRepresentation, *keycloakapi.Response, error)) *MockRealmClient_GetRealmKeys_Call {
	_c.Call.Return(run)
	return _c
}

// GetRealmLocalization provides a mock function for the type MockRealmClient
func (_mock *MockRealmClient) GetRealmLocalization(ctx context.Context, realm string, locale string) (map[string]string, *keycloakapi.Response, error) {
	ret := _mock.Called(ctx, realm, locale)

	if len(ret) == 0 {
		panic("no return value specified for GetRealmLocalization")
	}

	var r0 map[string]string
	var r1 *keycloakapi.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (map[string]string, *keycloakapi.Response, error)); ok {
		return returnFunc(ctx, realm, locale)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) map[string]string); ok {
		r0 = returnFunc(ctx, realm, locale)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) *keycloakapi.Response); ok {
		r1 = returnFunc(ctx, realm, locale)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*keycloakapi.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = returnFunc(ctx, realm, locale)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockRealmClient_GetRealmLocalization_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRealmLocalization'
type MockRealmClient_GetRealmLocalization_Call struct {
	*mock.Call
}

// GetRealmLocalization is a helper method to define mock.On call
//   - ctx context.Context
//   - realm string
//   - locale string
func (_e *MockRealmClient_Expecter) GetRealmLocalization(ctx interface{}, realm interface{}, locale interface{}) *MockRealmClient_GetRealmLocalization_Call {
	return &MockRealmClient_GetRealmLocalization_Call{Call: _e.mock.On("GetRealmLocalization", ctx, realm, locale)}
}

func (_c *MockRealmClient_GetRealmLocalization_Call) Run(run func(ctx context.Context, realm string, locale string)) *MockRealmClient_GetRealmLocalization_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRealmClient_GetRealmLocalization_Call) Return(stringToString map[string]string, response *keycloakapi.Response, err error) *MockRealmClient_GetRealmLocalization_Call {
	_c.Call.Return(stringToString, response, err)
	return _c
}

func (_c *MockRealmClient_GetRealmLocalization_Call) RunAndReturn(run func(ctx context.Context, realm string, locale string) (map[string]string, *keycloakapi.Response, error)) *MockRealmClient_GetRealmLocalization_Call {
	_c.Call.Return(run)
	return _c
}

// GetRealms provides a mock function for the type MockRealmClient
func (_mock *MockRealmClient) GetRealms(ctx context.Context) ([]keycloakapi.RealmRepresentation, *keycloakapi.Response, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetRealms")
	}

	var r0 []keycloakapi.RealmRepresentation
	var r1 *keycloakapi.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]keycloakapi.RealmRepresentation, *keycloakapi.Response, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []keycloakapi.RealmRepresentation); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]keycloakapi.RealmRepresentation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) *keycloakapi.Response); ok {
		r1 = returnFunc(ctx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*keycloakapi.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = returnFunc(ctx)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockRealmClient_GetRealms_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRealms'
type MockRealmClient_GetRealms_Call struct {
	*mock.Call
}

// GetRealms is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRealmClient_Expecter) GetRealms(ctx interface{}) *MockRealmClient_GetRealms_Call {
	return &MockRealmClient_GetRealms_Call{Call: _e.mock.On("GetRealms", ctx)}
}

func (_c *MockRealmClient_GetRealms_Call) Run(run func(ctx context.Context)) *MockRealmClient_GetRealms_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRealmClient_GetRealms_Call) Return(vs []keycloakapi.RealmRepresentation, response *keycloakapi.Response, err error) *MockRealmClient_GetRealms_Call {
	_c.Call.Return(vs, response, err)
	return _c
}

func (_c *MockRealmClient_GetRealms_Call) RunAndReturn(run func(ctx context.Context) ([]keycloakapi.RealmRepresentation, *keycloakapi.Response, error)) *MockRealmClient_GetRealms_Call {
	_c.Call.Return(run)
	return _c
}

// PostRealmLocalization provides a mock function for the type MockRealmClient
func (_mock *MockRealmClient) PostRealmLocalization(ctx context.Context, realm string, locale string, texts map[string]string) (*keycloakapi.Response, error) {
	ret := _mock.Called(ctx, realm, locale, texts)

	if len(ret) == 0 {
		panic("no return value specified for PostRealmLocalization")
	}

	var r0 *keycloakapi.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, map[string]string) (*keycloakapi.Response, error)); ok {
		return returnFunc(ctx, realm, locale, texts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, map[string]string) *keycloakapi.Response); ok {
		r0 = returnFunc(ctx, realm, locale, texts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*keycloakapi.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, map[string]string) error); ok {
		r1 = returnFunc(ctx, realm, locale, texts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRealmClient_PostRealmLocalization_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostRealmLocalization'
type MockRealmClient_PostRealmLocalization_Call struct {
	*mock.Call
}

// PostRealmLocalization is a helper method to define mock.On call
//   - ctx context.Context
//   - realm string
//   - locale string
//   - texts map[string]string
func (_e *MockRealmClient_Expecter) PostRealmLocalization(ctx interface{}, realm interface{}, locale interface{}, texts interface{}) *MockRealmClient_PostRealmLocalization_Call {
	return &MockRealmClient_PostRealmLocalization_Call{Call: _e.mock.On("PostRealmLocalization", ctx, realm, locale, texts)}
}

func (_c *MockRealmClient_PostRealmLocalization_Call) Run(run func(ctx context.Context, realm string, locale string, texts map[string]string)) *MockRealmClient_PostRealmLocalization_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 map[string]string
		if args[3] != nil {
			arg3 = args[3].(map[string]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRealmClient_PostRealmLocalization_Call) Return(response *keycloakapi.Response, err error) *MockRealmClient_PostRealmLocalization_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockRealmClient_PostRealmLocalization_Call) RunAndReturn(run func(ctx context.Context, realm string, locale string, texts map[string]string) (*keycloakapi.Response, error)) *MockRealmClient_PostRealmLocalization_Call {
	_c.Call.Return(run)
	return _c
}

// SetRealmBrowserFlow provides a mock function for the type MockRealmClient
func (_mock *MockRealmClient) SetRealmBrowserFlow(ctx context.Context, realm string, flowAlias string) (*keycloakapi.Response, error) {
	ret := _mock.Called(ctx, realm, flowAlias)

	if len(ret) == 0 {
		panic("no return value specified for SetRealmBrowserFlow")
	}

	var r0 *keycloakapi.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*keycloakapi.Response, error)); ok {
		return returnFunc(ctx, realm, flowAlias)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *keycloakapi.Response); ok {
		r0 = returnFunc(ctx, realm, flowAlias)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*keycloakapi.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, realm, flowAlias)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRealmClient_SetRealmBrowserFlow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetRealmBrowserFlow'
type MockRealmClient_SetRealmBrowserFlow_Call struct {
	*mock.Call
}

// SetRealmBrowserFlow is a helper method to define mock.On call
//   - ctx context.Context
//   - realm string
//   - flowAlias string
func (_e *MockRealmClient_Expecter) SetRealmBrowserFlow(ctx interface{}, realm interface{}, flowAlias interface{}) *MockRealmClient_SetRealmBrowserFlow_Call {
	return &MockRealmClient_SetRealmBrowserFlow_Call{Call: _e.mock.On("SetRealmBrowserFlow", ctx, realm, flowAlias)}
}

func (_c *MockRealmClient_SetRealmBrowserFlow_Call) Run(run func(ctx context.Context, realm string, flowAlias string)) *MockRealmClient_SetRealmBrowserFlow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRealmClient_SetRealmBrowserFlow_Call) Return(response *keycloakapi.Response, err error) *MockRealmClient_SetRealmBrowserFlow_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockRealmClient_SetRealmBrowserFlow_Call) RunAndReturn(run func(ctx context.Context, realm string, flowAlias string) (*keycloakapi.Response, error)) *MockRealmClient_SetRealmBrowserFlow_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRealm provides a mock function for the type MockRealmClient
func (_mock *MockRealmClient) UpdateRealm(ctx context.Context, realm string, realmRep keycloakapi.RealmRepresentation) (*keycloakapi.Response, error) {
	ret := _mock.Called(ctx, realm, realmRep)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRealm")
	}

	var r0 *keycloakapi.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, keycloakapi.RealmRepresentation) (*keycloakapi.Response, error)); ok {
		return returnFunc(ctx, realm, realmRep)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, keycloakapi.RealmRepresentation) *keycloakapi.Response); ok {
		r0 = returnFunc(ctx, realm, realmRep)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*keycloakapi.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, keycloakapi.RealmRepresentation) error); ok {
		r1 = returnFunc(ctx, realm, realmRep)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRealmClient_UpdateRealm_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRealm'
type MockRealmClient_UpdateRealm_Call struct {
	*mock.Call
}

// UpdateRealm is a helper method to define mock.On call
//   - ctx context.Context
//   - realm string
//   - realmRep keycloakapi.RealmRepresentation
func (_e *MockRealmClient_Expecter) UpdateRealm(ctx interface{}, realm interface{}, realmRep interface{}) *MockRealmClient_UpdateRealm_Call {
	return &MockRealmClient_UpdateRealm_Call{Call: _e.mock.On("UpdateRealm", ctx, realm, realmRep)}
}

func (_c *MockRealmClient_UpdateRealm_Call) Run(run func(ctx context.Context, realm string, realmRep keycloakapi.RealmRepresentation)) *MockRealmClient_UpdateRealm_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 keycloakapi.RealmRepresentation
		if args[2] != nil {
			arg2 = args[2].(keycloakapi.RealmRepresentation)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRealmClient_UpdateRealm_Call) Return(response *keycloakapi.Response, err error) *MockRealmClient_UpdateRealm_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockRealmClient_UpdateRealm_Call) RunAndReturn(run func(ctx context.Context, realm string, realmRep keycloakapi.RealmRepresentation) (*keycloakapi.Response, error)) *MockRealmClient_UpdateRealm_Call {
	_c.Call.Return(run)
	return _c
}
