// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/epam/edp-keycloak-operator/pkg/client/keycloakapi"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUsersClient creates a new instance of MockUsersClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUsersClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUsersClient {
	mock := &MockUsersClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUsersClient is an autogenerated mock type for the UsersClient type
type MockUsersClient struct {
	mock.Mock
}

type MockUsersClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUsersClient) EXPECT() *MockUsersClient_Expecter {
	return &MockUsersClient_Expecter{mock: &_m.Mock}
}

// AddUserClientRoles provides a mock function for the type MockUsersClient
func (_mock *MockUsersClient) AddUserClientRoles(ctx context.Context, realm string, userID string, clientID string, roles []keycloakapi.RoleRepresentation) (*keycloakapi.Response, error) {
	ret := _mock.Called(ctx, realm, userID, clientID, roles)

	if len(ret) == 0 {
		panic("no return value specified for AddUserClientRoles")
	}

	var r0 *keycloakapi.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, []keycloakapi.RoleRepresentation) (*keycloakapi.Response, error)); ok {
		return returnFunc(ctx, realm, userID, clientID, roles)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, []keycloakapi.RoleRepresentation) *keycloakapi.Response); ok {
		r0 = returnFunc(ctx, realm, userID, clientID, roles)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*keycloakapi.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, []keycloakapi.RoleRepresentation) error); ok {
		r1 = returnFunc(ctx, realm, userID, clientID, roles)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsersClient_AddUserClientRoles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddUserClientRoles'
type MockUsersClient_AddUserClientRoles_Call struct {
	*mock.Call
}

// AddUserClientRoles is a helper method to define mock.On call
//   - ctx context.Context
//   - realm string
//   - userID string
//   - clientID string
//   - roles []keycloakapi.RoleRepresentation
func (_e *MockUsersClient_Expecter) AddUserClientRoles(ctx interface{}, realm interface{}, userID interface{}, clientID interface{}, roles interface{}) *MockUsersClient_AddUserClientRoles_Call {
	return &MockUsersClient_AddUserClientRoles_Call{Call: _e.mock.On("AddUserClientRoles", ctx, realm, userID, clientID, roles)}
}

func (_c *MockUsersClient_AddUserClientRoles_Call) Run(run func(ctx context.Context, realm string, userID string, clientID string, roles []keycloakapi.RoleRepresentation)) *MockUsersClient_AddUserClientRoles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 []keycloakapi.RoleRepresentation
		if args[4] != nil {
			arg4 = args[4].([]keycloakapi.RoleRepresentation)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockUsersClient_AddUserClientRoles_Call) Return(response *keycloakapi.Response, err error) *MockUsersClient_AddUserClientRoles_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockUsersClient_AddUserClientRoles_Call) RunAndReturn(run func(ctx context.Context, realm string, userID string, clientID string, roles []keycloakapi.RoleRepresentation) (*keycloakapi.Response, error)) *MockUsersClient_AddUserClientRoles_Call {
	_c.Call.Return(run)
	return _c
}

// AddUserRealmRoles provides a mock function for the type MockUsersClient
func (_mock *MockUsersClient) AddUserRealmRoles(ctx context.Context, realm string, userID string, roles []keycloakapi.RoleRepresentation) (*keycloakapi.Response, error) {
	ret := _mock.Called(ctx, realm, userID, roles)

	if len(ret) == 0 {
		panic("no return value specified for AddUserRealmRoles")
	}

	var r0 *keycloakapi.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []keycloakapi.RoleRepresentation) (*keycloakapi.Response, error)); ok {
		return returnFunc(ctx, realm, userID, roles)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []keycloakapi.RoleRepresentation) *keycloakapi.Response); ok {
		r0 = returnFunc(ctx, realm, userID, roles)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*keycloakapi.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, []keycloakapi.RoleRepresentation) error); ok {
		r1 = returnFunc(ctx, realm, userID, roles)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsersClient_AddUserRealmRoles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddUserRealmRoles'
type MockUsersClient_AddUserRealmRoles_Call struct {
	*mock.Call
}

// AddUserRealmRoles is a helper method to define mock.On call
//   - ctx context.Context
//   - realm string
//   - userID string
//   - roles []keycloakapi.RoleRepresentation
func (_e *MockUsersClient_Expecter) AddUserRealmRoles(ctx interface{}, realm interface{}, userID interface{}, roles interface{}) *MockUsersClient_AddUserRealmRoles_Call {
	return &MockUsersClient_AddUserRealmRoles_Call{Call: _e.mock.On("AddUserRealmRoles", ctx, realm, userID, roles)}
}

func (_c *MockUsersClient_AddUserRealmRoles_Call) Run(run func(ctx context.Context, realm string, userID string, roles []keycloakapi.RoleRepresentation)) *MockUsersClient_AddUserRealmRoles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []keycloakapi.RoleRepresentation
		if args[3] != nil {
			arg3 = args[3].([]keycloakapi.RoleRepresentation)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockUsersClient_AddUserRealmRoles_Call) Return(response *keycloakapi.Response, err error) *MockUsersClient_AddUserRealmRoles_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockUsersClient_AddUserRealmRoles_Call) RunAndReturn(run func(ctx context.Context, realm string, userID string, roles []keycloakapi.RoleRepresentation) (*keycloakapi.Response, error)) *MockUsersClient_AddUserRealmRoles_Call {
	_c.Call.Return(run)
	return _c
}

// AddUserToGroup provides a mock function for the type MockUsersClient
func (_mock *MockUsersClient) AddUserToGroup(ctx context.Context, realm string, userID string, groupID string) (*keycloakapi.Response, error) {
	ret := _mock.Called(ctx, realm, userID, groupID)

	if len(ret) == 0 {
		panic("no return value specified for AddUserToGroup")
	}

	var r0 *keycloakapi.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (*keycloakapi.Response, error)); ok {
		return returnFunc(ctx, realm, userID, groupID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) *keycloakapi.Response); ok {
		r0 = returnFunc(ctx, realm, userID, groupID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*keycloakapi.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, realm, userID, groupID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsersClient_AddUserToGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddUserToGroup'
type MockUsersClient_AddUserToGroup_Call struct {
	*mock.Call
}

// AddUserToGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - realm string
//   - userID string
//   - groupID string
func (_e *MockUsersClient_Expecter) AddUserToGroup(ctx interface{}, realm interface{}, userID interface{}, groupID interface{}) *MockUsersClient_AddUserToGroup_Call {
	return &MockUsersClient_AddUserToGroup_Call{Call: _e.mock.On("AddUserToGroup", ctx, realm, userID, groupID)}
}

func (_c *MockUsersClient_AddUserToGroup_Call) Run(run func(ctx context.Context, realm string, userID string, groupID string)) *MockUsersClient_AddUserToGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockUsersClient_AddUserToGroup_Call) Return(response *keycloakapi.Response, err error) *MockUsersClient_AddUserToGroup_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockUsersClient_AddUserToGroup_Call) RunAndReturn(run func(ctx context.Context, realm string, userID string, groupID string) (*keycloakapi.Response, error)) *MockUsersClient_AddUserToGroup_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function for the type MockUsersClient
func (_mock *MockUsersClient) CreateUser(ctx context.Context, realm string, user keycloakapi.UserRepresentation) (*keycloakapi.Response, error) {
	ret := _mock.Called(ctx, realm, user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *keycloakapi.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, keycloakapi.UserRepresentation) (*keycloakapi.Response, error)); ok {
		return returnFunc(ctx, realm, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, keycloakapi.UserRepresentation) *keycloakapi.Response); ok {
		r0 = returnFunc(ctx, realm, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*keycloakapi.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, keycloakapi.UserRepresentation) error); ok {
		r1 = returnFunc(ctx, realm, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsersClient_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockUsersClient_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - realm string
//   - user keycloakapi.UserRepresentation
func (_e *MockUsersClient_Expecter) CreateUser(ctx interface{}, realm interface{}, user interface{}) *MockUsersClient_CreateUser_Call {
	return &MockUsersClient_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, realm, user)}
}

func (_c *MockUsersClient_CreateUser_Call) Run(run func(ctx context.Context, realm string, user keycloakapi.UserRepresentation)) *MockUsersClient_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 keycloakapi.UserRepresentation
		if args[2] != nil {
			arg2 = args[2].(keycloakapi.UserRepresentation)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUsersClient_CreateUser_Call) Return(response *keycloakapi.Response, err error) *MockUsersClient_CreateUser_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockUsersClient_CreateUser_Call) RunAndReturn(run func(ctx context.Context, realm string, user keycloakapi.UserRepresentation) (*keycloakapi.Response, error)) *MockUsersClient_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUserFederatedIdentity provides a mock function for the type MockUsersClient
func (_mock *MockUsersClient) CreateUserFederatedIdentity(ctx context.Context, realm string, userID string, provider string, identity keycloakapi.FederatedIdentityRepresentation) (*keycloakapi.Response, error) {
	ret := _mock.Called(ctx, realm, userID, provider, identity)

	if len(ret) == 0 {
		panic("no return value specified for CreateUserFederatedIdentity")
	}

	var r0 *keycloakapi.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, keycloakapi.FederatedIdentityRepresentation) (*keycloakapi.Response, error)); ok {
		return returnFunc(ctx, realm, userID, provider, identity)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, keycloakapi.FederatedIdentityRepresentation) *keycloakapi.Response); ok {
		r0 = returnFunc(ctx, realm, userID, provider, identity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*keycloakapi.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, keycloakapi.FederatedIdentityRepresentation) error); ok {
		r1 = returnFunc(ctx, realm, userID, provider, identity)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsersClient_CreateUserFederatedIdentity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUserFederatedIdentity'
type MockUsersClient_CreateUserFederatedIdentity_Call struct {
	*mock.Call
}

// CreateUserFederatedIdentity is a helper method to define mock.On call
//   - ctx context.Context
//   - realm string
//   - userID string
//   - provider string
//   - identity keycloakapi.FederatedIdentityRepresentation
func (_e *MockUsersClient_Expecter) CreateUserFederatedIdentity(ctx interface{}, realm interface{}, userID interface{}, provider interface{}, identity interface{}) *MockUsersClient_CreateUserFederatedIdentity_Call {
	return &MockUsersClient_CreateUserFederatedIdentity_Call{Call: _e.mock.On("CreateUserFederatedIdentity", ctx, realm, userID, provider, identity)}
}

func (_c *MockUsersClient_CreateUserFederatedIdentity_Call) Run(run func(ctx context.Context, realm string, userID string, provider string, identity keycloakapi.FederatedIdentityRepresentation)) *MockUsersClient_CreateUserFederatedIdentity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 keycloakapi.FederatedIdentityRepresentation
		if args[4] != nil {
			arg4 = args[4].(keycloakapi.FederatedIdentityRepresentation)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockUsersClient_CreateUserFederatedIdentity_Call) Return(response *keycloakapi.Response, err error) *MockUsersClient_CreateUserFederatedIdentity_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockUsersClient_CreateUserFederatedIdentity_Call) RunAndReturn(run func(ctx context.Context, realm string, userID string, provider string, identity keycloakapi.FederatedIdentityRepresentation) (*keycloakapi.Response, error)) *MockUsersClient_CreateUserFederatedIdentity_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUser provides a mock function for the type MockUsersClient
func (_mock *MockUsersClient) DeleteUser(ctx context.Context, realm string, userID string) (*keycloakapi.Response, error) {
	ret := _mock.Called(ctx, realm, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 *keycloakapi.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*keycloakapi.Response, error)); ok {
		return returnFunc(ctx, realm, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *keycloakapi.Response); ok {
		r0 = returnFunc(ctx, realm, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*keycloakapi.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, realm, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsersClient_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type MockUsersClient_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - ctx context.Context
//   - realm string
//   - userID string
func (_e *MockUsersClient_Expecter) DeleteUser(ctx interface{}, realm interface{}, userID interface{}) *MockUsersClient_DeleteUser_Call {
	return &MockUsersClient_DeleteUser_Call{Call: _e.mock.On("DeleteUser", ctx, realm, userID)}
}

func (_c *MockUsersClient_DeleteUser_Call) Run(run func(ctx context.Context, realm string, userID string)) *MockUsersClient_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUsersClient_DeleteUser_Call) Return(response *keycloakapi.Response, err error) *MockUsersClient_DeleteUser_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockUsersClient_DeleteUser_Call) RunAndReturn(run func(ctx context.Context, realm string, userID string) (*keycloakapi.Response, error)) *MockUsersClient_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUserClientRoles provides a mock function for the type MockUsersClient
func (_mock *MockUsersClient) DeleteUserClientRoles(ctx context.Context, realm string, userID string, clientID string, roles []keycloakapi.RoleRepresentation) (*keycloakapi.Response, error) {
	ret := _mock.Called(ctx, realm, userID, clientID, roles)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUserClientRoles")
	}

	var r0 *keycloakapi.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, []keycloakapi.RoleRepresentation) (*keycloakapi.Response, error)); ok {
		return returnFunc(ctx, realm, userID, clientID, roles)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, []keycloakapi.RoleRepresentation) *keycloakapi.Response); ok {
		r0 = returnFunc(ctx, realm, userID, clientID, roles)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*keycloakapi.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, []keycloakapi.RoleRepresentation) error); ok {
		r1 = returnFunc(ctx, realm, userID, clientID, roles)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsersClient_DeleteUserClientRoles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUserClientRoles'
type MockUsersClient_DeleteUserClientRoles_Call struct {
	*mock.Call
}

// DeleteUserClientRoles is a helper method to define mock.On call
//   - ctx context.Context
//   - realm string
//   - userID string
//   - clientID string
//   - roles []keycloakapi.RoleRepresentation
func (_e *MockUsersClient_Expecter) DeleteUserClientRoles(ctx interface{}, realm interface{}, userID interface{}, clientID interface{}, roles interface{}) *MockUsersClient_DeleteUserClientRoles_Call {
	return &MockUsersClient_DeleteUserClientRoles_Call{Call: _e.mock.On("DeleteUserClientRoles", ctx, realm, userID, clientID, roles)}
}

func (_c *MockUsersClient_DeleteUserClientRoles_Call) Run(run func(ctx context.Context, realm string, userID string, clientID string, roles []keycloakapi.RoleRepresentation)) *MockUsersClient_DeleteUserClientRoles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 []keycloakapi.RoleRepresentation
		if args[4] != nil {
			arg4 = args[4].([]keycloakapi.RoleRepresentation)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockUsersClient_DeleteUserClientRoles_Call) Return(response *keycloakapi.Response, err error) *MockUsersClient_DeleteUserClientRoles_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockUsersClient_DeleteUserClientRoles_Call) RunAndReturn(run func(ctx context.Context, realm string, userID string, clientID string, roles []keycloakapi.RoleRepresentation) (*keycloakapi.Response, error)) *MockUsersClient_DeleteUserClientRoles_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUserCredential provides a mock function for the type MockUsersClient
func (_mock *MockUsersClient) DeleteUserCredential(ctx context.Context, realm string, userID string, credentialID string) (*keycloakapi.Response, error) {
	ret := _mock.Called(ctx, realm, userID, credentialID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUserCredential")
	}

	var r0 *keycloakapi.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (*keycloakapi.Response, error)); ok {
		return returnFunc(ctx, realm, userID, credentialID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) *keycloakapi.Response); ok {
		r0 = returnFunc(ctx, realm, userID, credentialID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*keycloakapi.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, realm, userID, credentialID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsersClient_DeleteUserCredential_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUserCredential'
type MockUsersClient_DeleteUserCredential_Call struct {
	*mock.Call
}

// DeleteUserCredential is a helper method to define mock.On call
//   - ctx context.Context
//   - realm string
//   - userID string
//   - credentialID string
func (_e *MockUsersClient_Expecter) DeleteUserCredential(ctx interface{}, realm interface{}, userID interface{}, credentialID interface{}) *MockUsersClient_DeleteUserCredential_Call {
	return &MockUsersClient_DeleteUserCredential_Call{Call: _e.mock.On("DeleteUserCredential", ctx, realm, userID, credentialID)}
}

func (_c *MockUsersClient_DeleteUserCredential_Call) Run(run func(ctx context.Context, realm string, userID string, credentialID string)) *MockUsersClient_DeleteUserCredential_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockUsersClient_DeleteUserCredential_Call) Return(response *keycloakapi.Response, err error) *MockUsersClient_DeleteUserCredential_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockUsersClient_DeleteUserCredential_Call) RunAndReturn(run func(ctx context.Context, realm string, userID string, credentialID string) (*keycloakapi.Response, error)) *MockUsersClient_DeleteUserCredential_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUserFederatedIdentity provides a mock function for the type MockUsersClient
func (_mock *MockUsersClient) DeleteUserFederatedIdentity(ctx context.Context, realm string, userID string, provider string) (*keycloakapi.Response, error) {
	ret := _mock.Called(ctx, realm, userID, provider)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUserFederatedIdentity")
	}

	var r0 *keycloakapi.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (*keycloakapi.Response, error)); ok {
		return returnFunc(ctx, realm, userID, provider)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) *keycloakapi.Response); ok {
		r0 = returnFunc(ctx, realm, userID, provider)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*keycloakapi.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, realm, userID, provider)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsersClient_DeleteUserFederatedIdentity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUserFederatedIdentity'
type MockUsersClient_DeleteUserFederatedIdentity_Call struct {
	*mock.Call
}

// DeleteUserFederatedIdentity is a helper method to define mock.On call
//   - ctx context.Context
//   - realm string
//   - userID string
//   - provider string
func (_e *MockUsersClient_Expecter) DeleteUserFederatedIdentity(ctx interface{}, realm interface{}, userID interface{}, provider interface{}) *MockUsersClient_DeleteUserFederatedIdentity_Call {
	return &MockUsersClient_DeleteUserFederatedIdentity_Call{Call: _e.mock.On("DeleteUserFederatedIdentity", ctx, realm, userID, provider)}
}

func (_c *MockUsersClient_DeleteUserFederatedIdentity_Call) Run(run func(ctx context.Context, realm string, userID string, provider string)) *MockUsersClient_DeleteUserFederatedIdentity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockUsersClient_DeleteUserFederatedIdentity_Call) Return(response *keycloakapi.Response, err error) *MockUsersClient_DeleteUserFederatedIdentity_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockUsersClient_DeleteUserFederatedIdentity_Call) RunAndReturn(run func(ctx context.Context, realm string, userID string, provider string) (*keycloakapi.Response, error)) *MockUsersClient_DeleteUserFederatedIdentity_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUserRealmRoles provides a mock function for the type MockUsersClient
func (_mock *MockUsersClient) DeleteUserRealmRoles(ctx context.Context, realm string, userID string, roles []keycloakapi.RoleRepresentation) (*keycloakapi.Response, error) {
	ret := _mock.Called(ctx, realm, userID, roles)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUserRealmRoles")
	}

	var r0 *keycloakapi.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []keycloakapi.RoleRepresentation) (*keycloakapi.Response, error)); ok {
		return returnFunc(ctx, realm, userID, roles)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []keycloakapi.RoleRepresentation) *keycloakapi.Response); ok {
		r0 = returnFunc(ctx, realm, userID, roles)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*keycloakapi.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, []keycloakapi.RoleRepresentation) error); ok {
		r1 = returnFunc(ctx, realm, userID, roles)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsersClient_DeleteUserRealmRoles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUserRealmRoles'
type MockUsersClient_DeleteUserRealmRoles_Call struct {
	*mock.Call
}

// DeleteUserRealmRoles is a helper method to define mock.On call
//   - ctx context.Context
//   - realm string
//   - userID string
//   - roles []keycloakapi.RoleRepresentation
func (_e *MockUsersClient_Expecter) DeleteUserRealmRoles(ctx interface{}, realm interface{}, userID interface{}, roles interface{}) *MockUsersClient_DeleteUserRealmRoles_Call {
	return &MockUsersClient_DeleteUserRealmRoles_Call{Call: _e.mock.On("DeleteUserRealmRoles", ctx, realm, userID, roles)}
}

func (_c *MockUsersClient_DeleteUserRealmRoles_Call) Run(run func(ctx context.Context, realm string, userID string, roles []keycloakapi.RoleRepresentation)) *MockUsersClient_DeleteUserRealmRoles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []keycloakapi.RoleRepresentation
		if args[3] != nil {
			arg3 = args[3].([]keycloakapi.RoleRepresentation)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockUsersClient_DeleteUserRealmRoles_Call) Return(response *keycloakapi.Response, err error) *MockUsersClient_DeleteUserRealmRoles_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockUsersClient_DeleteUserRealmRoles_Call) RunAndReturn(run func(ctx context.Context, realm string, userID string, roles []keycloakapi.RoleRepresentation) (*keycloakapi.Response, error)) *MockUsersClient_DeleteUserRealmRoles_Call {
	_c.Call.Return(run)
	return _c
}

// ExecuteActionsEmail provides a mock function for the type MockUsersClient
func (_mock *MockUsersClient) ExecuteActionsEmail(ctx context.Context, realm string, userID string, actions []string) (*keycloakapi.Response, error) {
	ret := _mock.Called(ctx, realm, userID, actions)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteActionsEmail")
	}

	var r0 *keycloakapi.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []string) (*keycloakapi.Response, error)); ok {
		return returnFunc(ctx, realm, userID, actions)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []string) *keycloakapi.Response); ok {
		r0 = returnFunc(ctx, realm, userID, actions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*keycloakapi.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, []string) error); ok {
		r1 = returnFunc(ctx, realm, userID, actions)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsersClient_ExecuteActionsEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecuteActionsEmail'
type MockUsersClient_ExecuteActionsEmail_Call struct {
	*mock.Call
}

// ExecuteActionsEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - realm string
//   - userID string
//   - actions []string
func (_e *MockUsersClient_Expecter) ExecuteActionsEmail(ctx interface{}, realm interface{}, userID interface{}, actions interface{}) *MockUsersClient_ExecuteActionsEmail_Call {
	return &MockUsersClient_ExecuteActionsEmail_Call{Call: _e.mock.On("ExecuteActionsEmail", ctx, realm, userID, actions)}
}

func (_c *MockUsersClient_ExecuteActionsEmail_Call) Run(run func(ctx context.Context, realm string, userID string, actions []string)) *MockUsersClient_ExecuteActionsEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []string
		if args[3] != nil {
			arg3 = args[3].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockUsersClient_ExecuteActionsEmail_Call) Return(response *keycloakapi.Response, err error) *MockUsersClient_ExecuteActionsEmail_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockUsersClient_ExecuteActionsEmail_Call) RunAndReturn(run func(ctx context.Context, realm string, userID string, actions []string) (*keycloakapi.Response, error)) *MockUsersClient_ExecuteActionsEmail_Call {
	_c.Call.Return(run)
	return _c
}

// FindUserByUsername provides a mock function for the type MockUsersClient
func (_mock *MockUsersClient) FindUserByUsername(ctx context.Context, realm string, username string) (*keycloakapi.UserRepresentation, *keycloakapi.Response, error) {
	ret := _mock.Called(ctx, realm, username)

	if len(ret) == 0 {
		panic("no return value specified for FindUserByUsername")
	}

	var r0 *keycloakapi.UserRepresentation
	var r1 *keycloakapi.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*keycloakapi.UserRepresentation, *keycloakapi.Response, error)); ok {
		return returnFunc(ctx, realm, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *keycloakapi.UserRepresentation); ok {
		r0 = returnFunc(ctx, realm, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*keycloakapi.UserRepresentation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) *keycloakapi.Response); ok {
		r1 = returnFunc(ctx, realm, username)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*keycloakapi.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = returnFunc(ctx, realm, username)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockUsersClient_FindUserByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUserByUsername'
type MockUsersClient_FindUserByUsername_Call struct {
	*mock.Call
}

// FindUserByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - realm string
//   - username string
func (_e *MockUsersClient_Expecter) FindUserByUsername(ctx interface{}, realm interface{}, username interface{}) *MockUsersClient_FindUserByUsername_Call {
	return &MockUsersClient_FindUserByUsername_Call{Call: _e.mock.On("FindUserByUsername", ctx, realm, username)}
}

func (_c *MockUsersClient_FindUserByUsername_Call) Run(run func(ctx context.Context, realm string, username string)) *MockUsersClient_FindUserByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUsersClient_FindUserByUsername_Call) Return(v *keycloakapi.UserRepresentation, response *keycloakapi.Response, err error) *MockUsersClient_FindUserByUsername_Call {
	_c.Call.Return(v, response, err)
	return _c
}

func (_c *MockUsersClient_FindUserByUsername_Call) RunAndReturn(run func(ctx context.Context, realm string, username string) (*keycloakapi.UserRepresentation, *keycloakapi.Response, error)) *MockUsersClient_FindUserByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// GetUser provides a mock function for the type MockUsersClient
func (_mock *MockUsersClient) GetUser(ctx context.Context, realm string, userID string) (*keycloakapi.UserRepresentation, *keycloakapi.Response, error) {
	ret := _mock.Called(ctx, realm, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 *keycloakapi.UserRepresentation
	var r1 *keycloakapi.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*keycloakapi.UserRepresentation, *keycloakapi.Response, error)); ok {
		return returnFunc(ctx, realm, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *keycloakapi.UserRepresentation); ok {
		r0 = returnFunc(ctx, realm, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*keycloakapi.UserRepresentation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) *keycloakapi.Response); ok {
		r1 = returnFunc(ctx, realm, userID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*keycloakapi.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = returnFunc(ctx, realm, userID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockUsersClient_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type MockUsersClient_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx context.Context
//   - realm string
//   - userID string
func (_e *MockUsersClient_Expecter) GetUser(ctx interface{}, realm interface{}, userID interface{}) *MockUsersClient_GetUser_Call {
	return &MockUsersClient_GetUser_Call{Call: _e.mock.On("GetUser", ctx, realm, userID)}
}

func (_c *MockUsersClient_GetUser_Call) Run(run func(ctx context.Context, realm string, userID string)) *MockUsersClient_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUsersClient_GetUser_Call) Return(v *keycloakapi.UserRepresentation, response *keycloakapi.Response, err error) *MockUsersClient_GetUser_Call {
	_c.Call.Return(v, response, err)
	return _c
}

func (_c *MockUsersClient_GetUser_Call) RunAndReturn(run func(ctx context.Context, realm string, userID string) (*keycloakapi.UserRepresentation, *keycloakapi.Response, error)) *MockUsersClient_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserClientRoleMappings provides a mock function for the type MockUsersClient
func (_mock *MockUsersClient) GetUserClientRoleMappings(ctx context.Context, realm string, userID string, clientID string) ([]keycloakapi.RoleRepresentation, *keycloakapi.Response, error) {
	ret := _mock.Called(ctx, realm, userID, clientID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserClientRoleMappings")
	}

	var r0 []keycloakapi.RoleRepresentation
	var r1 *keycloakapi.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) ([]keycloakapi.RoleRepresentation, *keycloakapi.Response, error)); ok {
		return returnFunc(ctx, realm, userID, clientID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) []keycloakapi.RoleRepresentation); ok {
		r0 = returnFunc(ctx, realm, userID, clientID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]keycloakapi.RoleRepresentation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) *keycloakapi.Response); ok {
		r1 = returnFunc(ctx, realm, userID, clientID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*keycloakapi.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string, string) error); ok {
		r2 = returnFunc(ctx, realm, userID, clientID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockUsersClient_GetUserClientRoleMappings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserClientRoleMappings'
type MockUsersClient_GetUserClientRoleMappings_Call struct {
	*mock.Call
}

// GetUserClientRoleMappings is a helper method to define mock.On call
//   - ctx context.Context
//   - realm string
//   - userID string
//   - clientID string
func (_e *MockUsersClient_Expecter) GetUserClientRoleMappings(ctx interface{}, realm interface{}, userID interface{}, clientID interface{}) *MockUsersClient_GetUserClientRoleMappings_Call {
	return &MockUsersClient_GetUserClientRoleMappings_Call{Call: _e.mock.On("GetUserClientRoleMappings", ctx, realm, userID, clientID)}
}

func (_c *MockUsersClient_GetUserClientRoleMappings_Call) Run(run func(ctx context.Context, realm string, userID string, clientID string)) *MockUsersClient_GetUserClientRoleMappings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockUsersClient_GetUserClientRoleMappings_Call) Return(vs []keycloakapi.RoleRepresentation, response *keycloakapi.Response, err error) *MockUsersClient_GetUserClientRoleMappings_Call {
	_c.Call.Return(vs, response, err)
	return _c
}

func (_c *MockUsersClient_GetUserClientRoleMappings_Call) RunAndReturn(run func(ctx context.Context, realm string, userID string, clientID string) ([]keycloakapi.RoleRepresentation, *keycloakapi.Response, error)) *MockUsersClient_GetUserClientRoleMappings_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserCredentials provides a mock function for the type MockUsersClient
func (_mock *MockUsersClient) GetUserCredentials(ctx context.Context, realm string, userID string) ([]keycloakapi.CredentialRepresentation, *keycloakapi.Response, error) {
	ret := _mock.Called(ctx, realm, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserCredentials")
	}

	var r0 []keycloakapi.CredentialRepresentation
	var r1 *keycloakapi.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]keycloakapi.CredentialRepresentation, *keycloakapi.Response, error)); ok {
		return returnFunc(ctx, realm, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []keycloakapi.CredentialRepresentation); ok {
		r0 = returnFunc(ctx, realm, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]keycloakapi.CredentialRepresentation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) *keycloakapi.Response); ok {
		r1 = returnFunc(ctx, realm, userID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*keycloakapi.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = returnFunc(ctx, realm, userID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockUsersClient_GetUserCredentials_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserCredentials'
type MockUsersClient_GetUserCredentials_Call struct {
	*mock.Call
}

// GetUserCredentials is a helper method to define mock.On call
//   - ctx context.Context
//   - realm string
//   - userID string
func (_e *MockUsersClient_Expecter) GetUserCredentials(ctx interface{}, realm interface{}, userID interface{}) *MockUsersClient_GetUserCredentials_Call {
	return &MockUsersClient_GetUserCredentials_Call{Call: _e.mock.On("GetUserCredentials", ctx, realm, userID)}
}

func (_c *MockUsersClient_GetUserCredentials_Call) Run(run func(ctx context.Context, realm string, userID string)) *MockUsersClient_GetUserCredentials_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUsersClient_GetUserCredentials_Call) Return(vs []keycloakapi.CredentialRepresentation, response *keycloakapi.Response, err error) *MockUsersClient_GetUserCredentials_Call {
	_c.Call.Return(vs, response, err)
	return _c
}

func (_c *MockUsersClient_GetUserCredentials_Call) RunAndReturn(run func(ctx context.Context, realm string, userID string) ([]keycloakapi.CredentialRepresentation, *keycloakapi.Response, error)) *MockUsersClient_GetUserCredentials_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserFederatedIdentities provides a mock function for the type MockUsersClient
func (_mock *MockUsersClient) GetUserFederatedIdentities(ctx context.Context, realm string, userID string) ([]keycloakapi.FederatedIdentityRepresentation, *keycloakapi.Response, error) {
	ret := _mock.Called(ctx, realm, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserFederatedIdentities")
	}

	var r0 []keycloakapi.FederatedIdentityRepresentation
	var r1 *keycloakapi.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]keycloakapi.FederatedIdentityRepresentation, *keycloakapi.Response, error)); ok {
		return returnFunc(ctx, realm, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []keycloakapi.FederatedIdentityRepresentation); ok {
		r0 = returnFunc(ctx, realm, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]keycloakapi.FederatedIdentityRepresentation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) *keycloakapi.Response); ok {
		r1 = returnFunc(ctx, realm, userID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*keycloakapi.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = returnFunc(ctx, realm, userID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockUsersClient_GetUserFederatedIdentities_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserFederatedIdentities'
type MockUsersClient_GetUserFederatedIdentities_Call struct {
	*mock.Call
}

// GetUserFederatedIdentities is a helper method to define mock.On call
//   - ctx context.Context
//   - realm string
//   - userID string
func (_e *MockUsersClient_Expecter) GetUserFederatedIdentities(ctx interface{}, realm interface{}, userID interface{}) *MockUsersClient_GetUserFederatedIdentities_Call {
	return &MockUsersClient_GetUserFederatedIdentities_Call{Call: _e.mock.On("GetUserFederatedIdentities", ctx, realm, userID)}
}

func (_c *MockUsersClient_GetUserFederatedIdentities_Call) Run(run func(ctx context.Context, realm string, userID string)) *MockUsersClient_GetUserFederatedIdentities_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUsersClient_GetUserFederatedIdentities_Call) Return(vs []keycloakapi.FederatedIdentityRepresentation, response *keycloakapi.Response, err error) *MockUsersClient_GetUserFederatedIdentities_Call {
	_c.Call.Return(vs, response, err)
	return _c
}

func (_c *MockUsersClient_GetUserFederatedIdentities_Call) RunAndReturn(run func(ctx context.Context, realm string, userID string) ([]keycloakapi.FederatedIdentityRepresentation, *keycloakapi.Response, error)) *MockUsersClient_GetUserFederatedIdentities_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserGroups provides a mock function for the type MockUsersClient
func (_mock *MockUsersClient) GetUserGroups(ctx context.Context, realm string, userID string) ([]keycloakapi.GroupRepresentation, *keycloakapi.Response, error) {
	ret := _mock.Called(ctx, realm, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserGroups")
	}

	var r0 []keycloakapi.GroupRepresentation
	var r1 *keycloakapi.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]keycloakapi.GroupRepresentation, *keycloakapi.Response, error)); ok {
		return returnFunc(ctx, realm, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []keycloakapi.GroupRepresentation); ok {
		r0 = returnFunc(ctx, realm, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]keycloakapi.GroupRepresentation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) *keycloakapi.Response); ok {
		r1 = returnFunc(ctx, realm, userID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*keycloakapi.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = returnFunc(ctx, realm, userID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockUsersClient_GetUserGroups_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserGroups'
type MockUsersClient_GetUserGroups_Call struct {
	*mock.Call
}

// GetUserGroups is a helper method to define mock.On call
//   - ctx context.Context
//   - realm string
//   - userID string
func (_e *MockUsersClient_Expecter) GetUserGroups(ctx interface{}, realm interface{}, userID interface{}) *MockUsersClient_GetUserGroups_Call {
	return &MockUsersClient_GetUserGroups_Call{Call: _e.mock.On("GetUserGroups", ctx, realm, userID)}
}

func (_c *MockUsersClient_GetUserGroups_Call) Run(run func(ctx context.Context, realm string, userID string)) *MockUsersClient_GetUserGroups_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUsersClient_GetUserGroups_Call) Return(vs []keycloakapi.GroupRepresentation, response *keycloakapi.Response, err error) *MockUsersClient_GetUserGroups_Call {
	_c.Call.Return(vs, response, err)
	return _c
}

func (_c *MockUsersClient_GetUserGroups_Call) RunAndReturn(run func(ctx context.Context, realm string, userID string) ([]keycloakapi.GroupRepresentation, *keycloakapi.Response, error)) *MockUsersClient_GetUserGroups_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserRealmRoleMappings provides a mock function for the type MockUsersClient
func (_mock *MockUsersClient) GetUserRealmRoleMappings(ctx context.Context, realm string, userID string) ([]keycloakapi.RoleRepresentation, *keycloakapi.Response, error) {
	ret := _mock.Called(ctx, realm, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserRealmRoleMappings")
	}

	var r0 []keycloakapi.RoleRepresentation
	var r1 *keycloakapi.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]keycloakapi.RoleRepresentation, *keycloakapi.Response, error)); ok {
		return returnFunc(ctx, realm, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []keycloakapi.RoleRepresentation); ok {
		r0 = returnFunc(ctx, realm, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]keycloakapi.RoleRepresentation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) *keycloakapi.Response); ok {
		r1 = returnFunc(ctx, realm, userID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*keycloakapi.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = returnFunc(ctx, realm, userID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockUsersClient_GetUserRealmRoleMappings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserRealmRoleMappings'
type MockUsersClient_GetUserRealmRoleMappings_Call struct {
	*mock.Call
}

// GetUserRealmRoleMappings is a helper method to define mock.On call
//   - ctx context.Context
//   - realm string
//   - userID string
func (_e *MockUsersClient_Expecter) GetUserRealmRoleMappings(ctx interface{}, realm interface{}, userID interface{}) *MockUsersClient_GetUserRealmRoleMappings_Call {
	return &MockUsersClient_GetUserRealmRoleMappings_Call{Call: _e.mock.On("GetUserRealmRoleMappings", ctx, realm, userID)}
}

func (_c *MockUsersClient_GetUserRealmRoleMappings_Call) Run(run func(ctx context.Context, realm string, userID string)) *MockUsersClient_GetUserRealmRoleMappings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUsersClient_GetUserRealmRoleMappings_Call) Return(vs []keycloakapi.RoleRepresentation, response *keycloakapi.Response, err error) *MockUsersClient_GetUserRealmRoleMappings_Call {
	_c.Call.Return(vs, response, err)
	return _c
}

func (_c *MockUsersClient_GetUserRealmRoleMappings_Call) RunAndReturn(run func(ctx context.Context, realm string, userID string) ([]keycloakapi.RoleRepresentation, *keycloakapi.Response, error)) *MockUsersClient_GetUserRealmRoleMappings_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserSessions provides a mock function for the type MockUsersClient
func (_mock *MockUsersClient) GetUserSessions(ctx context.Context, realm string, userID string) ([]keycloakapi.UserSessionRepresentation, *keycloakapi.Response, error) {
	ret := _mock.Called(ctx, realm, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserSessions")
	}

	var r0 []keycloakapi.UserSessionRepresentation
	var r1 *keycloakapi.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]keycloakapi.UserSessionRepresentation, *keycloakapi.Response, error)); ok {
		return returnFunc(ctx, realm, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []keycloakapi.UserSessionRepresentation); ok {
		r0 = returnFunc(ctx, realm, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]keycloakapi.UserSessionRepresentation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) *keycloakapi.Response); ok {
		r1 = returnFunc(ctx, realm, userID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*keycloakapi.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = returnFunc(ctx, realm, userID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockUsersClient_GetUserSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserSessions'
type MockUsersClient_GetUserSessions_Call struct {
	*mock.Call
}

// GetUserSessions is a helper method to define mock.On call
//   - ctx context.Context
//   - realm string
//   - userID string
func (_e *MockUsersClient_Expecter) GetUserSessions(ctx interface{}, realm interface{}, userID interface{}) *MockUsersClient_GetUserSessions_Call {
	return &MockUsersClient_GetUserSessions_Call{Call: _e.mock.On("GetUserSessions", ctx, realm, userID)}
}

func (_c *MockUsersClient_GetUserSessions_Call) Run(run func(ctx context.Context, realm string, userID string)) *MockUsersClient_GetUserSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUsersClient_GetUserSessions_Call) Return(vs []keycloakapi.UserSessionRepresentation, response *keycloakapi.Response, err error) *MockUsersClient_GetUserSessions_Call {
	_c.Call.Return(vs, response, err)
	return _c
}

func (_c *MockUsersClient_GetUserSessions_Call) RunAndReturn(run func(ctx context.Context, realm string, userID string) ([]keycloakapi.UserSessionRepresentation, *keycloakapi.Response, error)) *MockUsersClient_GetUserSessions_Call {
	_c.Call.Return(run)
	return _c
}

// GetUsers provides a mock function for the type MockUsersClient
func (_mock *MockUsersClient) GetUsers(ctx context.Context, realm string, params *keycloakapi.GetUsersParams) ([]keycloakapi.UserRepresentation, *keycloakapi.Response, error) {
	ret := _mock.Called(ctx, realm, params)

	if len(ret) == 0 {
		panic("no return value specified for GetUsers")
	}

	var r0 []keycloakapi.UserRepresentation
	var r1 *keycloakapi.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *keycloakapi.GetUsersParams) ([]keycloakapi.UserRepresentation, *keycloakapi.Response, error)); ok {
		return returnFunc(ctx, realm, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *keycloakapi.GetUsersParams) []keycloakapi.UserRepresentation); ok {
		r0 = returnFunc(ctx, realm, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]keycloakapi.UserRepresentation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *keycloakapi.GetUsersParams) *keycloakapi.Response); ok {
		r1 = returnFunc(ctx, realm, params)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*keycloakapi.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, *keycloakapi.GetUsersParams) error); ok {
		r2 = returnFunc(ctx, realm, params)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockUsersClient_GetUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsers'
type MockUsersClient_GetUsers_Call struct {
	*mock.Call
}

// GetUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - realm string
//   - params *keycloakapi.GetUsersParams
func (_e *MockUsersClient_Expecter) GetUsers(ctx interface{}, realm interface{}, params interface{}) *MockUsersClient_GetUsers_Call {
	return &MockUsersClient_GetUsers_Call{Call: _e.mock.On("GetUsers", ctx, realm, params)}
}

func (_c *MockUsersClient_GetUsers_Call) Run(run func(ctx context.Context, realm string, params *keycloakapi.GetUsersParams)) *MockUsersClient_GetUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *keycloakapi.GetUsersParams
		if args[2] != nil {
			arg2 = args[2].(*keycloakapi.GetUsersParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUsersClient_GetUsers_Call) Return(vs []keycloakapi.UserRepresentation, response *keycloakapi.Response, err error) *MockUsersClient_GetUsers_Call {
	_c.Call.Return(vs, response, err)
	return _c
}

func (_c *MockUsersClient_GetUsers_Call) RunAndReturn(run func(ctx context.Context, realm string, params *keycloakapi.GetUsersParams) ([]keycloakapi.UserRepresentation, *keycloakapi.Response, error)) *MockUsersClient_GetUsers_Call {
	_c.Call.Return(run)
	return _c
}

// GetUsersProfile provides a mock function for the type MockUsersClient
func (_mock *MockUsersClient) GetUsersProfile(ctx context.Context, realm string) (*keycloakapi.UserProfileConfig, *keycloakapi.Response, error) {
	ret := _mock.Called(ctx, realm)

	if len(ret) == 0 {
		panic("no return value specified for GetUsersProfile")
	}

	var r0 *keycloakapi.UserProfileConfig
	var r1 *keycloakapi.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*keycloakapi.UserProfileConfig, *keycloakapi.Response, error)); ok {
		return returnFunc(ctx, realm)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *keycloakapi.UserProfileConfig); ok {
		r0 = returnFunc(ctx, realm)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*keycloakapi.UserProfileConfig)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) *keycloakapi.Response); ok {
		r1 = returnFunc(ctx, realm)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*keycloakapi.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, realm)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockUsersClient_GetUsersProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsersProfile'
type MockUsersClient_GetUsersProfile_Call struct {
	*mock.Call
}

// GetUsersProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - realm string
func (_e *MockUsersClient_Expecter) GetUsersProfile(ctx interface{}, realm interface{}) *MockUsersClient_GetUsersProfile_Call {
	return &MockUsersClient_GetUsersProfile_Call{Call: _e.mock.On("GetUsersProfile", ctx, realm)}
}

func (_c *MockUsersClient_GetUsersProfile_Call) Run(run func(ctx context.Context, realm string)) *MockUsersClient_GetUsersProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsersClient_GetUsersProfile_Call) Return(v *keycloakapi.UserProfileConfig, response *keycloakapi.Response, err error) *MockUsersClient_GetUsersProfile_Call {
	_c.Call.Return(v, response, err)
	return _c
}

func (_c *MockUsersClient_GetUsersProfile_Call) RunAndReturn(run func(ctx context.Context, realm string) (*keycloakapi.UserProfileConfig, *keycloakapi.Response, error)) *MockUsersClient_GetUsersProfile_Call {
	_c.Call.Return(run)
	return _c
}

// ImpersonateUser provides a mock function for the type MockUsersClient
func (_mock *MockUsersClient) ImpersonateUser(ctx context.Context, realm string, userID string) (map[string]any, *keycloakapi.Response, error) {
	ret := _mock.Called(ctx, realm, userID)

	if len(ret) == 0 {
		panic("no return value specified for ImpersonateUser")
	}

	var r0 map[string]any
	var r1 *keycloakapi.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (map[string]any, *keycloakapi.Response, error)); ok {
		return returnFunc(ctx, realm, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) map[string]any); ok {
		r0 = returnFunc(ctx, realm, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) *keycloakapi.Response); ok {
		r1 = returnFunc(ctx, realm, userID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*keycloakapi.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = returnFunc(ctx, realm, userID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockUsersClient_ImpersonateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ImpersonateUser'
type MockUsersClient_ImpersonateUser_Call struct {
	*mock.Call
}

// ImpersonateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - realm string
//   - userID string
func (_e *MockUsersClient_Expecter) ImpersonateUser(ctx interface{}, realm interface{}, userID interface{}) *MockUsersClient_ImpersonateUser_Call {
	return &MockUsersClient_ImpersonateUser_Call{Call: _e.mock.On("ImpersonateUser", ctx, realm, userID)}
}

func (_c *MockUsersClient_ImpersonateUser_Call) Run(run func(ctx context.Context, realm string, userID string)) *MockUsersClient_ImpersonateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUsersClient_ImpersonateUser_Call) Return(stringToV map[string]any, response *keycloakapi.Response, err error) *MockUsersClient_ImpersonateUser_Call {
	_c.Call.Return(stringToV, response, err)
	return _c
}

func (_c *MockUsersClient_ImpersonateUser_Call) RunAndReturn(run func(ctx context.Context, realm string, userID string) (map[string]any, *keycloakapi.Response, error)) *MockUsersClient_ImpersonateUser_Call {
	_c.Call.Return(run)
	return _c
}

// LogoutUser provides a mock function for the type MockUsersClient
func (_mock *MockUsersClient) LogoutUser(ctx context.Context, realm string, userID string) (*keycloakapi.Response, error) {
	ret := _mock.Called(ctx, realm, userID)

	if len(ret) == 0 {
		panic("no return value specified for LogoutUser")
	}

	var r0 *keycloakapi.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*keycloakapi.Response, error)); ok {
		return returnFunc(ctx, realm, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *keycloakapi.Response); ok {
		r0 = returnFunc(ctx, realm, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*keycloakapi.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, realm, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsersClient_LogoutUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogoutUser'
type MockUsersClient_LogoutUser_Call struct {
	*mock.Call
}

// LogoutUser is a helper method to define mock.On call
//   - ctx context.Context
//   - realm string
//   - userID string
func (_e *MockUsersClient_Expecter) LogoutUser(ctx interface{}, realm interface{}, userID interface{}) *MockUsersClient_LogoutUser_Call {
	return &MockUsersClient_LogoutUser_Call{Call: _e.mock.On("LogoutUser", ctx, realm, userID)}
}

func (_c *MockUsersClient_LogoutUser_Call) Run(run func(ctx context.Context, realm string, userID string)) *MockUsersClient_LogoutUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUsersClient_LogoutUser_Call) Return(response *keycloakapi.Response, err error) *MockUsersClient_LogoutUser_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockUsersClient_LogoutUser_Call) RunAndReturn(run func(ctx context.Context, realm string, userID string) (*keycloakapi.Response, error)) *MockUsersClient_LogoutUser_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveUserFromGroup provides a mock function for the type MockUsersClient
func (_mock *MockUsersClient) RemoveUserFromGroup(ctx context.Context, realm string, userID string, groupID string) (*keycloakapi.Response, error) {
	ret := _mock.Called(ctx, realm, userID, groupID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveUserFromGroup")
	}

	var r0 *keycloakapi.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (*keycloakapi.Response, error)); ok {
		return returnFunc(ctx, realm, userID, groupID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) *keycloakapi.Response); ok {
		r0 = returnFunc(ctx, realm, userID, groupID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*keycloakapi.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, realm, userID, groupID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsersClient_RemoveUserFromGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveUserFromGroup'
type MockUsersClient_RemoveUserFromGroup_Call struct {
	*mock.Call
}

// RemoveUserFromGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - realm string
//   - userID string
//   - groupID string
func (_e *MockUsersClient_Expecter) RemoveUserFromGroup(ctx interface{}, realm interface{}, userID interface{}, groupID interface{}) *MockUsersClient_RemoveUserFromGroup_Call {
	return &MockUsersClient_RemoveUserFromGroup_Call{Call: _e.mock.On("RemoveUserFromGroup", ctx, realm, userID, groupID)}
}

func (_c *MockUsersClient_RemoveUserFromGroup_Call) Run(run func(ctx context.Context, realm string, userID string, groupID string)) *MockUsersClient_RemoveUserFromGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockUsersClient_RemoveUserFromGroup_Call) Return(response *keycloakapi.Response, err error) *MockUsersClient_RemoveUserFromGroup_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockUsersClient_RemoveUserFromGroup_Call) RunAndReturn(run func(ctx context.Context, realm string, userID string, groupID string) (*keycloakapi.Response, error)) *MockUsersClient_RemoveUserFromGroup_Call {
	_c.Call.Return(run)
	return _c
}

// SendVerifyEmail provides a mock function for the type MockUsersClient
func (_mock *MockUsersClient) SendVerifyEmail(ctx context.Context, realm string, userID string) (*keycloakapi.Response, error) {
	ret := _mock.Called(ctx, realm, userID)

	if len(ret) == 0 {
		panic("no return value specified for SendVerifyEmail")
	}

	var r0 *keycloakapi.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*keycloakapi.Response, error)); ok {
		return returnFunc(ctx, realm, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *keycloakapi.Response); ok {
		r0 = returnFunc(ctx, realm, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*keycloakapi.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, realm, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsersClient_SendVerifyEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendVerifyEmail'
type MockUsersClient_SendVerifyEmail_Call struct {
	*mock.Call
}

// SendVerifyEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - realm string
//   - userID string
func (_e *MockUsersClient_Expecter) SendVerifyEmail(ctx interface{}, realm interface{}, userID interface{}) *MockUsersClient_SendVerifyEmail_Call {
	return &MockUsersClient_SendVerifyEmail_Call{Call: _e.mock.On("SendVerifyEmail", ctx, realm, userID)}
}

func (_c *MockUsersClient_SendVerifyEmail_Call) Run(run func(ctx context.Context, realm string, userID string)) *MockUsersClient_SendVerifyEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUsersClient_SendVerifyEmail_Call) Return(response *keycloakapi.Response, err error) *MockUsersClient_SendVerifyEmail_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockUsersClient_SendVerifyEmail_Call) RunAndReturn(run func(ctx context.Context, realm string, userID string) (*keycloakapi.Response, error)) *MockUsersClient_SendVerifyEmail_Call {
	_c.Call.Return(run)
	return _c
}

// SetUserPassword provides a mock function for the type MockUsersClient
func (_mock *MockUsersClient) SetUserPassword(ctx context.Context, realm string, userID string, cred keycloakapi.CredentialRepresentation) (*keycloakapi.Response, error) {
	ret := _mock.Called(ctx, realm, userID, cred)

	if len(ret) == 0 {
		panic("no return value specified for SetUserPassword")
	}

	var r0 *keycloakapi.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, keycloakapi.CredentialRepresentation) (*keycloakapi.Response, error)); ok {
		return returnFunc(ctx, realm, userID, cred)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, keycloakapi.CredentialRepresentation) *keycloakapi.Response); ok {
		r0 = returnFunc(ctx, realm, userID, cred)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*keycloakapi.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, keycloakapi.CredentialRepresentation) error); ok {
		r1 = returnFunc(ctx, realm, userID, cred)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsersClient_SetUserPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetUserPassword'
type MockUsersClient_SetUserPassword_Call struct {
	*mock.Call
}

// SetUserPassword is a helper method to define mock.On call
//   - ctx context.Context
//   - realm string
//   - userID string
//   - cred keycloakapi.CredentialRepresentation
func (_e *MockUsersClient_Expecter) SetUserPassword(ctx interface{}, realm interface{}, userID interface{}, cred interface{}) *MockUsersClient_SetUserPassword_Call {
	return &MockUsersClient_SetUserPassword_Call{Call: _e.mock.On("SetUserPassword", ctx, realm, userID, cred)}
}

func (_c *MockUsersClient_SetUserPassword_Call) Run(run func(ctx context.Context, realm string, userID string, cred keycloakapi.CredentialRepresentation)) *MockUsersClient_SetUserPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 keycloakapi.CredentialRepresentation
		if args[3] != nil {
			arg3 = args[3].(keycloakapi.CredentialRepresentation)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockUsersClient_SetUserPassword_Call) Return(response *keycloakapi.Response, err error) *MockUsersClient_SetUserPassword_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockUsersClient_SetUserPassword_Call) RunAndReturn(run func(ctx context.Context, realm string, userID string, cred keycloakapi.CredentialRepresentation) (*keycloakapi.Response, error)) *MockUsersClient_SetUserPassword_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function for the type MockUsersClient
func (_mock *MockUsersClient) UpdateUser(ctx context.Context, realm string, userID string, user keycloakapi.UserRepresentation) (*keycloakapi.Response, error) {
	ret := _mock.Called(ctx, realm, userID, user)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 *keycloakapi.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, keycloakapi.UserRepresentation) (*keycloakapi.Response, error)); ok {
		return returnFunc(ctx, realm, userID, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, keycloakapi.UserRepresentation) *keycloakapi.Response); ok {
		r0 = returnFunc(ctx, realm, userID, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*keycloakapi.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, keycloakapi.UserRepresentation) error); ok {
		r1 = returnFunc(ctx, realm, userID, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsersClient_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type MockUsersClient_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - realm string
//   - userID string
//   - user keycloakapi.UserRepresentation
func (_e *MockUsersClient_Expecter) UpdateUser(ctx interface{}, realm interface{}, userID interface{}, user interface{}) *MockUsersClient_UpdateUser_Call {
	return &MockUsersClient_UpdateUser_Call{Call: _e.mock.On("UpdateUser", ctx, realm, userID, user)}
}

func (_c *MockUsersClient_UpdateUser_Call) Run(run func(ctx context.Context, realm string, userID string, user keycloakapi.UserRepresentation)) *MockUsersClient_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 keycloakapi.UserRepresentation
		if args[3] != nil {
			arg3 = args[3].(keycloakapi.UserRepresentation)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockUsersClient_UpdateUser_Call) Return(response *keycloakapi.Response, err error) *MockUsersClient_UpdateUser_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockUsersClient_UpdateUser_Call) RunAndReturn(run func(ctx context.Context, realm string, userID string, user keycloakapi.UserRepresentation) (*keycloakapi.Response, error)) *MockUsersClient_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUsersProfile provides a mock function for the type MockUsersClient
func (_mock *MockUsersClient) UpdateUsersProfile(ctx context.Context, realm string, userProfile keycloakapi.UserProfileConfig) (*keycloakapi.UserProfileConfig, *keycloakapi.Response, error) {
	ret := _mock.Called(ctx, realm, userProfile)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUsersProfile")
	}

	var r0 *keycloakapi.UserProfileConfig
	var r1 *keycloakapi.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, keycloakapi.UserProfileConfig) (*keycloakapi.UserProfileConfig, *keycloakapi.Response, error)); ok {
		return returnFunc(ctx, realm, userProfile)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, keycloakapi.UserProfileConfig) *keycloakapi.UserProfileConfig); ok {
		r0 = returnFunc(ctx, realm, userProfile)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*keycloakapi.UserProfileConfig)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, keycloakapi.UserProfileConfig) *keycloakapi.Response); ok {
		r1 = returnFunc(ctx, realm, userProfile)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*keycloakapi.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, keycloakapi.UserProfileConfig) error); ok {
		r2 = returnFunc(ctx, realm, userProfile)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockUsersClient_UpdateUsersProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUsersProfile'
type MockUsersClient_UpdateUsersProfile_Call struct {
	*mock.Call
}

// UpdateUsersProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - realm string
//   - userProfile keycloakapi.UserProfileConfig
func (_e *MockUsersClient_Expecter) UpdateUsersProfile(ctx interface{}, realm interface{}, userProfile interface{}) *MockUsersClient_UpdateUsersProfile_Call {
	return &MockUsersClient_UpdateUsersProfile_Call{Call: _e.mock.On("UpdateUsersProfile", ctx, realm, userProfile)}
}

func (_c *MockUsersClient_UpdateUsersProfile_Call) Run(run func(ctx context.Context, realm string, userProfile keycloakapi.UserProfileConfig)) *MockUsersClient_UpdateUsersProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 keycloakapi.UserProfileConfig
		if args[2] != nil {
			arg2 = args[2].(keycloakapi.UserProfileConfig)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUsersClient_UpdateUsersProfile_Call) Return(v *keycloakapi.UserProfileConfig, response *keycloakapi.Response, err error) *MockUsersClient_UpdateUsersProfile_Call {
	_c.Call.Return(v, response, err)
	return _c
}

func (_c *MockUsersClient_UpdateUsersProfile_Call) RunAndReturn(run func(ctx context.Context, realm string, userProfile keycloakapi.UserProfileConfig) (*keycloakapi.UserProfileConfig, *keycloakapi.Response, error)) *MockUsersClient_UpdateUsersProfile_Call {
	_c.Call.Return(run)
	return _c
}
