apiVersion: v1.edp.epam.com/v1alpha1
kind: Keycloak
metadata:
  name: example-keycloak
spec:
  url: http://keycloak.security:8080
  secret: keycloak-secret
  realmName: openshift
  users:
    - username: test_user@edp.epam.com
      roles:
        - Administrator