apiVersion: v1.edp.epam.com/v1
kind: KeycloakClient
metadata:
  name: keycloakclient-sample
spec:
  advancedProtocolMappers: true
  clientId: agocd
  directAccess: true
  public: false
  secret: ''
  targetRealm: edp-main
  webUrl: https://argocd.example.com
  defaultClientScopes:
    - argocd_groups
