apiVersion: v1.edp.epam.com/v1
kind: KeycloakRealmRoleBatch
metadata:
  name: keycloakrealmrolebatch-sample
spec:
  realmRef:
    name: keycloakrealm-sample
    kind: KeycloakRealm
  roles:
    - composite: true
      description: default developer role
      isDefault: false
      name: developer
    - composite: true
      description: default administrator role
      isDefault: false
      name: administrator
