apiVersion: v1.edp.epam.com/v1
kind: KeycloakRealmRole
metadata:
  name: keycloakrealmrole-sample
spec:
  attributes: null
  composite: true
  composites: null
  description: default developer role
  name: developer
  realm: main
