// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/Nerzal/gocloak/v12"
	"github.com/epam/edp-keycloak-operator/api/v1"
	"github.com/epam/edp-keycloak-operator/api/v1alpha1"
	"github.com/epam/edp-keycloak-operator/internal/controller/helper"
	"github.com/epam/edp-keycloak-operator/pkg/client/keycloak"
	mock "github.com/stretchr/testify/mock"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

// NewMockControllerHelper creates a new instance of MockControllerHelper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockControllerHelper(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockControllerHelper {
	mock := &MockControllerHelper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockControllerHelper is an autogenerated mock type for the ControllerHelper type
type MockControllerHelper struct {
	mock.Mock
}

type MockControllerHelper_Expecter struct {
	mock *mock.Mock
}

func (_m *MockControllerHelper) EXPECT() *MockControllerHelper_Expecter {
	return &MockControllerHelper_Expecter{mock: &_m.Mock}
}

// CreateKeycloakClient provides a mock function for the type MockControllerHelper
func (_mock *MockControllerHelper) CreateKeycloakClient(ctx context.Context, url string, user string, password string, adminType string, caCert string, insecureSkipVerify bool) (keycloak.Client, error) {
	ret := _mock.Called(ctx, url, user, password, adminType, caCert, insecureSkipVerify)

	if len(ret) == 0 {
		panic("no return value specified for CreateKeycloakClient")
	}

	var r0 keycloak.Client
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string, string, bool) (keycloak.Client, error)); ok {
		return returnFunc(ctx, url, user, password, adminType, caCert, insecureSkipVerify)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string, string, bool) keycloak.Client); ok {
		r0 = returnFunc(ctx, url, user, password, adminType, caCert, insecureSkipVerify)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(keycloak.Client)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, string, string, bool) error); ok {
		r1 = returnFunc(ctx, url, user, password, adminType, caCert, insecureSkipVerify)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockControllerHelper_CreateKeycloakClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateKeycloakClient'
type MockControllerHelper_CreateKeycloakClient_Call struct {
	*mock.Call
}

// CreateKeycloakClient is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - user string
//   - password string
//   - adminType string
//   - caCert string
//   - insecureSkipVerify bool
func (_e *MockControllerHelper_Expecter) CreateKeycloakClient(ctx interface{}, url interface{}, user interface{}, password interface{}, adminType interface{}, caCert interface{}, insecureSkipVerify interface{}) *MockControllerHelper_CreateKeycloakClient_Call {
	return &MockControllerHelper_CreateKeycloakClient_Call{Call: _e.mock.On("CreateKeycloakClient", ctx, url, user, password, adminType, caCert, insecureSkipVerify)}
}

func (_c *MockControllerHelper_CreateKeycloakClient_Call) Run(run func(ctx context.Context, url string, user string, password string, adminType string, caCert string, insecureSkipVerify bool)) *MockControllerHelper_CreateKeycloakClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		var arg6 bool
		if args[6] != nil {
			arg6 = args[6].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
		)
	})
	return _c
}

func (_c *MockControllerHelper_CreateKeycloakClient_Call) Return(client keycloak.Client, err error) *MockControllerHelper_CreateKeycloakClient_Call {
	_c.Call.Return(client, err)
	return _c
}

func (_c *MockControllerHelper_CreateKeycloakClient_Call) RunAndReturn(run func(ctx context.Context, url string, user string, password string, adminType string, caCert string, insecureSkipVerify bool) (keycloak.Client, error)) *MockControllerHelper_CreateKeycloakClient_Call {
	_c.Call.Return(run)
	return _c
}

// CreateKeycloakClientFomAuthData provides a mock function for the type MockControllerHelper
func (_mock *MockControllerHelper) CreateKeycloakClientFomAuthData(ctx context.Context, authData *helper.KeycloakAuthData) (keycloak.Client, error) {
	ret := _mock.Called(ctx, authData)

	if len(ret) == 0 {
		panic("no return value specified for CreateKeycloakClientFomAuthData")
	}

	var r0 keycloak.Client
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *helper.KeycloakAuthData) (keycloak.Client, error)); ok {
		return returnFunc(ctx, authData)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *helper.KeycloakAuthData) keycloak.Client); ok {
		r0 = returnFunc(ctx, authData)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(keycloak.Client)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *helper.KeycloakAuthData) error); ok {
		r1 = returnFunc(ctx, authData)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockControllerHelper_CreateKeycloakClientFomAuthData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateKeycloakClientFomAuthData'
type MockControllerHelper_CreateKeycloakClientFomAuthData_Call struct {
	*mock.Call
}

// CreateKeycloakClientFomAuthData is a helper method to define mock.On call
//   - ctx context.Context
//   - authData *helper.KeycloakAuthData
func (_e *MockControllerHelper_Expecter) CreateKeycloakClientFomAuthData(ctx interface{}, authData interface{}) *MockControllerHelper_CreateKeycloakClientFomAuthData_Call {
	return &MockControllerHelper_CreateKeycloakClientFomAuthData_Call{Call: _e.mock.On("CreateKeycloakClientFomAuthData", ctx, authData)}
}

func (_c *MockControllerHelper_CreateKeycloakClientFomAuthData_Call) Run(run func(ctx context.Context, authData *helper.KeycloakAuthData)) *MockControllerHelper_CreateKeycloakClientFomAuthData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *helper.KeycloakAuthData
		if args[1] != nil {
			arg1 = args[1].(*helper.KeycloakAuthData)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockControllerHelper_CreateKeycloakClientFomAuthData_Call) Return(client keycloak.Client, err error) *MockControllerHelper_CreateKeycloakClientFomAuthData_Call {
	_c.Call.Return(client, err)
	return _c
}

func (_c *MockControllerHelper_CreateKeycloakClientFomAuthData_Call) RunAndReturn(run func(ctx context.Context, authData *helper.KeycloakAuthData) (keycloak.Client, error)) *MockControllerHelper_CreateKeycloakClientFomAuthData_Call {
	_c.Call.Return(run)
	return _c
}

// CreateKeycloakClientFromClusterRealm provides a mock function for the type MockControllerHelper
func (_mock *MockControllerHelper) CreateKeycloakClientFromClusterRealm(ctx context.Context, realm *v1alpha1.ClusterKeycloakRealm) (keycloak.Client, error) {
	ret := _mock.Called(ctx, realm)

	if len(ret) == 0 {
		panic("no return value specified for CreateKeycloakClientFromClusterRealm")
	}

	var r0 keycloak.Client
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1alpha1.ClusterKeycloakRealm) (keycloak.Client, error)); ok {
		return returnFunc(ctx, realm)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1alpha1.ClusterKeycloakRealm) keycloak.Client); ok {
		r0 = returnFunc(ctx, realm)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(keycloak.Client)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1alpha1.ClusterKeycloakRealm) error); ok {
		r1 = returnFunc(ctx, realm)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockControllerHelper_CreateKeycloakClientFromClusterRealm_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateKeycloakClientFromClusterRealm'
type MockControllerHelper_CreateKeycloakClientFromClusterRealm_Call struct {
	*mock.Call
}

// CreateKeycloakClientFromClusterRealm is a helper method to define mock.On call
//   - ctx context.Context
//   - realm *v1alpha1.ClusterKeycloakRealm
func (_e *MockControllerHelper_Expecter) CreateKeycloakClientFromClusterRealm(ctx interface{}, realm interface{}) *MockControllerHelper_CreateKeycloakClientFromClusterRealm_Call {
	return &MockControllerHelper_CreateKeycloakClientFromClusterRealm_Call{Call: _e.mock.On("CreateKeycloakClientFromClusterRealm", ctx, realm)}
}

func (_c *MockControllerHelper_CreateKeycloakClientFromClusterRealm_Call) Run(run func(ctx context.Context, realm *v1alpha1.ClusterKeycloakRealm)) *MockControllerHelper_CreateKeycloakClientFromClusterRealm_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1alpha1.ClusterKeycloakRealm
		if args[1] != nil {
			arg1 = args[1].(*v1alpha1.ClusterKeycloakRealm)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockControllerHelper_CreateKeycloakClientFromClusterRealm_Call) Return(client keycloak.Client, err error) *MockControllerHelper_CreateKeycloakClientFromClusterRealm_Call {
	_c.Call.Return(client, err)
	return _c
}

func (_c *MockControllerHelper_CreateKeycloakClientFromClusterRealm_Call) RunAndReturn(run func(ctx context.Context, realm *v1alpha1.ClusterKeycloakRealm) (keycloak.Client, error)) *MockControllerHelper_CreateKeycloakClientFromClusterRealm_Call {
	_c.Call.Return(run)
	return _c
}

// CreateKeycloakClientFromRealm provides a mock function for the type MockControllerHelper
func (_mock *MockControllerHelper) CreateKeycloakClientFromRealm(ctx context.Context, realm *v1.KeycloakRealm) (keycloak.Client, error) {
	ret := _mock.Called(ctx, realm)

	if len(ret) == 0 {
		panic("no return value specified for CreateKeycloakClientFromRealm")
	}

	var r0 keycloak.Client
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.KeycloakRealm) (keycloak.Client, error)); ok {
		return returnFunc(ctx, realm)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.KeycloakRealm) keycloak.Client); ok {
		r0 = returnFunc(ctx, realm)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(keycloak.Client)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.KeycloakRealm) error); ok {
		r1 = returnFunc(ctx, realm)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockControllerHelper_CreateKeycloakClientFromRealm_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateKeycloakClientFromRealm'
type MockControllerHelper_CreateKeycloakClientFromRealm_Call struct {
	*mock.Call
}

// CreateKeycloakClientFromRealm is a helper method to define mock.On call
//   - ctx context.Context
//   - realm *v1.KeycloakRealm
func (_e *MockControllerHelper_Expecter) CreateKeycloakClientFromRealm(ctx interface{}, realm interface{}) *MockControllerHelper_CreateKeycloakClientFromRealm_Call {
	return &MockControllerHelper_CreateKeycloakClientFromRealm_Call{Call: _e.mock.On("CreateKeycloakClientFromRealm", ctx, realm)}
}

func (_c *MockControllerHelper_CreateKeycloakClientFromRealm_Call) Run(run func(ctx context.Context, realm *v1.KeycloakRealm)) *MockControllerHelper_CreateKeycloakClientFromRealm_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.KeycloakRealm
		if args[1] != nil {
			arg1 = args[1].(*v1.KeycloakRealm)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockControllerHelper_CreateKeycloakClientFromRealm_Call) Return(client keycloak.Client, err error) *MockControllerHelper_CreateKeycloakClientFromRealm_Call {
	_c.Call.Return(client, err)
	return _c
}

func (_c *MockControllerHelper_CreateKeycloakClientFromRealm_Call) RunAndReturn(run func(ctx context.Context, realm *v1.KeycloakRealm) (keycloak.Client, error)) *MockControllerHelper_CreateKeycloakClientFromRealm_Call {
	_c.Call.Return(run)
	return _c
}

// CreateKeycloakClientFromRealmRef provides a mock function for the type MockControllerHelper
func (_mock *MockControllerHelper) CreateKeycloakClientFromRealmRef(ctx context.Context, object helper.ObjectWithRealmRef) (keycloak.Client, error) {
	ret := _mock.Called(ctx, object)

	if len(ret) == 0 {
		panic("no return value specified for CreateKeycloakClientFromRealmRef")
	}

	var r0 keycloak.Client
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, helper.ObjectWithRealmRef) (keycloak.Client, error)); ok {
		return returnFunc(ctx, object)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, helper.ObjectWithRealmRef) keycloak.Client); ok {
		r0 = returnFunc(ctx, object)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(keycloak.Client)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, helper.ObjectWithRealmRef) error); ok {
		r1 = returnFunc(ctx, object)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockControllerHelper_CreateKeycloakClientFromRealmRef_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateKeycloakClientFromRealmRef'
type MockControllerHelper_CreateKeycloakClientFromRealmRef_Call struct {
	*mock.Call
}

// CreateKeycloakClientFromRealmRef is a helper method to define mock.On call
//   - ctx context.Context
//   - object helper.ObjectWithRealmRef
func (_e *MockControllerHelper_Expecter) CreateKeycloakClientFromRealmRef(ctx interface{}, object interface{}) *MockControllerHelper_CreateKeycloakClientFromRealmRef_Call {
	return &MockControllerHelper_CreateKeycloakClientFromRealmRef_Call{Call: _e.mock.On("CreateKeycloakClientFromRealmRef", ctx, object)}
}

func (_c *MockControllerHelper_CreateKeycloakClientFromRealmRef_Call) Run(run func(ctx context.Context, object helper.ObjectWithRealmRef)) *MockControllerHelper_CreateKeycloakClientFromRealmRef_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 helper.ObjectWithRealmRef
		if args[1] != nil {
			arg1 = args[1].(helper.ObjectWithRealmRef)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockControllerHelper_CreateKeycloakClientFromRealmRef_Call) Return(client keycloak.Client, err error) *MockControllerHelper_CreateKeycloakClientFromRealmRef_Call {
	_c.Call.Return(client, err)
	return _c
}

func (_c *MockControllerHelper_CreateKeycloakClientFromRealmRef_Call) RunAndReturn(run func(ctx context.Context, object helper.ObjectWithRealmRef) (keycloak.Client, error)) *MockControllerHelper_CreateKeycloakClientFromRealmRef_Call {
	_c.Call.Return(run)
	return _c
}

// GetKeycloakRealmFromRef provides a mock function for the type MockControllerHelper
func (_mock *MockControllerHelper) GetKeycloakRealmFromRef(ctx context.Context, object helper.ObjectWithRealmRef, kcClient keycloak.Client) (*gocloak.RealmRepresentation, error) {
	ret := _mock.Called(ctx, object, kcClient)

	if len(ret) == 0 {
		panic("no return value specified for GetKeycloakRealmFromRef")
	}

	var r0 *gocloak.RealmRepresentation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, helper.ObjectWithRealmRef, keycloak.Client) (*gocloak.RealmRepresentation, error)); ok {
		return returnFunc(ctx, object, kcClient)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, helper.ObjectWithRealmRef, keycloak.Client) *gocloak.RealmRepresentation); ok {
		r0 = returnFunc(ctx, object, kcClient)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gocloak.RealmRepresentation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, helper.ObjectWithRealmRef, keycloak.Client) error); ok {
		r1 = returnFunc(ctx, object, kcClient)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockControllerHelper_GetKeycloakRealmFromRef_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetKeycloakRealmFromRef'
type MockControllerHelper_GetKeycloakRealmFromRef_Call struct {
	*mock.Call
}

// GetKeycloakRealmFromRef is a helper method to define mock.On call
//   - ctx context.Context
//   - object helper.ObjectWithRealmRef
//   - kcClient keycloak.Client
func (_e *MockControllerHelper_Expecter) GetKeycloakRealmFromRef(ctx interface{}, object interface{}, kcClient interface{}) *MockControllerHelper_GetKeycloakRealmFromRef_Call {
	return &MockControllerHelper_GetKeycloakRealmFromRef_Call{Call: _e.mock.On("GetKeycloakRealmFromRef", ctx, object, kcClient)}
}

func (_c *MockControllerHelper_GetKeycloakRealmFromRef_Call) Run(run func(ctx context.Context, object helper.ObjectWithRealmRef, kcClient keycloak.Client)) *MockControllerHelper_GetKeycloakRealmFromRef_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 helper.ObjectWithRealmRef
		if args[1] != nil {
			arg1 = args[1].(helper.ObjectWithRealmRef)
		}
		var arg2 keycloak.Client
		if args[2] != nil {
			arg2 = args[2].(keycloak.Client)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockControllerHelper_GetKeycloakRealmFromRef_Call) Return(realmRepresentation *gocloak.RealmRepresentation, err error) *MockControllerHelper_GetKeycloakRealmFromRef_Call {
	_c.Call.Return(realmRepresentation, err)
	return _c
}

func (_c *MockControllerHelper_GetKeycloakRealmFromRef_Call) RunAndReturn(run func(ctx context.Context, object helper.ObjectWithRealmRef, kcClient keycloak.Client) (*gocloak.RealmRepresentation, error)) *MockControllerHelper_GetKeycloakRealmFromRef_Call {
	_c.Call.Return(run)
	return _c
}

// InvalidateKeycloakClientTokenSecret provides a mock function for the type MockControllerHelper
func (_mock *MockControllerHelper) InvalidateKeycloakClientTokenSecret(ctx context.Context, namespace string, rootKeycloakName string) error {
	ret := _mock.Called(ctx, namespace, rootKeycloakName)

	if len(ret) == 0 {
		panic("no return value specified for InvalidateKeycloakClientTokenSecret")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, namespace, rootKeycloakName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockControllerHelper_InvalidateKeycloakClientTokenSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InvalidateKeycloakClientTokenSecret'
type MockControllerHelper_InvalidateKeycloakClientTokenSecret_Call struct {
	*mock.Call
}

// InvalidateKeycloakClientTokenSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - rootKeycloakName string
func (_e *MockControllerHelper_Expecter) InvalidateKeycloakClientTokenSecret(ctx interface{}, namespace interface{}, rootKeycloakName interface{}) *MockControllerHelper_InvalidateKeycloakClientTokenSecret_Call {
	return &MockControllerHelper_InvalidateKeycloakClientTokenSecret_Call{Call: _e.mock.On("InvalidateKeycloakClientTokenSecret", ctx, namespace, rootKeycloakName)}
}

func (_c *MockControllerHelper_InvalidateKeycloakClientTokenSecret_Call) Run(run func(ctx context.Context, namespace string, rootKeycloakName string)) *MockControllerHelper_InvalidateKeycloakClientTokenSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockControllerHelper_InvalidateKeycloakClientTokenSecret_Call) Return(err error) *MockControllerHelper_InvalidateKeycloakClientTokenSecret_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockControllerHelper_InvalidateKeycloakClientTokenSecret_Call) RunAndReturn(run func(ctx context.Context, namespace string, rootKeycloakName string) error) *MockControllerHelper_InvalidateKeycloakClientTokenSecret_Call {
	_c.Call.Return(run)
	return _c
}

// SetFailureCount provides a mock function for the type MockControllerHelper
func (_mock *MockControllerHelper) SetFailureCount(fc helper.FailureCountable) time.Duration {
	ret := _mock.Called(fc)

	if len(ret) == 0 {
		panic("no return value specified for SetFailureCount")
	}

	var r0 time.Duration
	if returnFunc, ok := ret.Get(0).(func(helper.FailureCountable) time.Duration); ok {
		r0 = returnFunc(fc)
	} else {
		r0 = ret.Get(0).(time.Duration)
	}
	return r0
}

// MockControllerHelper_SetFailureCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetFailureCount'
type MockControllerHelper_SetFailureCount_Call struct {
	*mock.Call
}

// SetFailureCount is a helper method to define mock.On call
//   - fc helper.FailureCountable
func (_e *MockControllerHelper_Expecter) SetFailureCount(fc interface{}) *MockControllerHelper_SetFailureCount_Call {
	return &MockControllerHelper_SetFailureCount_Call{Call: _e.mock.On("SetFailureCount", fc)}
}

func (_c *MockControllerHelper_SetFailureCount_Call) Run(run func(fc helper.FailureCountable)) *MockControllerHelper_SetFailureCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 helper.FailureCountable
		if args[0] != nil {
			arg0 = args[0].(helper.FailureCountable)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockControllerHelper_SetFailureCount_Call) Return(duration time.Duration) *MockControllerHelper_SetFailureCount_Call {
	_c.Call.Return(duration)
	return _c
}

func (_c *MockControllerHelper_SetFailureCount_Call) RunAndReturn(run func(fc helper.FailureCountable) time.Duration) *MockControllerHelper_SetFailureCount_Call {
	_c.Call.Return(run)
	return _c
}

// SetKeycloakOwnerRef provides a mock function for the type MockControllerHelper
func (_mock *MockControllerHelper) SetKeycloakOwnerRef(ctx context.Context, object helper.ObjectWithKeycloakRef) error {
	ret := _mock.Called(ctx, object)

	if len(ret) == 0 {
		panic("no return value specified for SetKeycloakOwnerRef")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, helper.ObjectWithKeycloakRef) error); ok {
		r0 = returnFunc(ctx, object)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockControllerHelper_SetKeycloakOwnerRef_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetKeycloakOwnerRef'
type MockControllerHelper_SetKeycloakOwnerRef_Call struct {
	*mock.Call
}

// SetKeycloakOwnerRef is a helper method to define mock.On call
//   - ctx context.Context
//   - object helper.ObjectWithKeycloakRef
func (_e *MockControllerHelper_Expecter) SetKeycloakOwnerRef(ctx interface{}, object interface{}) *MockControllerHelper_SetKeycloakOwnerRef_Call {
	return &MockControllerHelper_SetKeycloakOwnerRef_Call{Call: _e.mock.On("SetKeycloakOwnerRef", ctx, object)}
}

func (_c *MockControllerHelper_SetKeycloakOwnerRef_Call) Run(run func(ctx context.Context, object helper.ObjectWithKeycloakRef)) *MockControllerHelper_SetKeycloakOwnerRef_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 helper.ObjectWithKeycloakRef
		if args[1] != nil {
			arg1 = args[1].(helper.ObjectWithKeycloakRef)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockControllerHelper_SetKeycloakOwnerRef_Call) Return(err error) *MockControllerHelper_SetKeycloakOwnerRef_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockControllerHelper_SetKeycloakOwnerRef_Call) RunAndReturn(run func(ctx context.Context, object helper.ObjectWithKeycloakRef) error) *MockControllerHelper_SetKeycloakOwnerRef_Call {
	_c.Call.Return(run)
	return _c
}

// SetRealmOwnerRef provides a mock function for the type MockControllerHelper
func (_mock *MockControllerHelper) SetRealmOwnerRef(ctx context.Context, object helper.ObjectWithRealmRef) error {
	ret := _mock.Called(ctx, object)

	if len(ret) == 0 {
		panic("no return value specified for SetRealmOwnerRef")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, helper.ObjectWithRealmRef) error); ok {
		r0 = returnFunc(ctx, object)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockControllerHelper_SetRealmOwnerRef_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetRealmOwnerRef'
type MockControllerHelper_SetRealmOwnerRef_Call struct {
	*mock.Call
}

// SetRealmOwnerRef is a helper method to define mock.On call
//   - ctx context.Context
//   - object helper.ObjectWithRealmRef
func (_e *MockControllerHelper_Expecter) SetRealmOwnerRef(ctx interface{}, object interface{}) *MockControllerHelper_SetRealmOwnerRef_Call {
	return &MockControllerHelper_SetRealmOwnerRef_Call{Call: _e.mock.On("SetRealmOwnerRef", ctx, object)}
}

func (_c *MockControllerHelper_SetRealmOwnerRef_Call) Run(run func(ctx context.Context, object helper.ObjectWithRealmRef)) *MockControllerHelper_SetRealmOwnerRef_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 helper.ObjectWithRealmRef
		if args[1] != nil {
			arg1 = args[1].(helper.ObjectWithRealmRef)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockControllerHelper_SetRealmOwnerRef_Call) Return(err error) *MockControllerHelper_SetRealmOwnerRef_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockControllerHelper_SetRealmOwnerRef_Call) RunAndReturn(run func(ctx context.Context, object helper.ObjectWithRealmRef) error) *MockControllerHelper_SetRealmOwnerRef_Call {
	_c.Call.Return(run)
	return _c
}

// TryRemoveFinalizer provides a mock function for the type MockControllerHelper
func (_mock *MockControllerHelper) TryRemoveFinalizer(ctx context.Context, obj client.Object, finalizer string) error {
	ret := _mock.Called(ctx, obj, finalizer)

	if len(ret) == 0 {
		panic("no return value specified for TryRemoveFinalizer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, client.Object, string) error); ok {
		r0 = returnFunc(ctx, obj, finalizer)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockControllerHelper_TryRemoveFinalizer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TryRemoveFinalizer'
type MockControllerHelper_TryRemoveFinalizer_Call struct {
	*mock.Call
}

// TryRemoveFinalizer is a helper method to define mock.On call
//   - ctx context.Context
//   - obj client.Object
//   - finalizer string
func (_e *MockControllerHelper_Expecter) TryRemoveFinalizer(ctx interface{}, obj interface{}, finalizer interface{}) *MockControllerHelper_TryRemoveFinalizer_Call {
	return &MockControllerHelper_TryRemoveFinalizer_Call{Call: _e.mock.On("TryRemoveFinalizer", ctx, obj, finalizer)}
}

func (_c *MockControllerHelper_TryRemoveFinalizer_Call) Run(run func(ctx context.Context, obj client.Object, finalizer string)) *MockControllerHelper_TryRemoveFinalizer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 client.Object
		if args[1] != nil {
			arg1 = args[1].(client.Object)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockControllerHelper_TryRemoveFinalizer_Call) Return(err error) *MockControllerHelper_TryRemoveFinalizer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockControllerHelper_TryRemoveFinalizer_Call) RunAndReturn(run func(ctx context.Context, obj client.Object, finalizer string) error) *MockControllerHelper_TryRemoveFinalizer_Call {
	_c.Call.Return(run)
	return _c
}

// TryToDelete provides a mock function for the type MockControllerHelper
func (_mock *MockControllerHelper) TryToDelete(ctx context.Context, obj client.Object, terminator helper.Terminator, finalizer string) (bool, error) {
	ret := _mock.Called(ctx, obj, terminator, finalizer)

	if len(ret) == 0 {
		panic("no return value specified for TryToDelete")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, client.Object, helper.Terminator, string) (bool, error)); ok {
		return returnFunc(ctx, obj, terminator, finalizer)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, client.Object, helper.Terminator, string) bool); ok {
		r0 = returnFunc(ctx, obj, terminator, finalizer)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, client.Object, helper.Terminator, string) error); ok {
		r1 = returnFunc(ctx, obj, terminator, finalizer)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockControllerHelper_TryToDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TryToDelete'
type MockControllerHelper_TryToDelete_Call struct {
	*mock.Call
}

// TryToDelete is a helper method to define mock.On call
//   - ctx context.Context
//   - obj client.Object
//   - terminator helper.Terminator
//   - finalizer string
func (_e *MockControllerHelper_Expecter) TryToDelete(ctx interface{}, obj interface{}, terminator interface{}, finalizer interface{}) *MockControllerHelper_TryToDelete_Call {
	return &MockControllerHelper_TryToDelete_Call{Call: _e.mock.On("TryToDelete", ctx, obj, terminator, finalizer)}
}

func (_c *MockControllerHelper_TryToDelete_Call) Run(run func(ctx context.Context, obj client.Object, terminator helper.Terminator, finalizer string)) *MockControllerHelper_TryToDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 client.Object
		if args[1] != nil {
			arg1 = args[1].(client.Object)
		}
		var arg2 helper.Terminator
		if args[2] != nil {
			arg2 = args[2].(helper.Terminator)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockControllerHelper_TryToDelete_Call) Return(isDeleted bool, resultErr error) *MockControllerHelper_TryToDelete_Call {
	_c.Call.Return(isDeleted, resultErr)
	return _c
}

func (_c *MockControllerHelper_TryToDelete_Call) RunAndReturn(run func(ctx context.Context, obj client.Object, terminator helper.Terminator, finalizer string) (bool, error)) *MockControllerHelper_TryToDelete_Call {
	_c.Call.Return(run)
	return _c
}
