// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/epam/edp-keycloak-operator/api/v1"
	"github.com/epam/edp-keycloak-operator/api/v1alpha1"
	"github.com/epam/edp-keycloak-operator/internal/controller/helper"
	"github.com/epam/edp-keycloak-operator/pkg/client/keycloakapi"
	mock "github.com/stretchr/testify/mock"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

// NewMockControllerHelper creates a new instance of MockControllerHelper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockControllerHelper(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockControllerHelper {
	mock := &MockControllerHelper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockControllerHelper is an autogenerated mock type for the ControllerHelper type
type MockControllerHelper struct {
	mock.Mock
}

type MockControllerHelper_Expecter struct {
	mock *mock.Mock
}

func (_m *MockControllerHelper) EXPECT() *MockControllerHelper_Expecter {
	return &MockControllerHelper_Expecter{mock: &_m.Mock}
}

// CreateKeycloakClientFromClusterKeycloak provides a mock function for the type MockControllerHelper
func (_mock *MockControllerHelper) CreateKeycloakClientFromClusterKeycloak(ctx context.Context, clusterKeycloak *v1alpha1.ClusterKeycloak) (*keycloakapi.KeycloakClient, error) {
	ret := _mock.Called(ctx, clusterKeycloak)

	if len(ret) == 0 {
		panic("no return value specified for CreateKeycloakClientFromClusterKeycloak")
	}

	var r0 *keycloakapi.KeycloakClient
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1alpha1.ClusterKeycloak) (*keycloakapi.KeycloakClient, error)); ok {
		return returnFunc(ctx, clusterKeycloak)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1alpha1.ClusterKeycloak) *keycloakapi.KeycloakClient); ok {
		r0 = returnFunc(ctx, clusterKeycloak)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*keycloakapi.KeycloakClient)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1alpha1.ClusterKeycloak) error); ok {
		r1 = returnFunc(ctx, clusterKeycloak)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockControllerHelper_CreateKeycloakClientFromClusterKeycloak_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateKeycloakClientFromClusterKeycloak'
type MockControllerHelper_CreateKeycloakClientFromClusterKeycloak_Call struct {
	*mock.Call
}

// CreateKeycloakClientFromClusterKeycloak is a helper method to define mock.On call
//   - ctx context.Context
//   - clusterKeycloak *v1alpha1.ClusterKeycloak
func (_e *MockControllerHelper_Expecter) CreateKeycloakClientFromClusterKeycloak(ctx interface{}, clusterKeycloak interface{}) *MockControllerHelper_CreateKeycloakClientFromClusterKeycloak_Call {
	return &MockControllerHelper_CreateKeycloakClientFromClusterKeycloak_Call{Call: _e.mock.On("CreateKeycloakClientFromClusterKeycloak", ctx, clusterKeycloak)}
}

func (_c *MockControllerHelper_CreateKeycloakClientFromClusterKeycloak_Call) Run(run func(ctx context.Context, clusterKeycloak *v1alpha1.ClusterKeycloak)) *MockControllerHelper_CreateKeycloakClientFromClusterKeycloak_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1alpha1.ClusterKeycloak
		if args[1] != nil {
			arg1 = args[1].(*v1alpha1.ClusterKeycloak)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockControllerHelper_CreateKeycloakClientFromClusterKeycloak_Call) Return(keycloakClient *keycloakapi.KeycloakClient, err error) *MockControllerHelper_CreateKeycloakClientFromClusterKeycloak_Call {
	_c.Call.Return(keycloakClient, err)
	return _c
}

func (_c *MockControllerHelper_CreateKeycloakClientFromClusterKeycloak_Call) RunAndReturn(run func(ctx context.Context, clusterKeycloak *v1alpha1.ClusterKeycloak) (*keycloakapi.KeycloakClient, error)) *MockControllerHelper_CreateKeycloakClientFromClusterKeycloak_Call {
	_c.Call.Return(run)
	return _c
}

// CreateKeycloakClientFromClusterRealm provides a mock function for the type MockControllerHelper
func (_mock *MockControllerHelper) CreateKeycloakClientFromClusterRealm(ctx context.Context, realm *v1alpha1.ClusterKeycloakRealm) (*keycloakapi.KeycloakClient, error) {
	ret := _mock.Called(ctx, realm)

	if len(ret) == 0 {
		panic("no return value specified for CreateKeycloakClientFromClusterRealm")
	}

	var r0 *keycloakapi.KeycloakClient
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1alpha1.ClusterKeycloakRealm) (*keycloakapi.KeycloakClient, error)); ok {
		return returnFunc(ctx, realm)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1alpha1.ClusterKeycloakRealm) *keycloakapi.KeycloakClient); ok {
		r0 = returnFunc(ctx, realm)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*keycloakapi.KeycloakClient)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1alpha1.ClusterKeycloakRealm) error); ok {
		r1 = returnFunc(ctx, realm)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockControllerHelper_CreateKeycloakClientFromClusterRealm_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateKeycloakClientFromClusterRealm'
type MockControllerHelper_CreateKeycloakClientFromClusterRealm_Call struct {
	*mock.Call
}

// CreateKeycloakClientFromClusterRealm is a helper method to define mock.On call
//   - ctx context.Context
//   - realm *v1alpha1.ClusterKeycloakRealm
func (_e *MockControllerHelper_Expecter) CreateKeycloakClientFromClusterRealm(ctx interface{}, realm interface{}) *MockControllerHelper_CreateKeycloakClientFromClusterRealm_Call {
	return &MockControllerHelper_CreateKeycloakClientFromClusterRealm_Call{Call: _e.mock.On("CreateKeycloakClientFromClusterRealm", ctx, realm)}
}

func (_c *MockControllerHelper_CreateKeycloakClientFromClusterRealm_Call) Run(run func(ctx context.Context, realm *v1alpha1.ClusterKeycloakRealm)) *MockControllerHelper_CreateKeycloakClientFromClusterRealm_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1alpha1.ClusterKeycloakRealm
		if args[1] != nil {
			arg1 = args[1].(*v1alpha1.ClusterKeycloakRealm)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockControllerHelper_CreateKeycloakClientFromClusterRealm_Call) Return(keycloakClient *keycloakapi.KeycloakClient, err error) *MockControllerHelper_CreateKeycloakClientFromClusterRealm_Call {
	_c.Call.Return(keycloakClient, err)
	return _c
}

func (_c *MockControllerHelper_CreateKeycloakClientFromClusterRealm_Call) RunAndReturn(run func(ctx context.Context, realm *v1alpha1.ClusterKeycloakRealm) (*keycloakapi.KeycloakClient, error)) *MockControllerHelper_CreateKeycloakClientFromClusterRealm_Call {
	_c.Call.Return(run)
	return _c
}

// CreateKeycloakClientFromKeycloak provides a mock function for the type MockControllerHelper
func (_mock *MockControllerHelper) CreateKeycloakClientFromKeycloak(ctx context.Context, kc *v1.Keycloak) (*keycloakapi.KeycloakClient, error) {
	ret := _mock.Called(ctx, kc)

	if len(ret) == 0 {
		panic("no return value specified for CreateKeycloakClientFromKeycloak")
	}

	var r0 *keycloakapi.KeycloakClient
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.Keycloak) (*keycloakapi.KeycloakClient, error)); ok {
		return returnFunc(ctx, kc)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.Keycloak) *keycloakapi.KeycloakClient); ok {
		r0 = returnFunc(ctx, kc)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*keycloakapi.KeycloakClient)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.Keycloak) error); ok {
		r1 = returnFunc(ctx, kc)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockControllerHelper_CreateKeycloakClientFromKeycloak_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateKeycloakClientFromKeycloak'
type MockControllerHelper_CreateKeycloakClientFromKeycloak_Call struct {
	*mock.Call
}

// CreateKeycloakClientFromKeycloak is a helper method to define mock.On call
//   - ctx context.Context
//   - kc *v1.Keycloak
func (_e *MockControllerHelper_Expecter) CreateKeycloakClientFromKeycloak(ctx interface{}, kc interface{}) *MockControllerHelper_CreateKeycloakClientFromKeycloak_Call {
	return &MockControllerHelper_CreateKeycloakClientFromKeycloak_Call{Call: _e.mock.On("CreateKeycloakClientFromKeycloak", ctx, kc)}
}

func (_c *MockControllerHelper_CreateKeycloakClientFromKeycloak_Call) Run(run func(ctx context.Context, kc *v1.Keycloak)) *MockControllerHelper_CreateKeycloakClientFromKeycloak_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.Keycloak
		if args[1] != nil {
			arg1 = args[1].(*v1.Keycloak)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockControllerHelper_CreateKeycloakClientFromKeycloak_Call) Return(keycloakClient *keycloakapi.KeycloakClient, err error) *MockControllerHelper_CreateKeycloakClientFromKeycloak_Call {
	_c.Call.Return(keycloakClient, err)
	return _c
}

func (_c *MockControllerHelper_CreateKeycloakClientFromKeycloak_Call) RunAndReturn(run func(ctx context.Context, kc *v1.Keycloak) (*keycloakapi.KeycloakClient, error)) *MockControllerHelper_CreateKeycloakClientFromKeycloak_Call {
	_c.Call.Return(run)
	return _c
}

// CreateKeycloakClientFromRealm provides a mock function for the type MockControllerHelper
func (_mock *MockControllerHelper) CreateKeycloakClientFromRealm(ctx context.Context, realm *v1.KeycloakRealm) (*keycloakapi.KeycloakClient, error) {
	ret := _mock.Called(ctx, realm)

	if len(ret) == 0 {
		panic("no return value specified for CreateKeycloakClientFromRealm")
	}

	var r0 *keycloakapi.KeycloakClient
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.KeycloakRealm) (*keycloakapi.KeycloakClient, error)); ok {
		return returnFunc(ctx, realm)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.KeycloakRealm) *keycloakapi.KeycloakClient); ok {
		r0 = returnFunc(ctx, realm)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*keycloakapi.KeycloakClient)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.KeycloakRealm) error); ok {
		r1 = returnFunc(ctx, realm)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockControllerHelper_CreateKeycloakClientFromRealm_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateKeycloakClientFromRealm'
type MockControllerHelper_CreateKeycloakClientFromRealm_Call struct {
	*mock.Call
}

// CreateKeycloakClientFromRealm is a helper method to define mock.On call
//   - ctx context.Context
//   - realm *v1.KeycloakRealm
func (_e *MockControllerHelper_Expecter) CreateKeycloakClientFromRealm(ctx interface{}, realm interface{}) *MockControllerHelper_CreateKeycloakClientFromRealm_Call {
	return &MockControllerHelper_CreateKeycloakClientFromRealm_Call{Call: _e.mock.On("CreateKeycloakClientFromRealm", ctx, realm)}
}

func (_c *MockControllerHelper_CreateKeycloakClientFromRealm_Call) Run(run func(ctx context.Context, realm *v1.KeycloakRealm)) *MockControllerHelper_CreateKeycloakClientFromRealm_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.KeycloakRealm
		if args[1] != nil {
			arg1 = args[1].(*v1.KeycloakRealm)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockControllerHelper_CreateKeycloakClientFromRealm_Call) Return(keycloakClient *keycloakapi.KeycloakClient, err error) *MockControllerHelper_CreateKeycloakClientFromRealm_Call {
	_c.Call.Return(keycloakClient, err)
	return _c
}

func (_c *MockControllerHelper_CreateKeycloakClientFromRealm_Call) RunAndReturn(run func(ctx context.Context, realm *v1.KeycloakRealm) (*keycloakapi.KeycloakClient, error)) *MockControllerHelper_CreateKeycloakClientFromRealm_Call {
	_c.Call.Return(run)
	return _c
}

// CreateKeycloakClientFromRealmRef provides a mock function for the type MockControllerHelper
func (_mock *MockControllerHelper) CreateKeycloakClientFromRealmRef(ctx context.Context, object helper.ObjectWithRealmRef) (*keycloakapi.KeycloakClient, error) {
	ret := _mock.Called(ctx, object)

	if len(ret) == 0 {
		panic("no return value specified for CreateKeycloakClientFromRealmRef")
	}

	var r0 *keycloakapi.KeycloakClient
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, helper.ObjectWithRealmRef) (*keycloakapi.KeycloakClient, error)); ok {
		return returnFunc(ctx, object)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, helper.ObjectWithRealmRef) *keycloakapi.KeycloakClient); ok {
		r0 = returnFunc(ctx, object)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*keycloakapi.KeycloakClient)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, helper.ObjectWithRealmRef) error); ok {
		r1 = returnFunc(ctx, object)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockControllerHelper_CreateKeycloakClientFromRealmRef_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateKeycloakClientFromRealmRef'
type MockControllerHelper_CreateKeycloakClientFromRealmRef_Call struct {
	*mock.Call
}

// CreateKeycloakClientFromRealmRef is a helper method to define mock.On call
//   - ctx context.Context
//   - object helper.ObjectWithRealmRef
func (_e *MockControllerHelper_Expecter) CreateKeycloakClientFromRealmRef(ctx interface{}, object interface{}) *MockControllerHelper_CreateKeycloakClientFromRealmRef_Call {
	return &MockControllerHelper_CreateKeycloakClientFromRealmRef_Call{Call: _e.mock.On("CreateKeycloakClientFromRealmRef", ctx, object)}
}

func (_c *MockControllerHelper_CreateKeycloakClientFromRealmRef_Call) Run(run func(ctx context.Context, object helper.ObjectWithRealmRef)) *MockControllerHelper_CreateKeycloakClientFromRealmRef_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 helper.ObjectWithRealmRef
		if args[1] != nil {
			arg1 = args[1].(helper.ObjectWithRealmRef)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockControllerHelper_CreateKeycloakClientFromRealmRef_Call) Return(keycloakClient *keycloakapi.KeycloakClient, err error) *MockControllerHelper_CreateKeycloakClientFromRealmRef_Call {
	_c.Call.Return(keycloakClient, err)
	return _c
}

func (_c *MockControllerHelper_CreateKeycloakClientFromRealmRef_Call) RunAndReturn(run func(ctx context.Context, object helper.ObjectWithRealmRef) (*keycloakapi.KeycloakClient, error)) *MockControllerHelper_CreateKeycloakClientFromRealmRef_Call {
	_c.Call.Return(run)
	return _c
}

// GetRealmNameFromRef provides a mock function for the type MockControllerHelper
func (_mock *MockControllerHelper) GetRealmNameFromRef(ctx context.Context, object helper.ObjectWithRealmRef) (string, error) {
	ret := _mock.Called(ctx, object)

	if len(ret) == 0 {
		panic("no return value specified for GetRealmNameFromRef")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, helper.ObjectWithRealmRef) (string, error)); ok {
		return returnFunc(ctx, object)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, helper.ObjectWithRealmRef) string); ok {
		r0 = returnFunc(ctx, object)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, helper.ObjectWithRealmRef) error); ok {
		r1 = returnFunc(ctx, object)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockControllerHelper_GetRealmNameFromRef_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRealmNameFromRef'
type MockControllerHelper_GetRealmNameFromRef_Call struct {
	*mock.Call
}

// GetRealmNameFromRef is a helper method to define mock.On call
//   - ctx context.Context
//   - object helper.ObjectWithRealmRef
func (_e *MockControllerHelper_Expecter) GetRealmNameFromRef(ctx interface{}, object interface{}) *MockControllerHelper_GetRealmNameFromRef_Call {
	return &MockControllerHelper_GetRealmNameFromRef_Call{Call: _e.mock.On("GetRealmNameFromRef", ctx, object)}
}

func (_c *MockControllerHelper_GetRealmNameFromRef_Call) Run(run func(ctx context.Context, object helper.ObjectWithRealmRef)) *MockControllerHelper_GetRealmNameFromRef_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 helper.ObjectWithRealmRef
		if args[1] != nil {
			arg1 = args[1].(helper.ObjectWithRealmRef)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockControllerHelper_GetRealmNameFromRef_Call) Return(s string, err error) *MockControllerHelper_GetRealmNameFromRef_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockControllerHelper_GetRealmNameFromRef_Call) RunAndReturn(run func(ctx context.Context, object helper.ObjectWithRealmRef) (string, error)) *MockControllerHelper_GetRealmNameFromRef_Call {
	_c.Call.Return(run)
	return _c
}

// SetFailureCount provides a mock function for the type MockControllerHelper
func (_mock *MockControllerHelper) SetFailureCount(fc helper.FailureCountable) time.Duration {
	ret := _mock.Called(fc)

	if len(ret) == 0 {
		panic("no return value specified for SetFailureCount")
	}

	var r0 time.Duration
	if returnFunc, ok := ret.Get(0).(func(helper.FailureCountable) time.Duration); ok {
		r0 = returnFunc(fc)
	} else {
		r0 = ret.Get(0).(time.Duration)
	}
	return r0
}

// MockControllerHelper_SetFailureCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetFailureCount'
type MockControllerHelper_SetFailureCount_Call struct {
	*mock.Call
}

// SetFailureCount is a helper method to define mock.On call
//   - fc helper.FailureCountable
func (_e *MockControllerHelper_Expecter) SetFailureCount(fc interface{}) *MockControllerHelper_SetFailureCount_Call {
	return &MockControllerHelper_SetFailureCount_Call{Call: _e.mock.On("SetFailureCount", fc)}
}

func (_c *MockControllerHelper_SetFailureCount_Call) Run(run func(fc helper.FailureCountable)) *MockControllerHelper_SetFailureCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 helper.FailureCountable
		if args[0] != nil {
			arg0 = args[0].(helper.FailureCountable)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockControllerHelper_SetFailureCount_Call) Return(duration time.Duration) *MockControllerHelper_SetFailureCount_Call {
	_c.Call.Return(duration)
	return _c
}

func (_c *MockControllerHelper_SetFailureCount_Call) RunAndReturn(run func(fc helper.FailureCountable) time.Duration) *MockControllerHelper_SetFailureCount_Call {
	_c.Call.Return(run)
	return _c
}

// SetKeycloakOwnerRef provides a mock function for the type MockControllerHelper
func (_mock *MockControllerHelper) SetKeycloakOwnerRef(ctx context.Context, object helper.ObjectWithKeycloakRef) error {
	ret := _mock.Called(ctx, object)

	if len(ret) == 0 {
		panic("no return value specified for SetKeycloakOwnerRef")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, helper.ObjectWithKeycloakRef) error); ok {
		r0 = returnFunc(ctx, object)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockControllerHelper_SetKeycloakOwnerRef_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetKeycloakOwnerRef'
type MockControllerHelper_SetKeycloakOwnerRef_Call struct {
	*mock.Call
}

// SetKeycloakOwnerRef is a helper method to define mock.On call
//   - ctx context.Context
//   - object helper.ObjectWithKeycloakRef
func (_e *MockControllerHelper_Expecter) SetKeycloakOwnerRef(ctx interface{}, object interface{}) *MockControllerHelper_SetKeycloakOwnerRef_Call {
	return &MockControllerHelper_SetKeycloakOwnerRef_Call{Call: _e.mock.On("SetKeycloakOwnerRef", ctx, object)}
}

func (_c *MockControllerHelper_SetKeycloakOwnerRef_Call) Run(run func(ctx context.Context, object helper.ObjectWithKeycloakRef)) *MockControllerHelper_SetKeycloakOwnerRef_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 helper.ObjectWithKeycloakRef
		if args[1] != nil {
			arg1 = args[1].(helper.ObjectWithKeycloakRef)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockControllerHelper_SetKeycloakOwnerRef_Call) Return(err error) *MockControllerHelper_SetKeycloakOwnerRef_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockControllerHelper_SetKeycloakOwnerRef_Call) RunAndReturn(run func(ctx context.Context, object helper.ObjectWithKeycloakRef) error) *MockControllerHelper_SetKeycloakOwnerRef_Call {
	_c.Call.Return(run)
	return _c
}

// SetRealmOwnerRef provides a mock function for the type MockControllerHelper
func (_mock *MockControllerHelper) SetRealmOwnerRef(ctx context.Context, object helper.ObjectWithRealmRef) error {
	ret := _mock.Called(ctx, object)

	if len(ret) == 0 {
		panic("no return value specified for SetRealmOwnerRef")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, helper.ObjectWithRealmRef) error); ok {
		r0 = returnFunc(ctx, object)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockControllerHelper_SetRealmOwnerRef_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetRealmOwnerRef'
type MockControllerHelper_SetRealmOwnerRef_Call struct {
	*mock.Call
}

// SetRealmOwnerRef is a helper method to define mock.On call
//   - ctx context.Context
//   - object helper.ObjectWithRealmRef
func (_e *MockControllerHelper_Expecter) SetRealmOwnerRef(ctx interface{}, object interface{}) *MockControllerHelper_SetRealmOwnerRef_Call {
	return &MockControllerHelper_SetRealmOwnerRef_Call{Call: _e.mock.On("SetRealmOwnerRef", ctx, object)}
}

func (_c *MockControllerHelper_SetRealmOwnerRef_Call) Run(run func(ctx context.Context, object helper.ObjectWithRealmRef)) *MockControllerHelper_SetRealmOwnerRef_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 helper.ObjectWithRealmRef
		if args[1] != nil {
			arg1 = args[1].(helper.ObjectWithRealmRef)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockControllerHelper_SetRealmOwnerRef_Call) Return(err error) *MockControllerHelper_SetRealmOwnerRef_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockControllerHelper_SetRealmOwnerRef_Call) RunAndReturn(run func(ctx context.Context, object helper.ObjectWithRealmRef) error) *MockControllerHelper_SetRealmOwnerRef_Call {
	_c.Call.Return(run)
	return _c
}

// TryRemoveFinalizer provides a mock function for the type MockControllerHelper
func (_mock *MockControllerHelper) TryRemoveFinalizer(ctx context.Context, obj client.Object, finalizer string) error {
	ret := _mock.Called(ctx, obj, finalizer)

	if len(ret) == 0 {
		panic("no return value specified for TryRemoveFinalizer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, client.Object, string) error); ok {
		r0 = returnFunc(ctx, obj, finalizer)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockControllerHelper_TryRemoveFinalizer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TryRemoveFinalizer'
type MockControllerHelper_TryRemoveFinalizer_Call struct {
	*mock.Call
}

// TryRemoveFinalizer is a helper method to define mock.On call
//   - ctx context.Context
//   - obj client.Object
//   - finalizer string
func (_e *MockControllerHelper_Expecter) TryRemoveFinalizer(ctx interface{}, obj interface{}, finalizer interface{}) *MockControllerHelper_TryRemoveFinalizer_Call {
	return &MockControllerHelper_TryRemoveFinalizer_Call{Call: _e.mock.On("TryRemoveFinalizer", ctx, obj, finalizer)}
}

func (_c *MockControllerHelper_TryRemoveFinalizer_Call) Run(run func(ctx context.Context, obj client.Object, finalizer string)) *MockControllerHelper_TryRemoveFinalizer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 client.Object
		if args[1] != nil {
			arg1 = args[1].(client.Object)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockControllerHelper_TryRemoveFinalizer_Call) Return(err error) *MockControllerHelper_TryRemoveFinalizer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockControllerHelper_TryRemoveFinalizer_Call) RunAndReturn(run func(ctx context.Context, obj client.Object, finalizer string) error) *MockControllerHelper_TryRemoveFinalizer_Call {
	_c.Call.Return(run)
	return _c
}

// TryToDelete provides a mock function for the type MockControllerHelper
func (_mock *MockControllerHelper) TryToDelete(ctx context.Context, obj client.Object, terminator helper.Terminator, finalizer string) (bool, error) {
	ret := _mock.Called(ctx, obj, terminator, finalizer)

	if len(ret) == 0 {
		panic("no return value specified for TryToDelete")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, client.Object, helper.Terminator, string) (bool, error)); ok {
		return returnFunc(ctx, obj, terminator, finalizer)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, client.Object, helper.Terminator, string) bool); ok {
		r0 = returnFunc(ctx, obj, terminator, finalizer)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, client.Object, helper.Terminator, string) error); ok {
		r1 = returnFunc(ctx, obj, terminator, finalizer)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockControllerHelper_TryToDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TryToDelete'
type MockControllerHelper_TryToDelete_Call struct {
	*mock.Call
}

// TryToDelete is a helper method to define mock.On call
//   - ctx context.Context
//   - obj client.Object
//   - terminator helper.Terminator
//   - finalizer string
func (_e *MockControllerHelper_Expecter) TryToDelete(ctx interface{}, obj interface{}, terminator interface{}, finalizer interface{}) *MockControllerHelper_TryToDelete_Call {
	return &MockControllerHelper_TryToDelete_Call{Call: _e.mock.On("TryToDelete", ctx, obj, terminator, finalizer)}
}

func (_c *MockControllerHelper_TryToDelete_Call) Run(run func(ctx context.Context, obj client.Object, terminator helper.Terminator, finalizer string)) *MockControllerHelper_TryToDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 client.Object
		if args[1] != nil {
			arg1 = args[1].(client.Object)
		}
		var arg2 helper.Terminator
		if args[2] != nil {
			arg2 = args[2].(helper.Terminator)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockControllerHelper_TryToDelete_Call) Return(isDeleted bool, resultErr error) *MockControllerHelper_TryToDelete_Call {
	_c.Call.Return(isDeleted, resultErr)
	return _c
}

func (_c *MockControllerHelper_TryToDelete_Call) RunAndReturn(run func(ctx context.Context, obj client.Object, terminator helper.Terminator, finalizer string) (bool, error)) *MockControllerHelper_TryToDelete_Call {
	_c.Call.Return(run)
	return _c
}
