{{- if .Values.enableWebhooks }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "keycloak-operator.labels" . | nindent 4 }}
  name: edp-{{ .Release.Namespace }}-webhook-clusterrole
rules:
- apiGroups:
  - v1.edp.epam.com
  resources:
  - keycloakrealms
  verbs:
  - get
  - list
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "keycloak-operator.labels" . | nindent 4 }}
  name: edp-{{ .Release.Namespace }}-webhook-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edp-{{ .Release.Namespace }}-webhook-clusterrole
subjects:
  - kind: ServiceAccount
    name: edp-{{ .Values.name }}
    namespace: {{ .Release.Namespace }}
{{- end }}
