apiVersion: v2
description: A Helm chart for KubeRocketCI Keycloak Operator
home: https://docs.kuberocketci.io/
name: keycloak-operator
type: application
version: 1.35.0
appVersion: 1.35.0
icon: https://docs.kuberocketci.io/img/logo.svg
keywords:
  - authentication
  - authorization
  - edp
  - idp
  - keycloak
  - oauth
  - oidc
  - operator
  - saml
  - sso
maintainers:
  - name: epmd-edp
    email: SupportEPMD-EDP@epam.com
    url: https://solutionshub.epam.com/solution/kuberocketci
  - name: sergk
    url: https://github.com/SergK
sources:
  - https://github.com/epam/edp-keycloak-operator
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/operator: "true"
  artifacthub.io/images: |
    - name: keycloak-operator:1.35.0
      image: epamedp/keycloak-operator:1.35.0
  artifacthub.io/operatorCapabilities: Deep Insights
  artifacthub.io/crds: |
    - kind: Keycloak
      version: v1.edp.epam.com/v1
      name: keycloak
      displayName: keycloak
      description: Keycloak instance baseline configuration
    - kind: ClusterKeycloak
      version: v1.edp.epam.com/v1alpha1
      name: clusterkeycloak
      displayName: clusterkeycloak
      description: Keycloak instance baseline configuration
    - kind: ClusterKeycloakRealm
      version: v1.edp.epam.com/v1alpha1
      name: clusterkeycloakrealm
      displayName: ClusterKeycloakRealm
      description: Cluster-scoped Keycloak Realm Management
    - kind: KeycloakOrganization
      version: v1.edp.epam.com/v1alpha1
      name: keycloakorganization
      displayName: KeycloakOrganization
      description: Keycloak Organization Management
    - kind: KeycloakAuthFlow
      version: v1.edp.epam.com/v1
      name: keycloakauthflows
      displayName: keycloakauthflows
      description: Keycloak AuthFlow Management
    - kind: KeycloakClient
      version: v1.edp.epam.com/v1
      name: keycloakpermissiontemplate
      displayName: KeycloakClient
      description: Keycloak client Management
    - kind: KeycloakClientScope
      version: v1.edp.epam.com/v1
      name: keycloakclientscope
      displayName: KeycloakClientScope
      description: Keycloak Client Scope Management
    - kind: KeycloakRealm
      version: v1.edp.epam.com/v1
      name: keycloakrealm
      displayName: KeycloakRealm
      description: Keycloak Realm Management
    - kind: KeycloakRealmComponent
      version: v1.edp.epam.com/v1
      name: keycloakrealmcomponent
      displayName: KeycloakRealmComponent
      description: Keycloak Realm Component Management
    - kind: KeycloakRealmGroup
      version: v1.edp.epam.com/v1
      name: keycloakrealmgroup
      displayName: KeycloakRealmGroup
      description: Keycloak Realm Group Management
    - kind: KeycloakRealmIdentityProvider
      version: v1.edp.epam.com/v1
      name: keycloakrealmidentityprovider
      displayName: KeycloakRealmIdentityProvider
      description: Keycloak Realm Identity Provider Management
    - kind: KeycloakRealmRole
      version: v1.edp.epam.com/v1
      name: keycloakrealmrole
      displayName: KeycloakRealmRole
      description: Keycloak Realm Role Management
    - kind: KeycloakRealmRoleBatch
      version: v1.edp.epam.com/v1
      name: keycloakrealmrolebatch
      displayName: KeycloakRealmRoleBatch
      description: Keycloak Realm Role Management in a batch mode
    - kind: KeycloakRealmUser
      version: v1.edp.epam.com/v1
      name: keycloakrealmuser
      displayName: KeycloakRealmUser
      description: Keycloak Realm User Management
  artifacthub.io/crdsExamples: |
    - apiVersion: v1.edp.epam.com/v1
      kind: Keycloak
      metadata:
        name: keycloak-sample
      spec:
        secret: keycloak-access
        url: https://keycloak.example.com
    - apiVersion: v1.edp.epam.com/v1
      kind: KeycloakRealm
      metadata:
        name: keycloakrealm-sample
      spec:
        realmName: realm-sample
        keycloakRef:
          name: keycloak-sample
          kind: Keycloak
        passwordPolicy:
          - type: "forceExpiredPasswordChange"
            value: "365"
          - type: "length"
            value: "8"
        realmEventConfig:
          adminEventsDetailsEnabled: false
          adminEventsEnabled: true
          enabledEventTypes:
            - UPDATE_CONSENT_ERROR
            - CLIENT_LOGIN
          eventsEnabled: true
          eventsExpiration: 15000
          eventsListeners:
            - jboss-logging
        login:
          userRegistration: true
          forgotPassword: true
          rememberMe: true
          emailAsUsername: false
          loginWithEmail: true
          duplicateEmails: false
          verifyEmail: true
          editUsername: false
    - apiVersion: v1.edp.epam.com/v1
      kind: KeycloakClient
      metadata:
        name: keycloakclient-sample
      spec:
        realmRef:
          name: keycloakrealm-sample
          kind: KeycloakRealm
        advancedProtocolMappers: true
        clientId: argocd
        directAccess: true
        public: false
        secret: $client-secret-name:client-secret-key
        webUrl: https://argocd.example.com
        defaultClientScopes:
          - argocd_groups
    - apiVersion: v1.edp.epam.com/v1
      kind: KeycloakClientScope
      metadata:
        name: keycloakclientscope-sample
      spec:
        name: groups
        realmRef:
          name: keycloakrealm-sample
          kind: KeycloakRealm
        description: "Group Membership"
        type: default
        protocol: openid-connect
        protocolMappers:
          - name: groups
            protocol: openid-connect
            protocolMapper: "oidc-group-membership-mapper"
            config:
              "access.token.claim": "true"
              "claim.name": "groups"
              "full.path": "false"
              "id.token.claim": "true"
              "userinfo.token.claim": "true"
    - apiVersion: v1.edp.epam.com/v1
      kind: KeycloakRealmGroup
      metadata:
        name: keycloakrealmgroup-sample
      spec:
        realmRef:
          name: keycloakrealm-sample
          kind: KeycloakRealm
        name: ArgoCDAdmins
    - apiVersion: v1.edp.epam.com/v1
      kind: KeycloakAuthFlow
      metadata:
        name: keycloakauthflow-sample
      spec:
        realmRef:
          name: keycloakrealm-sample
          kind: KeycloakRealm
        alias: MyBrowser
        description: browser with idp
        providerId: basic-flow
        topLevel: true
        builtIn: false
        authenticationExecutions:
          - authenticator: "auth-cookie"
            priority: 0
            requirement: "ALTERNATIVE"
          - authenticator: "identity-provider-redirector"
            priority: 1
            requirement: "ALTERNATIVE"
            authenticatorConfig:
              alias: my-alias
              config:
                "defaultProvider": "my-alias"
    - apiVersion: v1.edp.epam.com/v1
      kind: KeycloakRealmComponent
      metadata:
        name: component-sample
      spec:
        realmRef:
          name: keycloakrealm-sample
          kind: KeycloakRealm
        name: cr-kerb-test
        providerId: kerberos
        providerType: "org.keycloak.storage.UserStorageProvider"
        config:
          allowPasswordAuthentication: ["true"]
          cachePolicy: ["EVICT_WEEKLY"]
          debug: ["true"]
          editMode: ["READ_ONLY"]
          enabled: ["true"]
          evictionDay: ["3"]
          evictionHour: ["5"]
          evictionMinute: ["7"]
          kerberosRealm: ["test-realm"]
          keyTab: ["test-key-tab"]
          priority: ["0"]
          serverPrincipal: ["srv-principal-test"]
          updateProfileFirstLogin: ["true"]
    - apiVersion: v1.edp.epam.com/v1
      kind: KeycloakRealmIdentityProvider
      metadata:
        name: keycloakrealmidentityprovider-sample
      spec:
        realmRef:
          name: keycloakrealm-sample
          kind: KeycloakRealm
        alias: github
        authenticateByDefault: false
        enabled: true
        firstBrokerLoginFlowAlias: "first broker login"
        providerId: "github"
        config:
          clientId: "foo"
          clientSecret: "$idp-secret:secret"
          syncMode: "IMPORT"
          useJwksUrl: "true"
        mappers:
          - name: "test3212"
            identityProviderMapper: "oidc-hardcoded-role-idp-mapper"
            identityProviderAlias: "github"
            config:
              role: "role-tr"
              syncMode: "INHERIT"
          - name: "test-33221"
            identityProviderMapper: "hardcoded-attribute-idp-mapper"
            identityProviderAlias: "github"
            config:
              attribute: "foo"
              "attribute.value": "bar"
              syncMode: "IMPORT"
    - apiVersion: v1.edp.epam.com/v1
      kind: KeycloakRealmUser
      metadata:
        name: keycloakrealmuser-sample
      spec:
        realmRef:
          name: keycloakrealm-sample
          kind: KeycloakRealm
        username: "john.snow13"
        firstName: "John"
        lastName: "Snow"
        email: "john.snow13@example.com"
        enabled: true
        emailVerified: true
        keepResource: true
        passwordSecret:
          name: keycloakrealmuser-sample-password
          key: password
        requiredUserActions:
          - UPDATE_PASSWORD
        attributes:
          foo: "bar"
          baz: "jazz"
    - apiVersion: v1.edp.epam.com/v1
      kind: KeycloakRealmRole
      metadata:
        name: keycloakrealmrole-sample
      spec:
        realmRef:
          name: keycloakrealm-sample
          kind: KeycloakRealm
        name: developer
        description: default developer role
        composite: true
        composites:
          - name: offline_access
    - apiVersion: v1.edp.epam.com/v1
      kind: KeycloakRealmRoleBatch
      metadata:
        name: keycloakrealmrolebatch-sample
      spec:
        realmRef:
          name: keycloakrealm-sample
          kind: KeycloakRealm
        roles:
          - name: developer
            description: default developer role
            composite: true
            isDefault: false
          - name: administrator
            description: default administrator role
            composite: true
            isDefault: false
    - apiVersion: v1.edp.epam.com/v1alpha1
      kind: ClusterKeycloak
      metadata:
        name: clusterkeycloak-sample
      spec:
        secret: keycloak-access
        url: https://keycloak.example.com
    - apiVersion: v1.edp.epam.com/v1alpha1
      kind: ClusterKeycloakRealm
      metadata:
        name: clusterkeycloakrealm-sample
      spec:
        clusterKeycloakRef: clusterkeycloak-sample
        realmName: realm-sample
        login:
          userRegistration: true
          forgotPassword: true
          rememberMe: true
          loginWithEmail: true
          verifyEmail: true
  artifacthub.io/links: |
    - name: KubeRocketCI Documentation
      url: https://docs.kuberocketci.io/
    - name: EPAM SolutionHub
      url: https://solutionshub.epam.com/solution/kuberocketci
  artifacthub.io/changes: |
    - Add frontend url property for realm
    - Allow define KeycloakRealmUser password in Kubernetes secret
    - Update current development version
    - Publish 1.15.0 version on OperatorHub
    - Update current development version
    - Add a description to the Custom Resources fields
