apiVersion: v2
description: A Helm chart for EDP Keycloak Operator
home: https://epam.github.io/edp-install/
name: keycloak-operator
type: application
version: 1.10.1
appVersion: 1.10.1
icon: https://epam.github.io/edp-install/assets/logo.png
keywords:
  - authentication
  - authorization
  - edp
  - idp
  - keycloak
  - oauth
  - oidc
  - operator
  - saml
  - sso
maintainers:
  - name: epmd-edp
    email: SupportEPMD-EDP@epam.com
    url: https://solutionshub.epam.com/solution/epam-delivery-platform
  - name: sergk
    url: https://github.com/SergK
sources:
  - https://github.com/epam/edp-keycloak-operator
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/operator: "true"
  artifacthub.io/images: |
    - name: keycloak-operator:1.10.1
      image: epamedp/keycloak-operator:1.10.1
    - name: keycloak-operator:1.10.0
      image: epamedp/keycloak-operator:1.10.0
    - name: keycloak-operator:1.9.0
      image: epamedp/keycloak-operator:1.9.0
    - name: keycloak-operator:1.8.0
      image: epamedp/keycloak-operator:1.8.0
  artifacthub.io/operatorCapabilities: Auto Pilot
  artifacthub.io/crds: |
    - kind: Keycloak
      version: v1.edp.epam.com/v1alpha1
      name: keycloak
      displayName: keycloak
      description: Keycloak instance baseline configuraion
    - kind: KeycloakAuthFlow
      version: v1.edp.epam.com/v1alpha1
      name: keycloakauthflows
      displayName: keycloakauthflows
      description: Keycloak AuthFlow Management
    - kind: KeycloakClient
      version: v1.edp.epam.com/v1alpha1
      name: keycloakpermissiontemplate
      displayName: KeycloakClient
      description: Keycloak client Management
    - kind: KeycloakClientScope
      version: v1.edp.epam.com/v1alpha1
      name: keycloakclientscope
      displayName: KeycloakClientScope
      description: Keycloak Client Scope Management
    - kind: KeycloakRealm
      version: v1.edp.epam.com/v1alpha1
      name: keycloakrealm
      displayName: KeycloakRealm
      description: Keycloak Realm Management
    - kind: KeycloakRealmComponent
      version: v1.edp.epam.com/v1alpha1
      name: keycloakrealmcomponent
      displayName: KeycloakRealmComponent
      description: Keycloak Realm Component Management
    - kind: KeycloakRealmGroup
      version: v1.edp.epam.com/v1alpha1
      name: keycloakrealmgroup
      displayName: KeycloakRealmGroup
      description: Keycloak Realm Group Management
    - kind: KeycloakRealmIdentityProvider
      version: v1.edp.epam.com/v1alpha1
      name: keycloakrealmidentityprovider
      displayName: KeycloakRealmIdentityProvider
      description: Keycloak Realm Indentity Provider Management
    - kind: KeycloakRealmRole
      version: v1.edp.epam.com/v1alpha1
      name: keycloakrealmrole
      displayName: KeycloakRealmRole
      description: Keycloak Realm Role Management
    - kind: KeycloakRealmRoleBatch
      version: v1.edp.epam.com/v1alpha1
      name: keycloakrealmrolebatch
      displayName: KeycloakRealmRoleBatch
      description: Keycloak Realm Role Management in a batch mode
    - kind: KeycloakRealmUser
      version: v1.edp.epam.com/v1alpha1
      name: keycloakrealmuser
      displayName: KeycloakRealmUser
      description: Keycloak Realm User Management
  artifacthub.io/crdsExamples: |
    - apiVersion: v1.edp.epam.com/v1alpha1
      kind: KeycloakClientScope
      metadata:
      name: groups
      spec:
        name: groups
        realm: main
        description: "Group Membership"
        protocol: openid-connect
        protocolMappers:
          - name: groups
            protocol: openid-connect
            protocolMapper: "oidc-group-membership-mapper"
            config:
              "access.token.claim": "true"
              "claim.name": "groups"
              "full.path": "false"
              "id.token.claim": "true"
              "userinfo.token.claim": "true"
    - apiVersion: v1.edp.epam.com/v1alpha1
      kind: KeycloakClient
      metadata:
        name: argocd
      spec:
        advancedProtocolMappers: true
        audRequired: true
        clientId: agocd
        directAccess: true
        public: false
        secret: ''
        targetRealm: edp-delivery-main
        webUrl: https://argocd.example.com
    - apiVersion: v1.edp.epam.com/v1alpha1
      kind: KeycloakRealmGroup
      metadata:
        name: argocd-admins
      spec:
        name: ArgoCDAdmins
        realm: main
    - apiVersion: v1.edp.epam.com/v1alpha1
      kind: KeycloakAuthFlow
      metadata:
        name: demo-tree
      spec:
        realm: main
        alias: demo-tree
        description: flow tree demo
        providerId: basic-flow
        topLevel: true
        builtIn: false
    - apiVersion: v1.edp.epam.com/v1alpha1
      kind: KeycloakAuthFlow
      metadata:
        name: d1-auth-flow
      spec:
        realm: d2-id-k8s-realm-name
        alias: MyBrowser
        description: browser with idp
        providerId: basic-flow
        topLevel: true
        builtIn: false
        authenticationExecutions:
          - authenticator: "auth-cookie"
            priority: 0
            requirement: "ALTERNATIVE"
          - authenticator: "identity-provider-redirector"
            priority: 1
            requirement: "REQUIRED"
            authenticatorConfig:
              alias: diia
              config:
                "defaultProvider": "oidc"
    - apiVersion: v1.edp.epam.com/v1alpha1
      kind: KeycloakRealmComponent
      metadata:
        name: kerberos-test
      spec:
        realm: d1-id-k8s-realm-name
        name: cr-kerb-test
        providerId: kerberos
        providerType: "org.keycloak.storage.UserStorageProvider"
        config:
          allowPasswordAuthentication: ["true"]
          cachePolicy: ["EVICT_WEEKLY"]
          debug: ["true"]
          editMode: ["READ_ONLY"]
          enabled: ["true"]
          evictionDay: ["3"]
          evictionHour: ["5"]
          evictionMinute: ["7"]
          kerberosRealm: ["test-realm"]
          keyTab: ["test-key-tab"]
          priority: ["0"]
          serverPrincipal: ["srv-principal-test"]
          updateProfileFirstLogin: ["true"]
    - apiVersion: v1.edp.epam.com/v1alpha1
      kind: KeycloakRealmIdentityProvider
      metadata:
        name: instagram-test
      spec:
        realm: d2-id-k8s-realm-name
        alias: instagram
        authenticateByDefault: false
        enabled: true
        firstBrokerLoginFlowAlias: "first broker login"
        providerId: "instagram"
        config:
          clientId: "foo"
          clientSecret: "bar"
          hideOnLoginPage: "true"
          syncMode: "IMPORT"
          useJwksUrl: "true"
        mappers:
          - name: "test3212"
            identityProviderMapper: "oidc-hardcoded-role-idp-mapper"
            identityProviderAlias: "instagram"
            config:
              role: "role-tr"
              syncMode: "INHERIT"
          - name: "test-33221"
            identityProviderMapper: "hardcoded-attribute-idp-mapper"
            identityProviderAlias: "instagram"
            config:
              attribute: "foo"
              "attribute.value": "bar"
              syncMode: "IMPORT"
    - apiVersion: v1.edp.epam.com/v1alpha1
      kind: KeycloakRealm
      metadata:
        name: d2-id-k8s-realm-name
      spec:
        id: d1-id-kc-realm-name
        realmName: d2-id-kc-realm-name
        keycloakOwner: main
        ssoRealmName: openshift
        ssoRealmEnabled: false # new one
        ssoAutoRedirectEnabled: false # new one
        realmEventConfig:
          adminEventsDetailsEnabled: false
          adminEventsEnabled: true
          enabledEventTypes:
            - UPDATE_CONSENT_ERROR
            - CLIENT_LOGIN
          eventsEnabled: true
          eventsExpiration: 15000
          eventsListeners:
            - jboss-logging
    - apiVersion: v1.edp.epam.com/v1alpha1
      kind: KeycloakRealmUser
      metadata:
        name: d1-user-test1
      spec:
        realm: d1-id-k8s-realm-name
        username: "john.snow13"
        firstName: "John"
        lastName: "Snow"
        email: "john.snow13@gmail.com"
        enabled: true
        emailVerified: true
        requiredUserActions:
          - UPDATE_PASSWORD
        attributes:
          foo: "bar"
          baz: "jazz"
  artifacthub.io/links: |
    - name: EDP Documentation
      url: https://epam.github.io/edp-install/
    - name: EPAM SolutionHub
      url: https://solutionshub.epam.com/solution/epam-delivery-platform
