apiVersion: v2
description: A Helm chart for EDP Keycloak Operator
home: https://solutionshub.epam.com/solution/epam-delivery-platform
name: keycloak-operator
type: application
version: 1.10.0-SNAPSHOT
appVersion: 1.10.0-SNAPSHOT
maintainers:
    - name: EPAM EDP Team
sources:
    - https://github.com/epam/edp-keycloak-operator
