global:
  edpName: ""
  platform: "openshift"
  admins:
    - "stub_user_one@example.com"
  developers:
    - "stub_user_one@example.com"

name: keycloak-operator
image:
  name: epamedp/keycloak-operator
  # if not defined then .Chart.AppVersion is used
  version:

resources:
  limits:
    memory: 192Mi
  requests:
    cpu: 50m
    memory: 64Mi

keycloak:
  url: "https://keycloak-keycloak.delivery.aws.main.edp.projects.epam.com"
