{{- if eq .Values.global.platform "openshift" -}}
apiVersion: authorization.openshift.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "keycloak-operator.labels" . | nindent 4 }}
  name: edp-{{ .Values.name }}-{{ .Values.global.edpName }}
rules:
- apiGroups:
    - '*'
  attributeRestrictions: null
  resources:
    - securitycontextconstraints
  verbs:
    - patch
    - update
    - delete
    - get
    - list
    - create
- apiGroups:
    - '*'
  attributeRestrictions: null
  resources:
    - keycloaks
    - keycloaks/finalizers
    - keycloaks/status
    - keycloakclients
    - keycloakclients/finalizers
    - keycloakclients/status
    - keycloakrealms
    - keycloakrealms/finalizers
    - keycloakrealms/status
    - edpcomponents
    - edpcomponents/finalizers
    - edpcomponents/status
  verbs:
     - '*'
{{ end }}
