apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "keycloak-operator.labels" . | nindent 4 }}
  name: edp-{{ .Values.name }}-clusterrole
rules:
- apiGroups:
  - v1.edp.epam.com
  resources:
  - clusterkeycloaks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - v1.edp.epam.com
  resources:
  - clusterkeycloaks/finalizers
  verbs:
  - update
- apiGroups:
  - v1.edp.epam.com
  resources:
  - clusterkeycloaks/status
  verbs:
  - get
  - patch
  - update
