{{- if eq .Values.global.platform "openshift" -}}
apiVersion: authorization.openshift.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.name }}-{{ .Values.global.edpName }}
roleRef:
  name: {{ .Values.name }}-{{ .Values.global.edpName }}-clusterrole
subjects:
  - kind: ServiceAccount
    name: {{ .Values.name }}-edp
    namespace: {{ .Values.global.edpName }}
userNames:
  - system:serviceaccount:{{ .Values.global.edpName }}:{{ .Values.name }}-edp
groupNames: []
{{- end -}}