{{- if eq .Values.global.platform "kubernetes" -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Values.global.edpName }}
  labels:
    {{- include "keycloak-operator.labels" . | nindent 4 }}
  name: edp-{{ .Values.name }}
rules:
- apiGroups:
    - '*'
  resources:
    - keycloaks
    - keycloaks/finalizers
    - keycloaks/status
    - keycloakclients
    - keycloakclients/finalizers
    - keycloakclients/status
    - keycloakrealms
    - keycloakrealms/finalizers
    - keycloakrealms/status
    - edpcomponents
    - edpcomponents/finalizers
    - edpcomponents/status
    - keycloakrealmroles
    - keycloakrealmroles/finalizers
    - keycloakrealmroles/status
    - keycloakrealmrolebatches
    - keycloakrealmrolebatches/finalizers
    - keycloakrealmrolebatches/status
    - keycloakrealmgroups
    - keycloakrealmgroups/finalizers
    - keycloakrealmgroups/status
    - keycloakauthflows
    - keycloakauthflows/finalizers
    - keycloakauthflows/status
    - keycloakrealmusers
    - keycloakrealmusers/finalizers
    - keycloakrealmusers/status
    - keycloakclientscopes/finalizers
    - keycloakclientscopes/status
    - keycloakclientscopes
    - events
  verbs:
     - '*'
- apiGroups:
    - coordination.k8s.io
  resources:
    - leases
  verbs:
    - create
    - get
    - list
    - update
- apiGroups:
    - v1.edp.epam.com
  resources:
    - keycloakrealmcomponents
  verbs:
    - list
    - watch
{{ end }}
