{{- if eq .Values.platform "openshift" -}}
apiVersion: authorization.openshift.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.name }}-admin-{{ .Values.namespace }}
roleRef:
  name: admin
subjects:
  - kind: ServiceAccount
    name: {{ .Values.name }}-edp
    namespace: {{ .Values.namespace }}
userNames:
  - system:serviceaccount:{{ .Values.namespace }}:{{ .Values.name }}-edp
groupNames: []
{{- end -}}