{{- if eq .Values.global.platform "openshift" -}}
apiVersion: authorization.openshift.io/v1
kind: Role
metadata:
  namespace: {{ .Values.global.edpName }}
  labels:
    {{- include "keycloak-operator.labels" . | nindent 4 }}
  name: edp-{{ .Values.name }}
rules:
- apiGroups:
    - '*'
  resources:
    - securitycontextconstraints
  verbs:
    - patch
    - update
    - delete
    - get
    - list
    - create
- apiGroups:
    - '*'
  resources:
    - keycloaks
    - keycloaks/finalizers
    - keycloaks/status
    - keycloakclients
    - keycloakclients/finalizers
    - keycloakclients/status
    - keycloakrealms
    - keycloakrealms/finalizers
    - keycloakrealms/status
    - edpcomponents
    - edpcomponents/finalizers
    - edpcomponents/status
    - keycloakrealmroles
    - keycloakrealmroles/finalizers
    - keycloakrealmroles/status
    - keycloakrealmrolebatches
    - keycloakrealmrolebatches/finalizers
    - keycloakrealmrolebatches/status
    - keycloakrealmgroups
    - keycloakrealmgroups/finalizers
    - keycloakrealmgroups/status
    - keycloakauthflows
    - keycloakauthflows/finalizers
    - keycloakauthflows/status
    - keycloakrealmusers
    - keycloakrealmusers/finalizers
    - keycloakrealmusers/status
    - keycloakclientscopes/finalizers
    - keycloakclientscopes/status
    - keycloakclientscopes
    - events
    - keycloakrealmcomponents
    - keycloakrealmcomponents/finalizers
    - keycloakrealmcomponents/status
    - keycloakrealmidentityproviders
    - keycloakrealmidentityproviders/finalizers
    - keycloakrealmidentityproviders/status
  verbs:
     - '*'
- apiGroups:
    - coordination.k8s.io
  resources:
    - leases
  verbs:
    - create
    - get
    - list
    - update
{{ end }}
