// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/epam/edp-keycloak-operator/pkg/client/keycloakv2"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGroupsClient creates a new instance of MockGroupsClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGroupsClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGroupsClient {
	mock := &MockGroupsClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGroupsClient is an autogenerated mock type for the GroupsClient type
type MockGroupsClient struct {
	mock.Mock
}

type MockGroupsClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGroupsClient) EXPECT() *MockGroupsClient_Expecter {
	return &MockGroupsClient_Expecter{mock: &_m.Mock}
}

// AddClientRoleMappings provides a mock function for the type MockGroupsClient
func (_mock *MockGroupsClient) AddClientRoleMappings(ctx context.Context, realm string, groupID string, clientID string, roles []keycloakv2.RoleRepresentation) (*keycloakv2.Response, error) {
	ret := _mock.Called(ctx, realm, groupID, clientID, roles)

	if len(ret) == 0 {
		panic("no return value specified for AddClientRoleMappings")
	}

	var r0 *keycloakv2.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, []keycloakv2.RoleRepresentation) (*keycloakv2.Response, error)); ok {
		return returnFunc(ctx, realm, groupID, clientID, roles)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, []keycloakv2.RoleRepresentation) *keycloakv2.Response); ok {
		r0 = returnFunc(ctx, realm, groupID, clientID, roles)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*keycloakv2.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, []keycloakv2.RoleRepresentation) error); ok {
		r1 = returnFunc(ctx, realm, groupID, clientID, roles)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGroupsClient_AddClientRoleMappings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddClientRoleMappings'
type MockGroupsClient_AddClientRoleMappings_Call struct {
	*mock.Call
}

// AddClientRoleMappings is a helper method to define mock.On call
//   - ctx context.Context
//   - realm string
//   - groupID string
//   - clientID string
//   - roles []keycloakv2.RoleRepresentation
func (_e *MockGroupsClient_Expecter) AddClientRoleMappings(ctx interface{}, realm interface{}, groupID interface{}, clientID interface{}, roles interface{}) *MockGroupsClient_AddClientRoleMappings_Call {
	return &MockGroupsClient_AddClientRoleMappings_Call{Call: _e.mock.On("AddClientRoleMappings", ctx, realm, groupID, clientID, roles)}
}

func (_c *MockGroupsClient_AddClientRoleMappings_Call) Run(run func(ctx context.Context, realm string, groupID string, clientID string, roles []keycloakv2.RoleRepresentation)) *MockGroupsClient_AddClientRoleMappings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 []keycloakv2.RoleRepresentation
		if args[4] != nil {
			arg4 = args[4].([]keycloakv2.RoleRepresentation)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockGroupsClient_AddClientRoleMappings_Call) Return(response *keycloakv2.Response, err error) *MockGroupsClient_AddClientRoleMappings_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockGroupsClient_AddClientRoleMappings_Call) RunAndReturn(run func(ctx context.Context, realm string, groupID string, clientID string, roles []keycloakv2.RoleRepresentation) (*keycloakv2.Response, error)) *MockGroupsClient_AddClientRoleMappings_Call {
	_c.Call.Return(run)
	return _c
}

// AddRealmRoleMappings provides a mock function for the type MockGroupsClient
func (_mock *MockGroupsClient) AddRealmRoleMappings(ctx context.Context, realm string, groupID string, roles []keycloakv2.RoleRepresentation) (*keycloakv2.Response, error) {
	ret := _mock.Called(ctx, realm, groupID, roles)

	if len(ret) == 0 {
		panic("no return value specified for AddRealmRoleMappings")
	}

	var r0 *keycloakv2.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []keycloakv2.RoleRepresentation) (*keycloakv2.Response, error)); ok {
		return returnFunc(ctx, realm, groupID, roles)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []keycloakv2.RoleRepresentation) *keycloakv2.Response); ok {
		r0 = returnFunc(ctx, realm, groupID, roles)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*keycloakv2.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, []keycloakv2.RoleRepresentation) error); ok {
		r1 = returnFunc(ctx, realm, groupID, roles)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGroupsClient_AddRealmRoleMappings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddRealmRoleMappings'
type MockGroupsClient_AddRealmRoleMappings_Call struct {
	*mock.Call
}

// AddRealmRoleMappings is a helper method to define mock.On call
//   - ctx context.Context
//   - realm string
//   - groupID string
//   - roles []keycloakv2.RoleRepresentation
func (_e *MockGroupsClient_Expecter) AddRealmRoleMappings(ctx interface{}, realm interface{}, groupID interface{}, roles interface{}) *MockGroupsClient_AddRealmRoleMappings_Call {
	return &MockGroupsClient_AddRealmRoleMappings_Call{Call: _e.mock.On("AddRealmRoleMappings", ctx, realm, groupID, roles)}
}

func (_c *MockGroupsClient_AddRealmRoleMappings_Call) Run(run func(ctx context.Context, realm string, groupID string, roles []keycloakv2.RoleRepresentation)) *MockGroupsClient_AddRealmRoleMappings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []keycloakv2.RoleRepresentation
		if args[3] != nil {
			arg3 = args[3].([]keycloakv2.RoleRepresentation)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockGroupsClient_AddRealmRoleMappings_Call) Return(response *keycloakv2.Response, err error) *MockGroupsClient_AddRealmRoleMappings_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockGroupsClient_AddRealmRoleMappings_Call) RunAndReturn(run func(ctx context.Context, realm string, groupID string, roles []keycloakv2.RoleRepresentation) (*keycloakv2.Response, error)) *MockGroupsClient_AddRealmRoleMappings_Call {
	_c.Call.Return(run)
	return _c
}

// CreateChildGroup provides a mock function for the type MockGroupsClient
func (_mock *MockGroupsClient) CreateChildGroup(ctx context.Context, realm string, parentGroupID string, group keycloakv2.GroupRepresentation) (*keycloakv2.Response, error) {
	ret := _mock.Called(ctx, realm, parentGroupID, group)

	if len(ret) == 0 {
		panic("no return value specified for CreateChildGroup")
	}

	var r0 *keycloakv2.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, keycloakv2.GroupRepresentation) (*keycloakv2.Response, error)); ok {
		return returnFunc(ctx, realm, parentGroupID, group)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, keycloakv2.GroupRepresentation) *keycloakv2.Response); ok {
		r0 = returnFunc(ctx, realm, parentGroupID, group)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*keycloakv2.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, keycloakv2.GroupRepresentation) error); ok {
		r1 = returnFunc(ctx, realm, parentGroupID, group)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGroupsClient_CreateChildGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateChildGroup'
type MockGroupsClient_CreateChildGroup_Call struct {
	*mock.Call
}

// CreateChildGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - realm string
//   - parentGroupID string
//   - group keycloakv2.GroupRepresentation
func (_e *MockGroupsClient_Expecter) CreateChildGroup(ctx interface{}, realm interface{}, parentGroupID interface{}, group interface{}) *MockGroupsClient_CreateChildGroup_Call {
	return &MockGroupsClient_CreateChildGroup_Call{Call: _e.mock.On("CreateChildGroup", ctx, realm, parentGroupID, group)}
}

func (_c *MockGroupsClient_CreateChildGroup_Call) Run(run func(ctx context.Context, realm string, parentGroupID string, group keycloakv2.GroupRepresentation)) *MockGroupsClient_CreateChildGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 keycloakv2.GroupRepresentation
		if args[3] != nil {
			arg3 = args[3].(keycloakv2.GroupRepresentation)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockGroupsClient_CreateChildGroup_Call) Return(response *keycloakv2.Response, err error) *MockGroupsClient_CreateChildGroup_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockGroupsClient_CreateChildGroup_Call) RunAndReturn(run func(ctx context.Context, realm string, parentGroupID string, group keycloakv2.GroupRepresentation) (*keycloakv2.Response, error)) *MockGroupsClient_CreateChildGroup_Call {
	_c.Call.Return(run)
	return _c
}

// CreateGroup provides a mock function for the type MockGroupsClient
func (_mock *MockGroupsClient) CreateGroup(ctx context.Context, realm string, group keycloakv2.GroupRepresentation) (*keycloakv2.Response, error) {
	ret := _mock.Called(ctx, realm, group)

	if len(ret) == 0 {
		panic("no return value specified for CreateGroup")
	}

	var r0 *keycloakv2.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, keycloakv2.GroupRepresentation) (*keycloakv2.Response, error)); ok {
		return returnFunc(ctx, realm, group)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, keycloakv2.GroupRepresentation) *keycloakv2.Response); ok {
		r0 = returnFunc(ctx, realm, group)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*keycloakv2.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, keycloakv2.GroupRepresentation) error); ok {
		r1 = returnFunc(ctx, realm, group)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGroupsClient_CreateGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateGroup'
type MockGroupsClient_CreateGroup_Call struct {
	*mock.Call
}

// CreateGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - realm string
//   - group keycloakv2.GroupRepresentation
func (_e *MockGroupsClient_Expecter) CreateGroup(ctx interface{}, realm interface{}, group interface{}) *MockGroupsClient_CreateGroup_Call {
	return &MockGroupsClient_CreateGroup_Call{Call: _e.mock.On("CreateGroup", ctx, realm, group)}
}

func (_c *MockGroupsClient_CreateGroup_Call) Run(run func(ctx context.Context, realm string, group keycloakv2.GroupRepresentation)) *MockGroupsClient_CreateGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 keycloakv2.GroupRepresentation
		if args[2] != nil {
			arg2 = args[2].(keycloakv2.GroupRepresentation)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGroupsClient_CreateGroup_Call) Return(response *keycloakv2.Response, err error) *MockGroupsClient_CreateGroup_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockGroupsClient_CreateGroup_Call) RunAndReturn(run func(ctx context.Context, realm string, group keycloakv2.GroupRepresentation) (*keycloakv2.Response, error)) *MockGroupsClient_CreateGroup_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteClientRoleMappings provides a mock function for the type MockGroupsClient
func (_mock *MockGroupsClient) DeleteClientRoleMappings(ctx context.Context, realm string, groupID string, clientID string, roles []keycloakv2.RoleRepresentation) (*keycloakv2.Response, error) {
	ret := _mock.Called(ctx, realm, groupID, clientID, roles)

	if len(ret) == 0 {
		panic("no return value specified for DeleteClientRoleMappings")
	}

	var r0 *keycloakv2.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, []keycloakv2.RoleRepresentation) (*keycloakv2.Response, error)); ok {
		return returnFunc(ctx, realm, groupID, clientID, roles)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, []keycloakv2.RoleRepresentation) *keycloakv2.Response); ok {
		r0 = returnFunc(ctx, realm, groupID, clientID, roles)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*keycloakv2.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, []keycloakv2.RoleRepresentation) error); ok {
		r1 = returnFunc(ctx, realm, groupID, clientID, roles)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGroupsClient_DeleteClientRoleMappings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteClientRoleMappings'
type MockGroupsClient_DeleteClientRoleMappings_Call struct {
	*mock.Call
}

// DeleteClientRoleMappings is a helper method to define mock.On call
//   - ctx context.Context
//   - realm string
//   - groupID string
//   - clientID string
//   - roles []keycloakv2.RoleRepresentation
func (_e *MockGroupsClient_Expecter) DeleteClientRoleMappings(ctx interface{}, realm interface{}, groupID interface{}, clientID interface{}, roles interface{}) *MockGroupsClient_DeleteClientRoleMappings_Call {
	return &MockGroupsClient_DeleteClientRoleMappings_Call{Call: _e.mock.On("DeleteClientRoleMappings", ctx, realm, groupID, clientID, roles)}
}

func (_c *MockGroupsClient_DeleteClientRoleMappings_Call) Run(run func(ctx context.Context, realm string, groupID string, clientID string, roles []keycloakv2.RoleRepresentation)) *MockGroupsClient_DeleteClientRoleMappings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 []keycloakv2.RoleRepresentation
		if args[4] != nil {
			arg4 = args[4].([]keycloakv2.RoleRepresentation)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockGroupsClient_DeleteClientRoleMappings_Call) Return(response *keycloakv2.Response, err error) *MockGroupsClient_DeleteClientRoleMappings_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockGroupsClient_DeleteClientRoleMappings_Call) RunAndReturn(run func(ctx context.Context, realm string, groupID string, clientID string, roles []keycloakv2.RoleRepresentation) (*keycloakv2.Response, error)) *MockGroupsClient_DeleteClientRoleMappings_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteGroup provides a mock function for the type MockGroupsClient
func (_mock *MockGroupsClient) DeleteGroup(ctx context.Context, realm string, groupID string) (*keycloakv2.Response, error) {
	ret := _mock.Called(ctx, realm, groupID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteGroup")
	}

	var r0 *keycloakv2.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*keycloakv2.Response, error)); ok {
		return returnFunc(ctx, realm, groupID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *keycloakv2.Response); ok {
		r0 = returnFunc(ctx, realm, groupID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*keycloakv2.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, realm, groupID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGroupsClient_DeleteGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteGroup'
type MockGroupsClient_DeleteGroup_Call struct {
	*mock.Call
}

// DeleteGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - realm string
//   - groupID string
func (_e *MockGroupsClient_Expecter) DeleteGroup(ctx interface{}, realm interface{}, groupID interface{}) *MockGroupsClient_DeleteGroup_Call {
	return &MockGroupsClient_DeleteGroup_Call{Call: _e.mock.On("DeleteGroup", ctx, realm, groupID)}
}

func (_c *MockGroupsClient_DeleteGroup_Call) Run(run func(ctx context.Context, realm string, groupID string)) *MockGroupsClient_DeleteGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGroupsClient_DeleteGroup_Call) Return(response *keycloakv2.Response, err error) *MockGroupsClient_DeleteGroup_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockGroupsClient_DeleteGroup_Call) RunAndReturn(run func(ctx context.Context, realm string, groupID string) (*keycloakv2.Response, error)) *MockGroupsClient_DeleteGroup_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRealmRoleMappings provides a mock function for the type MockGroupsClient
func (_mock *MockGroupsClient) DeleteRealmRoleMappings(ctx context.Context, realm string, groupID string, roles []keycloakv2.RoleRepresentation) (*keycloakv2.Response, error) {
	ret := _mock.Called(ctx, realm, groupID, roles)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRealmRoleMappings")
	}

	var r0 *keycloakv2.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []keycloakv2.RoleRepresentation) (*keycloakv2.Response, error)); ok {
		return returnFunc(ctx, realm, groupID, roles)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []keycloakv2.RoleRepresentation) *keycloakv2.Response); ok {
		r0 = returnFunc(ctx, realm, groupID, roles)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*keycloakv2.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, []keycloakv2.RoleRepresentation) error); ok {
		r1 = returnFunc(ctx, realm, groupID, roles)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGroupsClient_DeleteRealmRoleMappings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRealmRoleMappings'
type MockGroupsClient_DeleteRealmRoleMappings_Call struct {
	*mock.Call
}

// DeleteRealmRoleMappings is a helper method to define mock.On call
//   - ctx context.Context
//   - realm string
//   - groupID string
//   - roles []keycloakv2.RoleRepresentation
func (_e *MockGroupsClient_Expecter) DeleteRealmRoleMappings(ctx interface{}, realm interface{}, groupID interface{}, roles interface{}) *MockGroupsClient_DeleteRealmRoleMappings_Call {
	return &MockGroupsClient_DeleteRealmRoleMappings_Call{Call: _e.mock.On("DeleteRealmRoleMappings", ctx, realm, groupID, roles)}
}

func (_c *MockGroupsClient_DeleteRealmRoleMappings_Call) Run(run func(ctx context.Context, realm string, groupID string, roles []keycloakv2.RoleRepresentation)) *MockGroupsClient_DeleteRealmRoleMappings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []keycloakv2.RoleRepresentation
		if args[3] != nil {
			arg3 = args[3].([]keycloakv2.RoleRepresentation)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockGroupsClient_DeleteRealmRoleMappings_Call) Return(response *keycloakv2.Response, err error) *MockGroupsClient_DeleteRealmRoleMappings_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockGroupsClient_DeleteRealmRoleMappings_Call) RunAndReturn(run func(ctx context.Context, realm string, groupID string, roles []keycloakv2.RoleRepresentation) (*keycloakv2.Response, error)) *MockGroupsClient_DeleteRealmRoleMappings_Call {
	_c.Call.Return(run)
	return _c
}

// FindChildGroupByName provides a mock function for the type MockGroupsClient
func (_mock *MockGroupsClient) FindChildGroupByName(ctx context.Context, realm string, parentGroupID string, groupName string) (*keycloakv2.GroupRepresentation, *keycloakv2.Response, error) {
	ret := _mock.Called(ctx, realm, parentGroupID, groupName)

	if len(ret) == 0 {
		panic("no return value specified for FindChildGroupByName")
	}

	var r0 *keycloakv2.GroupRepresentation
	var r1 *keycloakv2.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (*keycloakv2.GroupRepresentation, *keycloakv2.Response, error)); ok {
		return returnFunc(ctx, realm, parentGroupID, groupName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) *keycloakv2.GroupRepresentation); ok {
		r0 = returnFunc(ctx, realm, parentGroupID, groupName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*keycloakv2.GroupRepresentation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) *keycloakv2.Response); ok {
		r1 = returnFunc(ctx, realm, parentGroupID, groupName)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*keycloakv2.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string, string) error); ok {
		r2 = returnFunc(ctx, realm, parentGroupID, groupName)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockGroupsClient_FindChildGroupByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindChildGroupByName'
type MockGroupsClient_FindChildGroupByName_Call struct {
	*mock.Call
}

// FindChildGroupByName is a helper method to define mock.On call
//   - ctx context.Context
//   - realm string
//   - parentGroupID string
//   - groupName string
func (_e *MockGroupsClient_Expecter) FindChildGroupByName(ctx interface{}, realm interface{}, parentGroupID interface{}, groupName interface{}) *MockGroupsClient_FindChildGroupByName_Call {
	return &MockGroupsClient_FindChildGroupByName_Call{Call: _e.mock.On("FindChildGroupByName", ctx, realm, parentGroupID, groupName)}
}

func (_c *MockGroupsClient_FindChildGroupByName_Call) Run(run func(ctx context.Context, realm string, parentGroupID string, groupName string)) *MockGroupsClient_FindChildGroupByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockGroupsClient_FindChildGroupByName_Call) Return(v *keycloakv2.GroupRepresentation, response *keycloakv2.Response, err error) *MockGroupsClient_FindChildGroupByName_Call {
	_c.Call.Return(v, response, err)
	return _c
}

func (_c *MockGroupsClient_FindChildGroupByName_Call) RunAndReturn(run func(ctx context.Context, realm string, parentGroupID string, groupName string) (*keycloakv2.GroupRepresentation, *keycloakv2.Response, error)) *MockGroupsClient_FindChildGroupByName_Call {
	_c.Call.Return(run)
	return _c
}

// FindGroupByName provides a mock function for the type MockGroupsClient
func (_mock *MockGroupsClient) FindGroupByName(ctx context.Context, realm string, groupName string) (*keycloakv2.GroupRepresentation, *keycloakv2.Response, error) {
	ret := _mock.Called(ctx, realm, groupName)

	if len(ret) == 0 {
		panic("no return value specified for FindGroupByName")
	}

	var r0 *keycloakv2.GroupRepresentation
	var r1 *keycloakv2.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*keycloakv2.GroupRepresentation, *keycloakv2.Response, error)); ok {
		return returnFunc(ctx, realm, groupName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *keycloakv2.GroupRepresentation); ok {
		r0 = returnFunc(ctx, realm, groupName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*keycloakv2.GroupRepresentation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) *keycloakv2.Response); ok {
		r1 = returnFunc(ctx, realm, groupName)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*keycloakv2.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = returnFunc(ctx, realm, groupName)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockGroupsClient_FindGroupByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindGroupByName'
type MockGroupsClient_FindGroupByName_Call struct {
	*mock.Call
}

// FindGroupByName is a helper method to define mock.On call
//   - ctx context.Context
//   - realm string
//   - groupName string
func (_e *MockGroupsClient_Expecter) FindGroupByName(ctx interface{}, realm interface{}, groupName interface{}) *MockGroupsClient_FindGroupByName_Call {
	return &MockGroupsClient_FindGroupByName_Call{Call: _e.mock.On("FindGroupByName", ctx, realm, groupName)}
}

func (_c *MockGroupsClient_FindGroupByName_Call) Run(run func(ctx context.Context, realm string, groupName string)) *MockGroupsClient_FindGroupByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGroupsClient_FindGroupByName_Call) Return(v *keycloakv2.GroupRepresentation, response *keycloakv2.Response, err error) *MockGroupsClient_FindGroupByName_Call {
	_c.Call.Return(v, response, err)
	return _c
}

func (_c *MockGroupsClient_FindGroupByName_Call) RunAndReturn(run func(ctx context.Context, realm string, groupName string) (*keycloakv2.GroupRepresentation, *keycloakv2.Response, error)) *MockGroupsClient_FindGroupByName_Call {
	_c.Call.Return(run)
	return _c
}

// GetChildGroups provides a mock function for the type MockGroupsClient
func (_mock *MockGroupsClient) GetChildGroups(ctx context.Context, realm string, groupID string, params *keycloakv2.GetChildGroupsParams) ([]keycloakv2.GroupRepresentation, *keycloakv2.Response, error) {
	ret := _mock.Called(ctx, realm, groupID, params)

	if len(ret) == 0 {
		panic("no return value specified for GetChildGroups")
	}

	var r0 []keycloakv2.GroupRepresentation
	var r1 *keycloakv2.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *keycloakv2.GetChildGroupsParams) ([]keycloakv2.GroupRepresentation, *keycloakv2.Response, error)); ok {
		return returnFunc(ctx, realm, groupID, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *keycloakv2.GetChildGroupsParams) []keycloakv2.GroupRepresentation); ok {
		r0 = returnFunc(ctx, realm, groupID, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]keycloakv2.GroupRepresentation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, *keycloakv2.GetChildGroupsParams) *keycloakv2.Response); ok {
		r1 = returnFunc(ctx, realm, groupID, params)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*keycloakv2.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string, *keycloakv2.GetChildGroupsParams) error); ok {
		r2 = returnFunc(ctx, realm, groupID, params)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockGroupsClient_GetChildGroups_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChildGroups'
type MockGroupsClient_GetChildGroups_Call struct {
	*mock.Call
}

// GetChildGroups is a helper method to define mock.On call
//   - ctx context.Context
//   - realm string
//   - groupID string
//   - params *keycloakv2.GetChildGroupsParams
func (_e *MockGroupsClient_Expecter) GetChildGroups(ctx interface{}, realm interface{}, groupID interface{}, params interface{}) *MockGroupsClient_GetChildGroups_Call {
	return &MockGroupsClient_GetChildGroups_Call{Call: _e.mock.On("GetChildGroups", ctx, realm, groupID, params)}
}

func (_c *MockGroupsClient_GetChildGroups_Call) Run(run func(ctx context.Context, realm string, groupID string, params *keycloakv2.GetChildGroupsParams)) *MockGroupsClient_GetChildGroups_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *keycloakv2.GetChildGroupsParams
		if args[3] != nil {
			arg3 = args[3].(*keycloakv2.GetChildGroupsParams)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockGroupsClient_GetChildGroups_Call) Return(vs []keycloakv2.GroupRepresentation, response *keycloakv2.Response, err error) *MockGroupsClient_GetChildGroups_Call {
	_c.Call.Return(vs, response, err)
	return _c
}

func (_c *MockGroupsClient_GetChildGroups_Call) RunAndReturn(run func(ctx context.Context, realm string, groupID string, params *keycloakv2.GetChildGroupsParams) ([]keycloakv2.GroupRepresentation, *keycloakv2.Response, error)) *MockGroupsClient_GetChildGroups_Call {
	_c.Call.Return(run)
	return _c
}

// GetClientRoleMappings provides a mock function for the type MockGroupsClient
func (_mock *MockGroupsClient) GetClientRoleMappings(ctx context.Context, realm string, groupID string, clientID string) ([]keycloakv2.RoleRepresentation, *keycloakv2.Response, error) {
	ret := _mock.Called(ctx, realm, groupID, clientID)

	if len(ret) == 0 {
		panic("no return value specified for GetClientRoleMappings")
	}

	var r0 []keycloakv2.RoleRepresentation
	var r1 *keycloakv2.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) ([]keycloakv2.RoleRepresentation, *keycloakv2.Response, error)); ok {
		return returnFunc(ctx, realm, groupID, clientID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) []keycloakv2.RoleRepresentation); ok {
		r0 = returnFunc(ctx, realm, groupID, clientID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]keycloakv2.RoleRepresentation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) *keycloakv2.Response); ok {
		r1 = returnFunc(ctx, realm, groupID, clientID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*keycloakv2.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string, string) error); ok {
		r2 = returnFunc(ctx, realm, groupID, clientID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockGroupsClient_GetClientRoleMappings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClientRoleMappings'
type MockGroupsClient_GetClientRoleMappings_Call struct {
	*mock.Call
}

// GetClientRoleMappings is a helper method to define mock.On call
//   - ctx context.Context
//   - realm string
//   - groupID string
//   - clientID string
func (_e *MockGroupsClient_Expecter) GetClientRoleMappings(ctx interface{}, realm interface{}, groupID interface{}, clientID interface{}) *MockGroupsClient_GetClientRoleMappings_Call {
	return &MockGroupsClient_GetClientRoleMappings_Call{Call: _e.mock.On("GetClientRoleMappings", ctx, realm, groupID, clientID)}
}

func (_c *MockGroupsClient_GetClientRoleMappings_Call) Run(run func(ctx context.Context, realm string, groupID string, clientID string)) *MockGroupsClient_GetClientRoleMappings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockGroupsClient_GetClientRoleMappings_Call) Return(vs []keycloakv2.RoleRepresentation, response *keycloakv2.Response, err error) *MockGroupsClient_GetClientRoleMappings_Call {
	_c.Call.Return(vs, response, err)
	return _c
}

func (_c *MockGroupsClient_GetClientRoleMappings_Call) RunAndReturn(run func(ctx context.Context, realm string, groupID string, clientID string) ([]keycloakv2.RoleRepresentation, *keycloakv2.Response, error)) *MockGroupsClient_GetClientRoleMappings_Call {
	_c.Call.Return(run)
	return _c
}

// GetGroup provides a mock function for the type MockGroupsClient
func (_mock *MockGroupsClient) GetGroup(ctx context.Context, realm string, groupID string) (*keycloakv2.GroupRepresentation, *keycloakv2.Response, error) {
	ret := _mock.Called(ctx, realm, groupID)

	if len(ret) == 0 {
		panic("no return value specified for GetGroup")
	}

	var r0 *keycloakv2.GroupRepresentation
	var r1 *keycloakv2.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*keycloakv2.GroupRepresentation, *keycloakv2.Response, error)); ok {
		return returnFunc(ctx, realm, groupID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *keycloakv2.GroupRepresentation); ok {
		r0 = returnFunc(ctx, realm, groupID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*keycloakv2.GroupRepresentation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) *keycloakv2.Response); ok {
		r1 = returnFunc(ctx, realm, groupID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*keycloakv2.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = returnFunc(ctx, realm, groupID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockGroupsClient_GetGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGroup'
type MockGroupsClient_GetGroup_Call struct {
	*mock.Call
}

// GetGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - realm string
//   - groupID string
func (_e *MockGroupsClient_Expecter) GetGroup(ctx interface{}, realm interface{}, groupID interface{}) *MockGroupsClient_GetGroup_Call {
	return &MockGroupsClient_GetGroup_Call{Call: _e.mock.On("GetGroup", ctx, realm, groupID)}
}

func (_c *MockGroupsClient_GetGroup_Call) Run(run func(ctx context.Context, realm string, groupID string)) *MockGroupsClient_GetGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGroupsClient_GetGroup_Call) Return(v *keycloakv2.GroupRepresentation, response *keycloakv2.Response, err error) *MockGroupsClient_GetGroup_Call {
	_c.Call.Return(v, response, err)
	return _c
}

func (_c *MockGroupsClient_GetGroup_Call) RunAndReturn(run func(ctx context.Context, realm string, groupID string) (*keycloakv2.GroupRepresentation, *keycloakv2.Response, error)) *MockGroupsClient_GetGroup_Call {
	_c.Call.Return(run)
	return _c
}

// GetGroupByPath provides a mock function for the type MockGroupsClient
func (_mock *MockGroupsClient) GetGroupByPath(ctx context.Context, realm string, path string) (*keycloakv2.GroupRepresentation, *keycloakv2.Response, error) {
	ret := _mock.Called(ctx, realm, path)

	if len(ret) == 0 {
		panic("no return value specified for GetGroupByPath")
	}

	var r0 *keycloakv2.GroupRepresentation
	var r1 *keycloakv2.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*keycloakv2.GroupRepresentation, *keycloakv2.Response, error)); ok {
		return returnFunc(ctx, realm, path)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *keycloakv2.GroupRepresentation); ok {
		r0 = returnFunc(ctx, realm, path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*keycloakv2.GroupRepresentation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) *keycloakv2.Response); ok {
		r1 = returnFunc(ctx, realm, path)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*keycloakv2.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = returnFunc(ctx, realm, path)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockGroupsClient_GetGroupByPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGroupByPath'
type MockGroupsClient_GetGroupByPath_Call struct {
	*mock.Call
}

// GetGroupByPath is a helper method to define mock.On call
//   - ctx context.Context
//   - realm string
//   - path string
func (_e *MockGroupsClient_Expecter) GetGroupByPath(ctx interface{}, realm interface{}, path interface{}) *MockGroupsClient_GetGroupByPath_Call {
	return &MockGroupsClient_GetGroupByPath_Call{Call: _e.mock.On("GetGroupByPath", ctx, realm, path)}
}

func (_c *MockGroupsClient_GetGroupByPath_Call) Run(run func(ctx context.Context, realm string, path string)) *MockGroupsClient_GetGroupByPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGroupsClient_GetGroupByPath_Call) Return(v *keycloakv2.GroupRepresentation, response *keycloakv2.Response, err error) *MockGroupsClient_GetGroupByPath_Call {
	_c.Call.Return(v, response, err)
	return _c
}

func (_c *MockGroupsClient_GetGroupByPath_Call) RunAndReturn(run func(ctx context.Context, realm string, path string) (*keycloakv2.GroupRepresentation, *keycloakv2.Response, error)) *MockGroupsClient_GetGroupByPath_Call {
	_c.Call.Return(run)
	return _c
}

// GetGroups provides a mock function for the type MockGroupsClient
func (_mock *MockGroupsClient) GetGroups(ctx context.Context, realm string, params *keycloakv2.GetGroupsParams) ([]keycloakv2.GroupRepresentation, *keycloakv2.Response, error) {
	ret := _mock.Called(ctx, realm, params)

	if len(ret) == 0 {
		panic("no return value specified for GetGroups")
	}

	var r0 []keycloakv2.GroupRepresentation
	var r1 *keycloakv2.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *keycloakv2.GetGroupsParams) ([]keycloakv2.GroupRepresentation, *keycloakv2.Response, error)); ok {
		return returnFunc(ctx, realm, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *keycloakv2.GetGroupsParams) []keycloakv2.GroupRepresentation); ok {
		r0 = returnFunc(ctx, realm, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]keycloakv2.GroupRepresentation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *keycloakv2.GetGroupsParams) *keycloakv2.Response); ok {
		r1 = returnFunc(ctx, realm, params)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*keycloakv2.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, *keycloakv2.GetGroupsParams) error); ok {
		r2 = returnFunc(ctx, realm, params)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockGroupsClient_GetGroups_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGroups'
type MockGroupsClient_GetGroups_Call struct {
	*mock.Call
}

// GetGroups is a helper method to define mock.On call
//   - ctx context.Context
//   - realm string
//   - params *keycloakv2.GetGroupsParams
func (_e *MockGroupsClient_Expecter) GetGroups(ctx interface{}, realm interface{}, params interface{}) *MockGroupsClient_GetGroups_Call {
	return &MockGroupsClient_GetGroups_Call{Call: _e.mock.On("GetGroups", ctx, realm, params)}
}

func (_c *MockGroupsClient_GetGroups_Call) Run(run func(ctx context.Context, realm string, params *keycloakv2.GetGroupsParams)) *MockGroupsClient_GetGroups_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *keycloakv2.GetGroupsParams
		if args[2] != nil {
			arg2 = args[2].(*keycloakv2.GetGroupsParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGroupsClient_GetGroups_Call) Return(vs []keycloakv2.GroupRepresentation, response *keycloakv2.Response, err error) *MockGroupsClient_GetGroups_Call {
	_c.Call.Return(vs, response, err)
	return _c
}

func (_c *MockGroupsClient_GetGroups_Call) RunAndReturn(run func(ctx context.Context, realm string, params *keycloakv2.GetGroupsParams) ([]keycloakv2.GroupRepresentation, *keycloakv2.Response, error)) *MockGroupsClient_GetGroups_Call {
	_c.Call.Return(run)
	return _c
}

// GetRealmRoleMappings provides a mock function for the type MockGroupsClient
func (_mock *MockGroupsClient) GetRealmRoleMappings(ctx context.Context, realm string, groupID string) ([]keycloakv2.RoleRepresentation, *keycloakv2.Response, error) {
	ret := _mock.Called(ctx, realm, groupID)

	if len(ret) == 0 {
		panic("no return value specified for GetRealmRoleMappings")
	}

	var r0 []keycloakv2.RoleRepresentation
	var r1 *keycloakv2.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]keycloakv2.RoleRepresentation, *keycloakv2.Response, error)); ok {
		return returnFunc(ctx, realm, groupID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []keycloakv2.RoleRepresentation); ok {
		r0 = returnFunc(ctx, realm, groupID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]keycloakv2.RoleRepresentation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) *keycloakv2.Response); ok {
		r1 = returnFunc(ctx, realm, groupID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*keycloakv2.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = returnFunc(ctx, realm, groupID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockGroupsClient_GetRealmRoleMappings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRealmRoleMappings'
type MockGroupsClient_GetRealmRoleMappings_Call struct {
	*mock.Call
}

// GetRealmRoleMappings is a helper method to define mock.On call
//   - ctx context.Context
//   - realm string
//   - groupID string
func (_e *MockGroupsClient_Expecter) GetRealmRoleMappings(ctx interface{}, realm interface{}, groupID interface{}) *MockGroupsClient_GetRealmRoleMappings_Call {
	return &MockGroupsClient_GetRealmRoleMappings_Call{Call: _e.mock.On("GetRealmRoleMappings", ctx, realm, groupID)}
}

func (_c *MockGroupsClient_GetRealmRoleMappings_Call) Run(run func(ctx context.Context, realm string, groupID string)) *MockGroupsClient_GetRealmRoleMappings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGroupsClient_GetRealmRoleMappings_Call) Return(vs []keycloakv2.RoleRepresentation, response *keycloakv2.Response, err error) *MockGroupsClient_GetRealmRoleMappings_Call {
	_c.Call.Return(vs, response, err)
	return _c
}

func (_c *MockGroupsClient_GetRealmRoleMappings_Call) RunAndReturn(run func(ctx context.Context, realm string, groupID string) ([]keycloakv2.RoleRepresentation, *keycloakv2.Response, error)) *MockGroupsClient_GetRealmRoleMappings_Call {
	_c.Call.Return(run)
	return _c
}

// GetRoleMappings provides a mock function for the type MockGroupsClient
func (_mock *MockGroupsClient) GetRoleMappings(ctx context.Context, realm string, groupID string) (*keycloakv2.MappingsRepresentation, *keycloakv2.Response, error) {
	ret := _mock.Called(ctx, realm, groupID)

	if len(ret) == 0 {
		panic("no return value specified for GetRoleMappings")
	}

	var r0 *keycloakv2.MappingsRepresentation
	var r1 *keycloakv2.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*keycloakv2.MappingsRepresentation, *keycloakv2.Response, error)); ok {
		return returnFunc(ctx, realm, groupID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *keycloakv2.MappingsRepresentation); ok {
		r0 = returnFunc(ctx, realm, groupID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*keycloakv2.MappingsRepresentation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) *keycloakv2.Response); ok {
		r1 = returnFunc(ctx, realm, groupID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*keycloakv2.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = returnFunc(ctx, realm, groupID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockGroupsClient_GetRoleMappings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRoleMappings'
type MockGroupsClient_GetRoleMappings_Call struct {
	*mock.Call
}

// GetRoleMappings is a helper method to define mock.On call
//   - ctx context.Context
//   - realm string
//   - groupID string
func (_e *MockGroupsClient_Expecter) GetRoleMappings(ctx interface{}, realm interface{}, groupID interface{}) *MockGroupsClient_GetRoleMappings_Call {
	return &MockGroupsClient_GetRoleMappings_Call{Call: _e.mock.On("GetRoleMappings", ctx, realm, groupID)}
}

func (_c *MockGroupsClient_GetRoleMappings_Call) Run(run func(ctx context.Context, realm string, groupID string)) *MockGroupsClient_GetRoleMappings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGroupsClient_GetRoleMappings_Call) Return(v *keycloakv2.MappingsRepresentation, response *keycloakv2.Response, err error) *MockGroupsClient_GetRoleMappings_Call {
	_c.Call.Return(v, response, err)
	return _c
}

func (_c *MockGroupsClient_GetRoleMappings_Call) RunAndReturn(run func(ctx context.Context, realm string, groupID string) (*keycloakv2.MappingsRepresentation, *keycloakv2.Response, error)) *MockGroupsClient_GetRoleMappings_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateGroup provides a mock function for the type MockGroupsClient
func (_mock *MockGroupsClient) UpdateGroup(ctx context.Context, realm string, groupID string, group keycloakv2.GroupRepresentation) (*keycloakv2.Response, error) {
	ret := _mock.Called(ctx, realm, groupID, group)

	if len(ret) == 0 {
		panic("no return value specified for UpdateGroup")
	}

	var r0 *keycloakv2.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, keycloakv2.GroupRepresentation) (*keycloakv2.Response, error)); ok {
		return returnFunc(ctx, realm, groupID, group)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, keycloakv2.GroupRepresentation) *keycloakv2.Response); ok {
		r0 = returnFunc(ctx, realm, groupID, group)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*keycloakv2.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, keycloakv2.GroupRepresentation) error); ok {
		r1 = returnFunc(ctx, realm, groupID, group)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGroupsClient_UpdateGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateGroup'
type MockGroupsClient_UpdateGroup_Call struct {
	*mock.Call
}

// UpdateGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - realm string
//   - groupID string
//   - group keycloakv2.GroupRepresentation
func (_e *MockGroupsClient_Expecter) UpdateGroup(ctx interface{}, realm interface{}, groupID interface{}, group interface{}) *MockGroupsClient_UpdateGroup_Call {
	return &MockGroupsClient_UpdateGroup_Call{Call: _e.mock.On("UpdateGroup", ctx, realm, groupID, group)}
}

func (_c *MockGroupsClient_UpdateGroup_Call) Run(run func(ctx context.Context, realm string, groupID string, group keycloakv2.GroupRepresentation)) *MockGroupsClient_UpdateGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 keycloakv2.GroupRepresentation
		if args[3] != nil {
			arg3 = args[3].(keycloakv2.GroupRepresentation)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockGroupsClient_UpdateGroup_Call) Return(response *keycloakv2.Response, err error) *MockGroupsClient_UpdateGroup_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockGroupsClient_UpdateGroup_Call) RunAndReturn(run func(ctx context.Context, realm string, groupID string, group keycloakv2.GroupRepresentation) (*keycloakv2.Response, error)) *MockGroupsClient_UpdateGroup_Call {
	_c.Call.Return(run)
	return _c
}
