// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/epam/edp-keycloak-operator/pkg/client/keycloakv2"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRealmClient creates a new instance of MockRealmClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRealmClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRealmClient {
	mock := &MockRealmClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRealmClient is an autogenerated mock type for the RealmClient type
type MockRealmClient struct {
	mock.Mock
}

type MockRealmClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRealmClient) EXPECT() *MockRealmClient_Expecter {
	return &MockRealmClient_Expecter{mock: &_m.Mock}
}

// CreateRealm provides a mock function for the type MockRealmClient
func (_mock *MockRealmClient) CreateRealm(ctx context.Context, realmRep keycloakv2.RealmRepresentation) (*keycloakv2.Response, error) {
	ret := _mock.Called(ctx, realmRep)

	if len(ret) == 0 {
		panic("no return value specified for CreateRealm")
	}

	var r0 *keycloakv2.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, keycloakv2.RealmRepresentation) (*keycloakv2.Response, error)); ok {
		return returnFunc(ctx, realmRep)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, keycloakv2.RealmRepresentation) *keycloakv2.Response); ok {
		r0 = returnFunc(ctx, realmRep)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*keycloakv2.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, keycloakv2.RealmRepresentation) error); ok {
		r1 = returnFunc(ctx, realmRep)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRealmClient_CreateRealm_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRealm'
type MockRealmClient_CreateRealm_Call struct {
	*mock.Call
}

// CreateRealm is a helper method to define mock.On call
//   - ctx context.Context
//   - realmRep keycloakv2.RealmRepresentation
func (_e *MockRealmClient_Expecter) CreateRealm(ctx interface{}, realmRep interface{}) *MockRealmClient_CreateRealm_Call {
	return &MockRealmClient_CreateRealm_Call{Call: _e.mock.On("CreateRealm", ctx, realmRep)}
}

func (_c *MockRealmClient_CreateRealm_Call) Run(run func(ctx context.Context, realmRep keycloakv2.RealmRepresentation)) *MockRealmClient_CreateRealm_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 keycloakv2.RealmRepresentation
		if args[1] != nil {
			arg1 = args[1].(keycloakv2.RealmRepresentation)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRealmClient_CreateRealm_Call) Return(response *keycloakv2.Response, err error) *MockRealmClient_CreateRealm_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockRealmClient_CreateRealm_Call) RunAndReturn(run func(ctx context.Context, realmRep keycloakv2.RealmRepresentation) (*keycloakv2.Response, error)) *MockRealmClient_CreateRealm_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRealm provides a mock function for the type MockRealmClient
func (_mock *MockRealmClient) DeleteRealm(ctx context.Context, realm string) (*keycloakv2.Response, error) {
	ret := _mock.Called(ctx, realm)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRealm")
	}

	var r0 *keycloakv2.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*keycloakv2.Response, error)); ok {
		return returnFunc(ctx, realm)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *keycloakv2.Response); ok {
		r0 = returnFunc(ctx, realm)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*keycloakv2.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, realm)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRealmClient_DeleteRealm_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRealm'
type MockRealmClient_DeleteRealm_Call struct {
	*mock.Call
}

// DeleteRealm is a helper method to define mock.On call
//   - ctx context.Context
//   - realm string
func (_e *MockRealmClient_Expecter) DeleteRealm(ctx interface{}, realm interface{}) *MockRealmClient_DeleteRealm_Call {
	return &MockRealmClient_DeleteRealm_Call{Call: _e.mock.On("DeleteRealm", ctx, realm)}
}

func (_c *MockRealmClient_DeleteRealm_Call) Run(run func(ctx context.Context, realm string)) *MockRealmClient_DeleteRealm_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRealmClient_DeleteRealm_Call) Return(response *keycloakv2.Response, err error) *MockRealmClient_DeleteRealm_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockRealmClient_DeleteRealm_Call) RunAndReturn(run func(ctx context.Context, realm string) (*keycloakv2.Response, error)) *MockRealmClient_DeleteRealm_Call {
	_c.Call.Return(run)
	return _c
}

// GetRealm provides a mock function for the type MockRealmClient
func (_mock *MockRealmClient) GetRealm(ctx context.Context, realm string) (*keycloakv2.RealmRepresentation, *keycloakv2.Response, error) {
	ret := _mock.Called(ctx, realm)

	if len(ret) == 0 {
		panic("no return value specified for GetRealm")
	}

	var r0 *keycloakv2.RealmRepresentation
	var r1 *keycloakv2.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*keycloakv2.RealmRepresentation, *keycloakv2.Response, error)); ok {
		return returnFunc(ctx, realm)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *keycloakv2.RealmRepresentation); ok {
		r0 = returnFunc(ctx, realm)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*keycloakv2.RealmRepresentation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) *keycloakv2.Response); ok {
		r1 = returnFunc(ctx, realm)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*keycloakv2.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, realm)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockRealmClient_GetRealm_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRealm'
type MockRealmClient_GetRealm_Call struct {
	*mock.Call
}

// GetRealm is a helper method to define mock.On call
//   - ctx context.Context
//   - realm string
func (_e *MockRealmClient_Expecter) GetRealm(ctx interface{}, realm interface{}) *MockRealmClient_GetRealm_Call {
	return &MockRealmClient_GetRealm_Call{Call: _e.mock.On("GetRealm", ctx, realm)}
}

func (_c *MockRealmClient_GetRealm_Call) Run(run func(ctx context.Context, realm string)) *MockRealmClient_GetRealm_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRealmClient_GetRealm_Call) Return(v *keycloakv2.RealmRepresentation, response *keycloakv2.Response, err error) *MockRealmClient_GetRealm_Call {
	_c.Call.Return(v, response, err)
	return _c
}

func (_c *MockRealmClient_GetRealm_Call) RunAndReturn(run func(ctx context.Context, realm string) (*keycloakv2.RealmRepresentation, *keycloakv2.Response, error)) *MockRealmClient_GetRealm_Call {
	_c.Call.Return(run)
	return _c
}

// SetRealmBrowserFlow provides a mock function for the type MockRealmClient
func (_mock *MockRealmClient) SetRealmBrowserFlow(ctx context.Context, realm string, flowAlias string) (*keycloakv2.Response, error) {
	ret := _mock.Called(ctx, realm, flowAlias)

	if len(ret) == 0 {
		panic("no return value specified for SetRealmBrowserFlow")
	}

	var r0 *keycloakv2.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*keycloakv2.Response, error)); ok {
		return returnFunc(ctx, realm, flowAlias)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *keycloakv2.Response); ok {
		r0 = returnFunc(ctx, realm, flowAlias)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*keycloakv2.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, realm, flowAlias)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRealmClient_SetRealmBrowserFlow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetRealmBrowserFlow'
type MockRealmClient_SetRealmBrowserFlow_Call struct {
	*mock.Call
}

// SetRealmBrowserFlow is a helper method to define mock.On call
//   - ctx context.Context
//   - realm string
//   - flowAlias string
func (_e *MockRealmClient_Expecter) SetRealmBrowserFlow(ctx interface{}, realm interface{}, flowAlias interface{}) *MockRealmClient_SetRealmBrowserFlow_Call {
	return &MockRealmClient_SetRealmBrowserFlow_Call{Call: _e.mock.On("SetRealmBrowserFlow", ctx, realm, flowAlias)}
}

func (_c *MockRealmClient_SetRealmBrowserFlow_Call) Run(run func(ctx context.Context, realm string, flowAlias string)) *MockRealmClient_SetRealmBrowserFlow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRealmClient_SetRealmBrowserFlow_Call) Return(response *keycloakv2.Response, err error) *MockRealmClient_SetRealmBrowserFlow_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockRealmClient_SetRealmBrowserFlow_Call) RunAndReturn(run func(ctx context.Context, realm string, flowAlias string) (*keycloakv2.Response, error)) *MockRealmClient_SetRealmBrowserFlow_Call {
	_c.Call.Return(run)
	return _c
}

// SetRealmEventConfig provides a mock function for the type MockRealmClient
func (_mock *MockRealmClient) SetRealmEventConfig(ctx context.Context, realm string, cfg keycloakv2.RealmEventsConfigRepresentation) (*keycloakv2.Response, error) {
	ret := _mock.Called(ctx, realm, cfg)

	if len(ret) == 0 {
		panic("no return value specified for SetRealmEventConfig")
	}

	var r0 *keycloakv2.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, keycloakv2.RealmEventsConfigRepresentation) (*keycloakv2.Response, error)); ok {
		return returnFunc(ctx, realm, cfg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, keycloakv2.RealmEventsConfigRepresentation) *keycloakv2.Response); ok {
		r0 = returnFunc(ctx, realm, cfg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*keycloakv2.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, keycloakv2.RealmEventsConfigRepresentation) error); ok {
		r1 = returnFunc(ctx, realm, cfg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRealmClient_SetRealmEventConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetRealmEventConfig'
type MockRealmClient_SetRealmEventConfig_Call struct {
	*mock.Call
}

// SetRealmEventConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - realm string
//   - cfg keycloakv2.RealmEventsConfigRepresentation
func (_e *MockRealmClient_Expecter) SetRealmEventConfig(ctx interface{}, realm interface{}, cfg interface{}) *MockRealmClient_SetRealmEventConfig_Call {
	return &MockRealmClient_SetRealmEventConfig_Call{Call: _e.mock.On("SetRealmEventConfig", ctx, realm, cfg)}
}

func (_c *MockRealmClient_SetRealmEventConfig_Call) Run(run func(ctx context.Context, realm string, cfg keycloakv2.RealmEventsConfigRepresentation)) *MockRealmClient_SetRealmEventConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 keycloakv2.RealmEventsConfigRepresentation
		if args[2] != nil {
			arg2 = args[2].(keycloakv2.RealmEventsConfigRepresentation)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRealmClient_SetRealmEventConfig_Call) Return(response *keycloakv2.Response, err error) *MockRealmClient_SetRealmEventConfig_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockRealmClient_SetRealmEventConfig_Call) RunAndReturn(run func(ctx context.Context, realm string, cfg keycloakv2.RealmEventsConfigRepresentation) (*keycloakv2.Response, error)) *MockRealmClient_SetRealmEventConfig_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRealm provides a mock function for the type MockRealmClient
func (_mock *MockRealmClient) UpdateRealm(ctx context.Context, realm string, realmRep keycloakv2.RealmRepresentation) (*keycloakv2.Response, error) {
	ret := _mock.Called(ctx, realm, realmRep)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRealm")
	}

	var r0 *keycloakv2.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, keycloakv2.RealmRepresentation) (*keycloakv2.Response, error)); ok {
		return returnFunc(ctx, realm, realmRep)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, keycloakv2.RealmRepresentation) *keycloakv2.Response); ok {
		r0 = returnFunc(ctx, realm, realmRep)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*keycloakv2.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, keycloakv2.RealmRepresentation) error); ok {
		r1 = returnFunc(ctx, realm, realmRep)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRealmClient_UpdateRealm_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRealm'
type MockRealmClient_UpdateRealm_Call struct {
	*mock.Call
}

// UpdateRealm is a helper method to define mock.On call
//   - ctx context.Context
//   - realm string
//   - realmRep keycloakv2.RealmRepresentation
func (_e *MockRealmClient_Expecter) UpdateRealm(ctx interface{}, realm interface{}, realmRep interface{}) *MockRealmClient_UpdateRealm_Call {
	return &MockRealmClient_UpdateRealm_Call{Call: _e.mock.On("UpdateRealm", ctx, realm, realmRep)}
}

func (_c *MockRealmClient_UpdateRealm_Call) Run(run func(ctx context.Context, realm string, realmRep keycloakv2.RealmRepresentation)) *MockRealmClient_UpdateRealm_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 keycloakv2.RealmRepresentation
		if args[2] != nil {
			arg2 = args[2].(keycloakv2.RealmRepresentation)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRealmClient_UpdateRealm_Call) Return(response *keycloakv2.Response, err error) *MockRealmClient_UpdateRealm_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockRealmClient_UpdateRealm_Call) RunAndReturn(run func(ctx context.Context, realm string, realmRep keycloakv2.RealmRepresentation) (*keycloakv2.Response, error)) *MockRealmClient_UpdateRealm_Call {
	_c.Call.Return(run)
	return _c
}
