// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/epam/edp-keycloak-operator/pkg/client/keycloakv2"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRolesClient creates a new instance of MockRolesClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRolesClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRolesClient {
	mock := &MockRolesClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRolesClient is an autogenerated mock type for the RolesClient type
type MockRolesClient struct {
	mock.Mock
}

type MockRolesClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRolesClient) EXPECT() *MockRolesClient_Expecter {
	return &MockRolesClient_Expecter{mock: &_m.Mock}
}

// CreateRealmRole provides a mock function for the type MockRolesClient
func (_mock *MockRolesClient) CreateRealmRole(ctx context.Context, realm string, role keycloakv2.RoleRepresentation) (*keycloakv2.Response, error) {
	ret := _mock.Called(ctx, realm, role)

	if len(ret) == 0 {
		panic("no return value specified for CreateRealmRole")
	}

	var r0 *keycloakv2.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, keycloakv2.RoleRepresentation) (*keycloakv2.Response, error)); ok {
		return returnFunc(ctx, realm, role)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, keycloakv2.RoleRepresentation) *keycloakv2.Response); ok {
		r0 = returnFunc(ctx, realm, role)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*keycloakv2.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, keycloakv2.RoleRepresentation) error); ok {
		r1 = returnFunc(ctx, realm, role)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRolesClient_CreateRealmRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRealmRole'
type MockRolesClient_CreateRealmRole_Call struct {
	*mock.Call
}

// CreateRealmRole is a helper method to define mock.On call
//   - ctx context.Context
//   - realm string
//   - role keycloakv2.RoleRepresentation
func (_e *MockRolesClient_Expecter) CreateRealmRole(ctx interface{}, realm interface{}, role interface{}) *MockRolesClient_CreateRealmRole_Call {
	return &MockRolesClient_CreateRealmRole_Call{Call: _e.mock.On("CreateRealmRole", ctx, realm, role)}
}

func (_c *MockRolesClient_CreateRealmRole_Call) Run(run func(ctx context.Context, realm string, role keycloakv2.RoleRepresentation)) *MockRolesClient_CreateRealmRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 keycloakv2.RoleRepresentation
		if args[2] != nil {
			arg2 = args[2].(keycloakv2.RoleRepresentation)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRolesClient_CreateRealmRole_Call) Return(response *keycloakv2.Response, err error) *MockRolesClient_CreateRealmRole_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockRolesClient_CreateRealmRole_Call) RunAndReturn(run func(ctx context.Context, realm string, role keycloakv2.RoleRepresentation) (*keycloakv2.Response, error)) *MockRolesClient_CreateRealmRole_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRealmRole provides a mock function for the type MockRolesClient
func (_mock *MockRolesClient) DeleteRealmRole(ctx context.Context, realm string, roleName string) (*keycloakv2.Response, error) {
	ret := _mock.Called(ctx, realm, roleName)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRealmRole")
	}

	var r0 *keycloakv2.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*keycloakv2.Response, error)); ok {
		return returnFunc(ctx, realm, roleName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *keycloakv2.Response); ok {
		r0 = returnFunc(ctx, realm, roleName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*keycloakv2.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, realm, roleName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRolesClient_DeleteRealmRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRealmRole'
type MockRolesClient_DeleteRealmRole_Call struct {
	*mock.Call
}

// DeleteRealmRole is a helper method to define mock.On call
//   - ctx context.Context
//   - realm string
//   - roleName string
func (_e *MockRolesClient_Expecter) DeleteRealmRole(ctx interface{}, realm interface{}, roleName interface{}) *MockRolesClient_DeleteRealmRole_Call {
	return &MockRolesClient_DeleteRealmRole_Call{Call: _e.mock.On("DeleteRealmRole", ctx, realm, roleName)}
}

func (_c *MockRolesClient_DeleteRealmRole_Call) Run(run func(ctx context.Context, realm string, roleName string)) *MockRolesClient_DeleteRealmRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRolesClient_DeleteRealmRole_Call) Return(response *keycloakv2.Response, err error) *MockRolesClient_DeleteRealmRole_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockRolesClient_DeleteRealmRole_Call) RunAndReturn(run func(ctx context.Context, realm string, roleName string) (*keycloakv2.Response, error)) *MockRolesClient_DeleteRealmRole_Call {
	_c.Call.Return(run)
	return _c
}

// GetRealmRole provides a mock function for the type MockRolesClient
func (_mock *MockRolesClient) GetRealmRole(ctx context.Context, realm string, roleName string) (*keycloakv2.RoleRepresentation, *keycloakv2.Response, error) {
	ret := _mock.Called(ctx, realm, roleName)

	if len(ret) == 0 {
		panic("no return value specified for GetRealmRole")
	}

	var r0 *keycloakv2.RoleRepresentation
	var r1 *keycloakv2.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*keycloakv2.RoleRepresentation, *keycloakv2.Response, error)); ok {
		return returnFunc(ctx, realm, roleName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *keycloakv2.RoleRepresentation); ok {
		r0 = returnFunc(ctx, realm, roleName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*keycloakv2.RoleRepresentation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) *keycloakv2.Response); ok {
		r1 = returnFunc(ctx, realm, roleName)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*keycloakv2.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = returnFunc(ctx, realm, roleName)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockRolesClient_GetRealmRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRealmRole'
type MockRolesClient_GetRealmRole_Call struct {
	*mock.Call
}

// GetRealmRole is a helper method to define mock.On call
//   - ctx context.Context
//   - realm string
//   - roleName string
func (_e *MockRolesClient_Expecter) GetRealmRole(ctx interface{}, realm interface{}, roleName interface{}) *MockRolesClient_GetRealmRole_Call {
	return &MockRolesClient_GetRealmRole_Call{Call: _e.mock.On("GetRealmRole", ctx, realm, roleName)}
}

func (_c *MockRolesClient_GetRealmRole_Call) Run(run func(ctx context.Context, realm string, roleName string)) *MockRolesClient_GetRealmRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRolesClient_GetRealmRole_Call) Return(v *keycloakv2.RoleRepresentation, response *keycloakv2.Response, err error) *MockRolesClient_GetRealmRole_Call {
	_c.Call.Return(v, response, err)
	return _c
}

func (_c *MockRolesClient_GetRealmRole_Call) RunAndReturn(run func(ctx context.Context, realm string, roleName string) (*keycloakv2.RoleRepresentation, *keycloakv2.Response, error)) *MockRolesClient_GetRealmRole_Call {
	_c.Call.Return(run)
	return _c
}

// GetRealmRoles provides a mock function for the type MockRolesClient
func (_mock *MockRolesClient) GetRealmRoles(ctx context.Context, realm string, params *keycloakv2.GetRealmRolesParams) ([]keycloakv2.RoleRepresentation, *keycloakv2.Response, error) {
	ret := _mock.Called(ctx, realm, params)

	if len(ret) == 0 {
		panic("no return value specified for GetRealmRoles")
	}

	var r0 []keycloakv2.RoleRepresentation
	var r1 *keycloakv2.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *keycloakv2.GetRealmRolesParams) ([]keycloakv2.RoleRepresentation, *keycloakv2.Response, error)); ok {
		return returnFunc(ctx, realm, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *keycloakv2.GetRealmRolesParams) []keycloakv2.RoleRepresentation); ok {
		r0 = returnFunc(ctx, realm, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]keycloakv2.RoleRepresentation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *keycloakv2.GetRealmRolesParams) *keycloakv2.Response); ok {
		r1 = returnFunc(ctx, realm, params)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*keycloakv2.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, *keycloakv2.GetRealmRolesParams) error); ok {
		r2 = returnFunc(ctx, realm, params)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockRolesClient_GetRealmRoles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRealmRoles'
type MockRolesClient_GetRealmRoles_Call struct {
	*mock.Call
}

// GetRealmRoles is a helper method to define mock.On call
//   - ctx context.Context
//   - realm string
//   - params *keycloakv2.GetRealmRolesParams
func (_e *MockRolesClient_Expecter) GetRealmRoles(ctx interface{}, realm interface{}, params interface{}) *MockRolesClient_GetRealmRoles_Call {
	return &MockRolesClient_GetRealmRoles_Call{Call: _e.mock.On("GetRealmRoles", ctx, realm, params)}
}

func (_c *MockRolesClient_GetRealmRoles_Call) Run(run func(ctx context.Context, realm string, params *keycloakv2.GetRealmRolesParams)) *MockRolesClient_GetRealmRoles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *keycloakv2.GetRealmRolesParams
		if args[2] != nil {
			arg2 = args[2].(*keycloakv2.GetRealmRolesParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRolesClient_GetRealmRoles_Call) Return(vs []keycloakv2.RoleRepresentation, response *keycloakv2.Response, err error) *MockRolesClient_GetRealmRoles_Call {
	_c.Call.Return(vs, response, err)
	return _c
}

func (_c *MockRolesClient_GetRealmRoles_Call) RunAndReturn(run func(ctx context.Context, realm string, params *keycloakv2.GetRealmRolesParams) ([]keycloakv2.RoleRepresentation, *keycloakv2.Response, error)) *MockRolesClient_GetRealmRoles_Call {
	_c.Call.Return(run)
	return _c
}
