// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/epam/edp-keycloak-operator/pkg/client/keycloakv2"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSessionsClient creates a new instance of MockSessionsClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionsClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionsClient {
	mock := &MockSessionsClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSessionsClient is an autogenerated mock type for the SessionsClient type
type MockSessionsClient struct {
	mock.Mock
}

type MockSessionsClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionsClient) EXPECT() *MockSessionsClient_Expecter {
	return &MockSessionsClient_Expecter{mock: &_m.Mock}
}

// GetRealmSessionStats provides a mock function for the type MockSessionsClient
func (_mock *MockSessionsClient) GetRealmSessionStats(ctx context.Context, realm string) ([]map[string]string, *keycloakv2.Response, error) {
	ret := _mock.Called(ctx, realm)

	if len(ret) == 0 {
		panic("no return value specified for GetRealmSessionStats")
	}

	var r0 []map[string]string
	var r1 *keycloakv2.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]map[string]string, *keycloakv2.Response, error)); ok {
		return returnFunc(ctx, realm)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []map[string]string); ok {
		r0 = returnFunc(ctx, realm)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]map[string]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) *keycloakv2.Response); ok {
		r1 = returnFunc(ctx, realm)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*keycloakv2.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, realm)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockSessionsClient_GetRealmSessionStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRealmSessionStats'
type MockSessionsClient_GetRealmSessionStats_Call struct {
	*mock.Call
}

// GetRealmSessionStats is a helper method to define mock.On call
//   - ctx context.Context
//   - realm string
func (_e *MockSessionsClient_Expecter) GetRealmSessionStats(ctx interface{}, realm interface{}) *MockSessionsClient_GetRealmSessionStats_Call {
	return &MockSessionsClient_GetRealmSessionStats_Call{Call: _e.mock.On("GetRealmSessionStats", ctx, realm)}
}

func (_c *MockSessionsClient_GetRealmSessionStats_Call) Run(run func(ctx context.Context, realm string)) *MockSessionsClient_GetRealmSessionStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionsClient_GetRealmSessionStats_Call) Return(stringToStrings []map[string]string, response *keycloakv2.Response, err error) *MockSessionsClient_GetRealmSessionStats_Call {
	_c.Call.Return(stringToStrings, response, err)
	return _c
}

func (_c *MockSessionsClient_GetRealmSessionStats_Call) RunAndReturn(run func(ctx context.Context, realm string) ([]map[string]string, *keycloakv2.Response, error)) *MockSessionsClient_GetRealmSessionStats_Call {
	_c.Call.Return(run)
	return _c
}

// LogoutAllSessions provides a mock function for the type MockSessionsClient
func (_mock *MockSessionsClient) LogoutAllSessions(ctx context.Context, realm string) (*keycloakv2.Response, error) {
	ret := _mock.Called(ctx, realm)

	if len(ret) == 0 {
		panic("no return value specified for LogoutAllSessions")
	}

	var r0 *keycloakv2.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*keycloakv2.Response, error)); ok {
		return returnFunc(ctx, realm)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *keycloakv2.Response); ok {
		r0 = returnFunc(ctx, realm)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*keycloakv2.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, realm)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionsClient_LogoutAllSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogoutAllSessions'
type MockSessionsClient_LogoutAllSessions_Call struct {
	*mock.Call
}

// LogoutAllSessions is a helper method to define mock.On call
//   - ctx context.Context
//   - realm string
func (_e *MockSessionsClient_Expecter) LogoutAllSessions(ctx interface{}, realm interface{}) *MockSessionsClient_LogoutAllSessions_Call {
	return &MockSessionsClient_LogoutAllSessions_Call{Call: _e.mock.On("LogoutAllSessions", ctx, realm)}
}

func (_c *MockSessionsClient_LogoutAllSessions_Call) Run(run func(ctx context.Context, realm string)) *MockSessionsClient_LogoutAllSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionsClient_LogoutAllSessions_Call) Return(response *keycloakv2.Response, err error) *MockSessionsClient_LogoutAllSessions_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockSessionsClient_LogoutAllSessions_Call) RunAndReturn(run func(ctx context.Context, realm string) (*keycloakv2.Response, error)) *MockSessionsClient_LogoutAllSessions_Call {
	_c.Call.Return(run)
	return _c
}
