// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/epam/edp-keycloak-operator/pkg/client/keycloakv2"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUsersClient creates a new instance of MockUsersClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUsersClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUsersClient {
	mock := &MockUsersClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUsersClient is an autogenerated mock type for the UsersClient type
type MockUsersClient struct {
	mock.Mock
}

type MockUsersClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUsersClient) EXPECT() *MockUsersClient_Expecter {
	return &MockUsersClient_Expecter{mock: &_m.Mock}
}

// AddUserRealmRoles provides a mock function for the type MockUsersClient
func (_mock *MockUsersClient) AddUserRealmRoles(ctx context.Context, realm string, userID string, roles []keycloakv2.RoleRepresentation) (*keycloakv2.Response, error) {
	ret := _mock.Called(ctx, realm, userID, roles)

	if len(ret) == 0 {
		panic("no return value specified for AddUserRealmRoles")
	}

	var r0 *keycloakv2.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []keycloakv2.RoleRepresentation) (*keycloakv2.Response, error)); ok {
		return returnFunc(ctx, realm, userID, roles)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []keycloakv2.RoleRepresentation) *keycloakv2.Response); ok {
		r0 = returnFunc(ctx, realm, userID, roles)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*keycloakv2.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, []keycloakv2.RoleRepresentation) error); ok {
		r1 = returnFunc(ctx, realm, userID, roles)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsersClient_AddUserRealmRoles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddUserRealmRoles'
type MockUsersClient_AddUserRealmRoles_Call struct {
	*mock.Call
}

// AddUserRealmRoles is a helper method to define mock.On call
//   - ctx context.Context
//   - realm string
//   - userID string
//   - roles []keycloakv2.RoleRepresentation
func (_e *MockUsersClient_Expecter) AddUserRealmRoles(ctx interface{}, realm interface{}, userID interface{}, roles interface{}) *MockUsersClient_AddUserRealmRoles_Call {
	return &MockUsersClient_AddUserRealmRoles_Call{Call: _e.mock.On("AddUserRealmRoles", ctx, realm, userID, roles)}
}

func (_c *MockUsersClient_AddUserRealmRoles_Call) Run(run func(ctx context.Context, realm string, userID string, roles []keycloakv2.RoleRepresentation)) *MockUsersClient_AddUserRealmRoles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []keycloakv2.RoleRepresentation
		if args[3] != nil {
			arg3 = args[3].([]keycloakv2.RoleRepresentation)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockUsersClient_AddUserRealmRoles_Call) Return(response *keycloakv2.Response, err error) *MockUsersClient_AddUserRealmRoles_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockUsersClient_AddUserRealmRoles_Call) RunAndReturn(run func(ctx context.Context, realm string, userID string, roles []keycloakv2.RoleRepresentation) (*keycloakv2.Response, error)) *MockUsersClient_AddUserRealmRoles_Call {
	_c.Call.Return(run)
	return _c
}

// AddUserToGroup provides a mock function for the type MockUsersClient
func (_mock *MockUsersClient) AddUserToGroup(ctx context.Context, realm string, userID string, groupID string) (*keycloakv2.Response, error) {
	ret := _mock.Called(ctx, realm, userID, groupID)

	if len(ret) == 0 {
		panic("no return value specified for AddUserToGroup")
	}

	var r0 *keycloakv2.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (*keycloakv2.Response, error)); ok {
		return returnFunc(ctx, realm, userID, groupID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) *keycloakv2.Response); ok {
		r0 = returnFunc(ctx, realm, userID, groupID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*keycloakv2.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, realm, userID, groupID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsersClient_AddUserToGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddUserToGroup'
type MockUsersClient_AddUserToGroup_Call struct {
	*mock.Call
}

// AddUserToGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - realm string
//   - userID string
//   - groupID string
func (_e *MockUsersClient_Expecter) AddUserToGroup(ctx interface{}, realm interface{}, userID interface{}, groupID interface{}) *MockUsersClient_AddUserToGroup_Call {
	return &MockUsersClient_AddUserToGroup_Call{Call: _e.mock.On("AddUserToGroup", ctx, realm, userID, groupID)}
}

func (_c *MockUsersClient_AddUserToGroup_Call) Run(run func(ctx context.Context, realm string, userID string, groupID string)) *MockUsersClient_AddUserToGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockUsersClient_AddUserToGroup_Call) Return(response *keycloakv2.Response, err error) *MockUsersClient_AddUserToGroup_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockUsersClient_AddUserToGroup_Call) RunAndReturn(run func(ctx context.Context, realm string, userID string, groupID string) (*keycloakv2.Response, error)) *MockUsersClient_AddUserToGroup_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function for the type MockUsersClient
func (_mock *MockUsersClient) CreateUser(ctx context.Context, realm string, user keycloakv2.UserRepresentation) (*keycloakv2.Response, error) {
	ret := _mock.Called(ctx, realm, user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *keycloakv2.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, keycloakv2.UserRepresentation) (*keycloakv2.Response, error)); ok {
		return returnFunc(ctx, realm, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, keycloakv2.UserRepresentation) *keycloakv2.Response); ok {
		r0 = returnFunc(ctx, realm, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*keycloakv2.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, keycloakv2.UserRepresentation) error); ok {
		r1 = returnFunc(ctx, realm, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsersClient_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockUsersClient_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - realm string
//   - user keycloakv2.UserRepresentation
func (_e *MockUsersClient_Expecter) CreateUser(ctx interface{}, realm interface{}, user interface{}) *MockUsersClient_CreateUser_Call {
	return &MockUsersClient_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, realm, user)}
}

func (_c *MockUsersClient_CreateUser_Call) Run(run func(ctx context.Context, realm string, user keycloakv2.UserRepresentation)) *MockUsersClient_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 keycloakv2.UserRepresentation
		if args[2] != nil {
			arg2 = args[2].(keycloakv2.UserRepresentation)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUsersClient_CreateUser_Call) Return(response *keycloakv2.Response, err error) *MockUsersClient_CreateUser_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockUsersClient_CreateUser_Call) RunAndReturn(run func(ctx context.Context, realm string, user keycloakv2.UserRepresentation) (*keycloakv2.Response, error)) *MockUsersClient_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// FindUserByUsername provides a mock function for the type MockUsersClient
func (_mock *MockUsersClient) FindUserByUsername(ctx context.Context, realm string, username string) (*keycloakv2.UserRepresentation, *keycloakv2.Response, error) {
	ret := _mock.Called(ctx, realm, username)

	if len(ret) == 0 {
		panic("no return value specified for FindUserByUsername")
	}

	var r0 *keycloakv2.UserRepresentation
	var r1 *keycloakv2.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*keycloakv2.UserRepresentation, *keycloakv2.Response, error)); ok {
		return returnFunc(ctx, realm, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *keycloakv2.UserRepresentation); ok {
		r0 = returnFunc(ctx, realm, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*keycloakv2.UserRepresentation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) *keycloakv2.Response); ok {
		r1 = returnFunc(ctx, realm, username)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*keycloakv2.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = returnFunc(ctx, realm, username)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockUsersClient_FindUserByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUserByUsername'
type MockUsersClient_FindUserByUsername_Call struct {
	*mock.Call
}

// FindUserByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - realm string
//   - username string
func (_e *MockUsersClient_Expecter) FindUserByUsername(ctx interface{}, realm interface{}, username interface{}) *MockUsersClient_FindUserByUsername_Call {
	return &MockUsersClient_FindUserByUsername_Call{Call: _e.mock.On("FindUserByUsername", ctx, realm, username)}
}

func (_c *MockUsersClient_FindUserByUsername_Call) Run(run func(ctx context.Context, realm string, username string)) *MockUsersClient_FindUserByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUsersClient_FindUserByUsername_Call) Return(v *keycloakv2.UserRepresentation, response *keycloakv2.Response, err error) *MockUsersClient_FindUserByUsername_Call {
	_c.Call.Return(v, response, err)
	return _c
}

func (_c *MockUsersClient_FindUserByUsername_Call) RunAndReturn(run func(ctx context.Context, realm string, username string) (*keycloakv2.UserRepresentation, *keycloakv2.Response, error)) *MockUsersClient_FindUserByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserGroups provides a mock function for the type MockUsersClient
func (_mock *MockUsersClient) GetUserGroups(ctx context.Context, realm string, userID string) ([]keycloakv2.GroupRepresentation, *keycloakv2.Response, error) {
	ret := _mock.Called(ctx, realm, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserGroups")
	}

	var r0 []keycloakv2.GroupRepresentation
	var r1 *keycloakv2.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]keycloakv2.GroupRepresentation, *keycloakv2.Response, error)); ok {
		return returnFunc(ctx, realm, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []keycloakv2.GroupRepresentation); ok {
		r0 = returnFunc(ctx, realm, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]keycloakv2.GroupRepresentation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) *keycloakv2.Response); ok {
		r1 = returnFunc(ctx, realm, userID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*keycloakv2.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = returnFunc(ctx, realm, userID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockUsersClient_GetUserGroups_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserGroups'
type MockUsersClient_GetUserGroups_Call struct {
	*mock.Call
}

// GetUserGroups is a helper method to define mock.On call
//   - ctx context.Context
//   - realm string
//   - userID string
func (_e *MockUsersClient_Expecter) GetUserGroups(ctx interface{}, realm interface{}, userID interface{}) *MockUsersClient_GetUserGroups_Call {
	return &MockUsersClient_GetUserGroups_Call{Call: _e.mock.On("GetUserGroups", ctx, realm, userID)}
}

func (_c *MockUsersClient_GetUserGroups_Call) Run(run func(ctx context.Context, realm string, userID string)) *MockUsersClient_GetUserGroups_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUsersClient_GetUserGroups_Call) Return(vs []keycloakv2.GroupRepresentation, response *keycloakv2.Response, err error) *MockUsersClient_GetUserGroups_Call {
	_c.Call.Return(vs, response, err)
	return _c
}

func (_c *MockUsersClient_GetUserGroups_Call) RunAndReturn(run func(ctx context.Context, realm string, userID string) ([]keycloakv2.GroupRepresentation, *keycloakv2.Response, error)) *MockUsersClient_GetUserGroups_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserRealmRoleMappings provides a mock function for the type MockUsersClient
func (_mock *MockUsersClient) GetUserRealmRoleMappings(ctx context.Context, realm string, userID string) ([]keycloakv2.RoleRepresentation, *keycloakv2.Response, error) {
	ret := _mock.Called(ctx, realm, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserRealmRoleMappings")
	}

	var r0 []keycloakv2.RoleRepresentation
	var r1 *keycloakv2.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]keycloakv2.RoleRepresentation, *keycloakv2.Response, error)); ok {
		return returnFunc(ctx, realm, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []keycloakv2.RoleRepresentation); ok {
		r0 = returnFunc(ctx, realm, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]keycloakv2.RoleRepresentation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) *keycloakv2.Response); ok {
		r1 = returnFunc(ctx, realm, userID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*keycloakv2.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = returnFunc(ctx, realm, userID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockUsersClient_GetUserRealmRoleMappings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserRealmRoleMappings'
type MockUsersClient_GetUserRealmRoleMappings_Call struct {
	*mock.Call
}

// GetUserRealmRoleMappings is a helper method to define mock.On call
//   - ctx context.Context
//   - realm string
//   - userID string
func (_e *MockUsersClient_Expecter) GetUserRealmRoleMappings(ctx interface{}, realm interface{}, userID interface{}) *MockUsersClient_GetUserRealmRoleMappings_Call {
	return &MockUsersClient_GetUserRealmRoleMappings_Call{Call: _e.mock.On("GetUserRealmRoleMappings", ctx, realm, userID)}
}

func (_c *MockUsersClient_GetUserRealmRoleMappings_Call) Run(run func(ctx context.Context, realm string, userID string)) *MockUsersClient_GetUserRealmRoleMappings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUsersClient_GetUserRealmRoleMappings_Call) Return(vs []keycloakv2.RoleRepresentation, response *keycloakv2.Response, err error) *MockUsersClient_GetUserRealmRoleMappings_Call {
	_c.Call.Return(vs, response, err)
	return _c
}

func (_c *MockUsersClient_GetUserRealmRoleMappings_Call) RunAndReturn(run func(ctx context.Context, realm string, userID string) ([]keycloakv2.RoleRepresentation, *keycloakv2.Response, error)) *MockUsersClient_GetUserRealmRoleMappings_Call {
	_c.Call.Return(run)
	return _c
}

// GetUsersProfile provides a mock function for the type MockUsersClient
func (_mock *MockUsersClient) GetUsersProfile(ctx context.Context, realm string) (*keycloakv2.UserProfileConfig, *keycloakv2.Response, error) {
	ret := _mock.Called(ctx, realm)

	if len(ret) == 0 {
		panic("no return value specified for GetUsersProfile")
	}

	var r0 *keycloakv2.UserProfileConfig
	var r1 *keycloakv2.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*keycloakv2.UserProfileConfig, *keycloakv2.Response, error)); ok {
		return returnFunc(ctx, realm)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *keycloakv2.UserProfileConfig); ok {
		r0 = returnFunc(ctx, realm)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*keycloakv2.UserProfileConfig)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) *keycloakv2.Response); ok {
		r1 = returnFunc(ctx, realm)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*keycloakv2.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, realm)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockUsersClient_GetUsersProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsersProfile'
type MockUsersClient_GetUsersProfile_Call struct {
	*mock.Call
}

// GetUsersProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - realm string
func (_e *MockUsersClient_Expecter) GetUsersProfile(ctx interface{}, realm interface{}) *MockUsersClient_GetUsersProfile_Call {
	return &MockUsersClient_GetUsersProfile_Call{Call: _e.mock.On("GetUsersProfile", ctx, realm)}
}

func (_c *MockUsersClient_GetUsersProfile_Call) Run(run func(ctx context.Context, realm string)) *MockUsersClient_GetUsersProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsersClient_GetUsersProfile_Call) Return(v *keycloakv2.UserProfileConfig, response *keycloakv2.Response, err error) *MockUsersClient_GetUsersProfile_Call {
	_c.Call.Return(v, response, err)
	return _c
}

func (_c *MockUsersClient_GetUsersProfile_Call) RunAndReturn(run func(ctx context.Context, realm string) (*keycloakv2.UserProfileConfig, *keycloakv2.Response, error)) *MockUsersClient_GetUsersProfile_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveUserFromGroup provides a mock function for the type MockUsersClient
func (_mock *MockUsersClient) RemoveUserFromGroup(ctx context.Context, realm string, userID string, groupID string) (*keycloakv2.Response, error) {
	ret := _mock.Called(ctx, realm, userID, groupID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveUserFromGroup")
	}

	var r0 *keycloakv2.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (*keycloakv2.Response, error)); ok {
		return returnFunc(ctx, realm, userID, groupID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) *keycloakv2.Response); ok {
		r0 = returnFunc(ctx, realm, userID, groupID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*keycloakv2.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, realm, userID, groupID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsersClient_RemoveUserFromGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveUserFromGroup'
type MockUsersClient_RemoveUserFromGroup_Call struct {
	*mock.Call
}

// RemoveUserFromGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - realm string
//   - userID string
//   - groupID string
func (_e *MockUsersClient_Expecter) RemoveUserFromGroup(ctx interface{}, realm interface{}, userID interface{}, groupID interface{}) *MockUsersClient_RemoveUserFromGroup_Call {
	return &MockUsersClient_RemoveUserFromGroup_Call{Call: _e.mock.On("RemoveUserFromGroup", ctx, realm, userID, groupID)}
}

func (_c *MockUsersClient_RemoveUserFromGroup_Call) Run(run func(ctx context.Context, realm string, userID string, groupID string)) *MockUsersClient_RemoveUserFromGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockUsersClient_RemoveUserFromGroup_Call) Return(response *keycloakv2.Response, err error) *MockUsersClient_RemoveUserFromGroup_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockUsersClient_RemoveUserFromGroup_Call) RunAndReturn(run func(ctx context.Context, realm string, userID string, groupID string) (*keycloakv2.Response, error)) *MockUsersClient_RemoveUserFromGroup_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUsersProfile provides a mock function for the type MockUsersClient
func (_mock *MockUsersClient) UpdateUsersProfile(ctx context.Context, realm string, userProfile keycloakv2.UserProfileConfig) (*keycloakv2.UserProfileConfig, *keycloakv2.Response, error) {
	ret := _mock.Called(ctx, realm, userProfile)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUsersProfile")
	}

	var r0 *keycloakv2.UserProfileConfig
	var r1 *keycloakv2.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, keycloakv2.UserProfileConfig) (*keycloakv2.UserProfileConfig, *keycloakv2.Response, error)); ok {
		return returnFunc(ctx, realm, userProfile)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, keycloakv2.UserProfileConfig) *keycloakv2.UserProfileConfig); ok {
		r0 = returnFunc(ctx, realm, userProfile)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*keycloakv2.UserProfileConfig)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, keycloakv2.UserProfileConfig) *keycloakv2.Response); ok {
		r1 = returnFunc(ctx, realm, userProfile)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*keycloakv2.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, keycloakv2.UserProfileConfig) error); ok {
		r2 = returnFunc(ctx, realm, userProfile)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockUsersClient_UpdateUsersProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUsersProfile'
type MockUsersClient_UpdateUsersProfile_Call struct {
	*mock.Call
}

// UpdateUsersProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - realm string
//   - userProfile keycloakv2.UserProfileConfig
func (_e *MockUsersClient_Expecter) UpdateUsersProfile(ctx interface{}, realm interface{}, userProfile interface{}) *MockUsersClient_UpdateUsersProfile_Call {
	return &MockUsersClient_UpdateUsersProfile_Call{Call: _e.mock.On("UpdateUsersProfile", ctx, realm, userProfile)}
}

func (_c *MockUsersClient_UpdateUsersProfile_Call) Run(run func(ctx context.Context, realm string, userProfile keycloakv2.UserProfileConfig)) *MockUsersClient_UpdateUsersProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 keycloakv2.UserProfileConfig
		if args[2] != nil {
			arg2 = args[2].(keycloakv2.UserProfileConfig)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUsersClient_UpdateUsersProfile_Call) Return(v *keycloakv2.UserProfileConfig, response *keycloakv2.Response, err error) *MockUsersClient_UpdateUsersProfile_Call {
	_c.Call.Return(v, response, err)
	return _c
}

func (_c *MockUsersClient_UpdateUsersProfile_Call) RunAndReturn(run func(ctx context.Context, realm string, userProfile keycloakv2.UserProfileConfig) (*keycloakv2.UserProfileConfig, *keycloakv2.Response, error)) *MockUsersClient_UpdateUsersProfile_Call {
	_c.Call.Return(run)
	return _c
}
