apiVersion: v1.edp.epam.com/v1
kind: Keycloak
metadata:
  name: "main"
  labels:
    {{- include "keycloak-operator.labels" . | nindent 4 }}
spec:
  url: {{ .Values.keycloak.url }}
  secret: "keycloak"
