apiVersion: v1.edp.epam.com/v1
kind: KeycloakRealmRoleBatch
metadata:
  name: "default-roles"
spec:
  realm: main
  roles:
    - name: developer
      composite: true
      description: "default developer role"
      isDefault: false
    - name: administrator
      composite: true
      description: "default administrator role"
