apiVersion: v1.edp.epam.com/v1alpha1
kind: Keycloak
metadata:
  name: "main"
spec:
  url: {{ .Values.keycloak.url }}
  secret: "keycloak"
  users:
  {{- range .Values.global.admins }}
  - username: {{.}}
    realmRoles:
      - administrator
  {{- end}}
  {{- range .Values.global.developers }}
  - username: {{.}}
    realmRoles:
      - developer
  {{- end}}